### ISSUE TITLE
Failed to start container with Docker for Mac

### ISSUE THREAD

**Issue by ayayron** [openanalytics/shinyproxy#1]
I have the new version of Docker for Mac, which is a bit different than Docker Toolbox (https://docs.docker.com/docker-for-mac/docker-toolbox/). 

To the Docker demo, I add the port (in Kitematic):
Docker port = "3838" -> MacIP:port = "localhost:2375"

When starting the server and trying to open 01_hello Shiny app, I get the following error:
> Status code: 500
> Message: Failed to start container: Request error: POST http://localhost:2375/containers/create: 413

Getting the log from `syslog -k Sender Docker` I see:
> <Notice>: Created instance tcp:0.0.0.0:2375:tcp:172.17.0.2:3838

**Comment by rajshah4** [comment]
This is how I got shinyproxy running on my mac:

1. Use the command: `docker-machine env default` to get my settings:  
    export DOCKER_TLS_VERIFY=&quot;1&quot;  
    export DOCKER_HOST="tcp://192.168.99.100:2376"  
    export DOCKER_CERT_PATH="/Users/rajivshah/.docker/machine/machines/default"  
    export DOCKER_MACHINE_NAME="default"
2. Update the application.yml file to:  
    cert-path: /Users/rajivshah/.docker/machine/machines/default      
    url: https://192.168.99.100:2376     
    host: 192.168.99.100```
3. Ran the recompile of the jar file `zip -r -Zstore ../shinyproxy-0.3.0.jar *`  

4. Then run the java file: `java -jar shinyproxy-0.3.0.jar` (It starts the docker containers when you click on an app)

**Comment by tverbeke** [comment]
Many thanks for sharing @rajshah4 ! I'll add a section to our docs on http://shinyproxy.io

Regarding the `application.yml` file, if you put a customized version in the same folder as the .jar file, the values will be picked up automatically (and overwrite the default configuration).

@ayayron Can you confirm this works for you as well?

**Comment by rajshah4** [comment]
Ahh good, tip about the `application.yml` file.

**Comment by ayayron** [comment]
@rajshah4, I was able to get it to work using your settings using Docker Toolbox, but had to remove the three backticks, ```, from the application.yml file.

**Comment by rajshah4** [comment]
Oop, sorry about that, it was markdown that was showing up, I fixed it in the above post and removed the tick marks . . . glad you got it working
