### ISSUE TITLE
Error creating bean with name 'springSecurityFilterChain' 

### ISSUE THREAD

**Issue by cmattoon** [openanalytics/shinyproxy#10]
Possibly related to #4 ?

When `application.yml` is present (used default example on website, plus a trimmed-down version), I get the following error when running `java -jar shinyproxy-0.9.1.jar`:

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NullPointerException

This error only occurs when the config file is present. On its own, it works fine. Logs are below:

Fail (with application.yml): https://pastebin.com/4CDqMG38
Success (no config file): https://pastebin.com/mXrF1bLS

```
root@shinyproxy: # java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by fmichielssen** [comment]
Hi,

Can you check your application.yml for the presence of the authentication property? E.g.
`shiny:  proxy:  authentication: none`
This property cannot be omitted, please use 'none' for no authentication.
