### ISSUE TITLE
Url pathname always returns endpoint url

### ISSUE THREAD

**Issue by dylancis** [openanalytics/shinyproxy#102]
While using the` /app/myshinyapp/ `url style and printing the following statements:
```
print("–start of clientData–")
print(session$clientData$url_protocol)
print(session$clientData$url_hostname)
print(session$clientData$url_port)
print(session$clientData$url_pathname)
print("–end of clientData–")
```

I got:
```
[1] “–start of clientData–”
[1] “http:”
[1] “myshinyapp.dbrs.local”
[1] “”
[1] “/endpoint/b7219443-8125-41d4-9894-b19b1602614c/”
[1] “–end of clientData–”
```

I would understand if if I was using the app_direct style but here it is a bit confusing, I think
`session$clientData$url_pathname`
should return `app/myshinyapp/ ` instead, don’t you agree ?

Thank you

**Comment by fmichielssen** [comment]
Hi @dylancis, the upcoming release will support this, showing `/app_direct/<app-name>` instead of `/endpoint/<proxy-id>`, regardless of whether the app is accessed via iframe or directly.

**Comment by dylancis** [comment]
Hi @fmichielssen - this is awesome. Thanks. Do you mean also in the browser url itself ?

**Comment by dylancis** [comment]
Also @fmichielssen , is there a way to set which one between /app/ and /app_direct/ to use by default on the landing page:

![image](https://user-images.githubusercontent.com/4976433/54815347-aab91e80-4c89-11e9-975c-f60e24cab6e9.png)

This is pointing to `<a href="/app/eurmbsinsight">EU RMBS Insight Model</a>` but what bout if by default we would like `<a href="/app_direct/eurmbsinsight">`EU RMBS Insight Model</a> instead ?

**Comment by dylancis** [comment]
Hi @fmichielssen we have not deployed 2.2.1 and while I now see /`app_direct/` in the JS condole:
![image](https://user-images.githubusercontent.com/4976433/56197407-abe32e80-6030-11e9-8e42-4ba872d2ea4e.png)

If I tried to amend the url once the app is lunched to use `/app_direct/` instead of `/app/` I get a 503 error code:
![image](https://user-images.githubusercontent.com/4976433/56197467-cb7a5700-6030-11e9-98fe-f06dbe4c0ca0.png)

I used to be able to do this in earlier version - anything I do wrong maybe ?
Thank you, Dylan

**Comment by tverbeke** [comment]
Hi @dylancis Maybe the following is relevant:
https://support.openanalytics.eu/t/app-direct-functionality/1108

**Comment by dylancis** [comment]
thanks @tverbeke got it a forward slash is needed at the end of the url such as `/app_direct/modelappname/` to make it works.
Is there any reason why the `'` id required here ? Also I looked at https://www.shinyproxy.io/configuration/ and it seems there is no way we can specify the redirect mode `/app/` vs `/app_direct/` via the `ShinyProxy` landing page.

It would be useful to have an option within the configuration `YAML` file such as:
```
 specs:
  - id: 01_hello
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    app_url: app_direct (or app)
    access-groups: [scientists, mathematicians]
```
