### ISSUE TITLE
Possibility to use kubernetes secrets?

### ISSUE THREAD

**Issue by Emelieh21** [openanalytics/shinyproxy#104]
Hey guys,

Is it possible to attach kubernetes secrets to a container? I have a shiny app that needs it to access credentials for a database. I looked into the image-pull-secret, but it seems like this is just for secrets related to pulling images from a docker registry right?

Thanks a lot in advance!

Cheers,

Emelie

**Comment by Emelieh21** [comment]
Another small question on which I could not find the answer in the documentation... Is it somehow possible to [put an AWS IAM role annotation](https://github.com/jtblin/kube2iam#kubernetes-annotation) to a container that is launched with the shiny proxy?

**Comment by fmichielssen** [comment]
Hi @Emelieh21 ,

Support for kubernetes-specific settings is currently fairly minimal, and doesn't include secrets or annotations:
https://github.com/openanalytics/containerproxy/blob/3e89377a4d3f4238df59bb5f1d43f579c77e0aac/src/main/java/eu/openanalytics/containerproxy/backend/kubernetes/KubernetesBackend.java#L108

This will likely be improved in the coming months, as there is now a lot of focus on kubernetes support; there is already a PR for node-selector: https://github.com/openanalytics/containerproxy/pulls

**Comment by tverbeke** [comment]
Hi @Emelieh21 

ShinyProxy 2.2.2 supports the usage of secret key refs using the following syntax:

```proxy:
  specs:
  - id: 01_hello
    container-env:
      MY_VAR: "secretKeyRef:<name>:<key>" 
```

Thanks again for your feedback!

Best,
Tobias

**Comment by Emelieh21** [comment]
Hey Tobias!

Thanks a lot :) It works like a charm! 

Cheers,

Emelie

**Comment by Emelieh21** [comment]
Hey guys, should I open a separate feature request for the metadata annotations (for AWS IAM roles, as mentioned in the comment above)?

**Comment by tverbeke** [comment]
Hi @Emelieh21 Maybe best, yes. We overlooked it.
