### ISSUE TITLE
OpenID connect logging

### ISSUE THREAD

**Issue by gbisschoff** [openanalytics/shinyproxy#105]
When a user logs in using the openid flow it does not show in the log that the user has logged in.
It does show when the user logs out.

**Comment by fmichielssen** [comment]
Thanks for the heads up.
A fix has been committed: https://github.com/openanalytics/containerproxy/commit/c173790a7fde76e720314b328e7b6ab3f3d6dc2c
and will be in the upcoming release

**Comment by tverbeke** [comment]
@gbisschoff fix released in ShinyProxy 2.1.0
