### ISSUE TITLE
Admin authorization fails when auth-groups is an array

### ISSUE THREAD

**Issue by warnes** [openanalytics/shinyproxy#107]
When `admin-groups` is a singleton:
```
admin-groups: "Test"
```
, members of the group are correctly granted Admin access. However, when it is an array (even with a single element) members of the group(s) are *not* granted Admin access:
```
admin-groups: [ "Test" ]
```

See https://github.com/openanalytics/containerproxy/issues/8

**Comment by fmichielssen** [comment]
Issue is being tracked here: https://github.com/openanalytics/containerproxy/issues/8
Closing this one.
