### ISSUE TITLE
Error on running shinyproxy.jar with application.yml

### ISSUE THREAD

**Issue by kiwimic** [openanalytics/shinyproxy#11]
Ubuntu 16.04.

When i run shinyproxy.jar from folder without application.yml (with standard configuration coppied form https://www.shinyproxy.io/configuration/#overview) i have no problem to run app (hello application, 06_tabsets). But when i copy this file into directory with shinyproxy.jar and run this standard configuration. Shiny proxy stops on 4th step in inicilizastion and produce this log.
[shinyproxy.txt](https://github.com/openanalytics/shinyproxy/files/1019877/shinyproxy.txt)

**Comment by fmichielssen** [comment]
Hi,

The docs may have changed in the meantime, I'm not sure, but please make sure this property is set in your yml:
`
shiny:
  proxy:
    docker:
      cert-path: /home/none
`
