### ISSUE TITLE
fetch active application

### ISSUE THREAD

**Issue by romunov** [openanalytics/shinyproxy#110]
I have posted this [to the community](https://support.openanalytics.eu/t/is-there-a-way-to-access-active-app-id-from-navbar/825) but it would probably make more sense to put feature requests here.

What:
It would be neat to have access to currently running user session application in some particular window. Not sure how this is possible for 'edge' case where user might have more than one application open.

Use case:
Have a button to part of the documentation relevant for particular app.
Design navbar based on active app.

How:
I would like to fetch active app (e.g. `app.active`, `app.loaded`), check its name, id... and based on the result construct some logic, e.g. link to specific part of some documentation.

**Comment by LEDfan** [comment]
On the app pages (e.g. `/app/myapp`) you can access the `appName` variable in the HTML template, e.g.:

```html
<span class="navbar-brand" th:if="${appName}" th:text="${appName}"></span>
````
