### ISSUE TITLE
redirect from shinyapp to external resource

### ISSUE THREAD

**Issue by evfonarik** [openanalytics/shinyproxy#113]
I am trying to simple redirect from shiny app to google via code example:
```
      tags$ul(
        class = "dropdown-menu",
        tags$li(
          tags$a(href = "https://google.com", "redirect to google")
        )
      )
```
In browser I see shiny proxy blank page, but in browser console looks like redirect is ok

![default](https://user-images.githubusercontent.com/45656314/49686546-29d57d00-fb07-11e8-8e66-9fa8256e3479.png)

Whats wrong and whats the right way to redirect from shinyapp? @fmichielssen Could you please help?

**Comment by fmichielssen** [comment]
Hi @evfonarik ,

Since the shiny app is running in an iframe, your redirect needs to target the parent frame.
I'm not familiar with the `tags` approach, but in Javascript it would be this:

`window.top.location.href = "https://google.com"; `

Note the `window.top` instead of `window`.

**Comment by evfonarik** [comment]
Hi @evfonarik 
Thanks for your comment. Will ping developer on R language to adapt this code like on JS.

**Comment by fmichielssen** [comment]
Does that `tags$a` line support the `target` attribute? If so, this might also work:

    tags$a(href = "https://google.com", target = "_parent", "redirect to google")

**Comment by LEDfan** [comment]
As I believe that your question is answered, I'm closing this issue. Feel free to re-open it if you need more help.
