### ISSUE TITLE
landing-page configuration 

### ISSUE THREAD

**Issue by kforner** [openanalytics/shinyproxy#119]
The `landing-page` configuration item, as documented  here https://www.shinyproxy.io/configuration/ states that: 

>landing page: landing page resource; default value is /;

I thought it was a way to redirect the shinyproxy homepage. In my case I wanted to automatically go to my shinyapp, so I put: 
```
landing-page: app/myapp
```
But apparently it changed nothing. 
What did I miss ? 
Thanks

**Comment by trafficonese** [comment]
Did you restart the .jar after making those changes? 

It is working for me.
When I access http://localhost:8080 it redirects me to http://localhost:8080/app/myapp

**Comment by mnazarov** [comment]
Indeed this now works as expected, but it didn't at the time of the original post (Jan 29)

**Comment by kforner** [comment]
good to know, thanks!

**Comment by OGuggenbuehl** [comment]
Could I get some clarification on this? I have added `landing-page: app/MyApp` to my .yml file but the forwarding does not work as expected and I end up at the ShinyProxy landingpage after login.

**Comment by michaelhogersosis** [comment]
@OGuggenbuehl a bit pedantic perhaps, but can you try `landing-page: /app/MyApp`? That seems to work in our setup.

**Comment by OGuggenbuehl** [comment]
> @OGuggenbuehl can you try `landing-page: /app/MyApp`? 
This does not change anything unfortunately.

**Comment by michaelhogersosis** [comment]
@OGuggenbuehl Strange.. Can you perhaps post your yml file?

**Comment by OGuggenbuehl** [comment]
I'd rather not for security reasons. Right now I'll just make due with including the path in the hyperlink directly. Thank you for your help!

**Comment by michaelhogersosis** [comment]
Understood, sounds good !
