### ISSUE TITLE
FYI: apache proxy/reverse proxy configuration for websockets

### ISSUE THREAD

**Issue by kforner** [openanalytics/shinyproxy#120]
Just to share what worked for me. 
I had to use apache to provide HTTPS and authentication, but the shiny app was freezing, because of a failing websocket connection.

To fix it, I used the **proxy_wstunnel** apache module, that must be installed and enabled.
Then I added this in the **vhost** configuration, where `shinyproxy` is the host running the shinyproxy server (probably `localhost` for usual cases):
```apache
 RewriteEngine on
 RewriteCond %{HTTP:Upgrade} =websocket
 RewriteRule /(.*) ws://shinyproxy:8080/$1 [P,L]
```
As a bonus, I also used this to redirect directly to the shiny app:
```apache
 RewriteRule ^/$ /app/myapp [R]
```

**Comment by tverbeke** [comment]
@kforner Many thanks for sharing, we will add this to the documentation shortly.

**Comment by gdancik** [comment]
Thanks for posting this. I am still having a similar problem -- any help is greatly appreciated. 

I am using apache with a proxy/reverse proxy. The app loads and then greys out with the error: "Firefox can’t establish a connection to the server at ws://www.mysite.com/app_direct/01_hello/websocket/" 

My configuration is below:
```
<VirtualHost *:80>
ProxyPass / http://localhost:8080/
ProxyPassReverse / http://localhost:8080/

RewriteEngine on
RewriteCond %{HTTP:Upgrade} =websocket
RewriteRule /{.*} ws://localhost:8080/$1 [P,L]

</VirtualHost>
```

**Comment by ifellows** [comment]
I had a similar issue with Edge using nginx that was fixed by changing my nginx configuration from
```
location /apps/ {
  proxy_pass http://localhost:3838/;
}
```

to

```
location /apps/ {
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_pass http://localhost:3838/;
}
```
