### ISSUE TITLE
[Feature Request] App Idle Timeout

### ISSUE THREAD

**Issue by shrektan** [openanalytics/shinyproxy#121]
As discussed in https://support.openanalytics.eu/t/session-inactive-timeout-while-tab-still-open/814 , 

> Nowadays people can live with a tab open for days or weeks before they close it. Having multiple users, you can end up with a lot of ghost containers being live for nothing.

Although it's possible to implement such a feature at the app level, I think it's desired to have the feature in Shinyproxy's configuration. 

Features I suggest:

- `app_idle_timeout` in the configuration, just like `heartbeat-timeout`
- `app_idle_message` to display a customized message when timeout.

Thanks!

**Comment by fmichielssen** [comment]
That's an interesting idea, @shrektan, thanks for bringing it up!
I think we can measure app idleness by the lack of incoming HTTP requests or websocket frames.
Note, I think there may be some cases that will escape this check. E.g. if the app has implemented some sort of periodic refresh, then the `app_idle_timeout` would never expire.

**Comment by dylancis** [comment]
Another alternative is to track user app interaction like in here: https://stackoverflow.com/questions/33839543/shiny-server-session-time-out-doesnt-work/53207050#53207050

**Comment by LEDfan** [comment]
Hi, I think this is covered by the max-lifetime property (https://shinyproxy.io/documentation/configuration/#max-lifetime), which allows you to specify the maximum amount an app can exist (even if kept open). Therefore, I'm closing this issue. If I misunderstood the feature request, please re-open this issue.

**Comment by AkedoMakona** [comment]
I would like to re-open this discussion. I am having trouble tuning the parameters `heartbeat-timeout` and `servlet.session.timeout` such that my app stays open for users for an indefinite period of time while *in use*, but closes after ~1 hour idle, even if the browser tab is open. I do not want to set a max-lifetime value, as I do not want the app to shutdown on users while they are using it under any circumstances. Is this possible to achieve with the current parameters in 3.1.1?
