### ISSUE TITLE
WebSocket Error with microsoft edge 

### ISSUE THREAD

**Issue by kforner** [openanalytics/shinyproxy#123]
My shinyproxied app does not work with Microsoft Edge (Microsoft Edge 42.17134.1.0; Microsoft EdgeHTML 17.17134), sigh...

In the console I get:
```
SCRIPT12008: SCRIPT12008: WebSocket Error: Incorrect HTTP response. Status code 200, OK
SCRIPT5007: SCRIPT5007: Unable to get property 'readyState' of undefined or null reference
```
It works fine with IE11 11.472.17134.0 but apparently does not for some earlier versions.

I manage the websockets as reported in #120 

Have you already had this type of problems ? 
Is it possible to disable websockets completely, as shiny server supports (cf https://docs.rstudio.com/shiny-server/#disabling-websockets-on-the-server) ?

**Comment by tverbeke** [comment]
Hi @kforner, thank you for the report - it is the first report of this kind AFAIK. The only other Edge related report is #118 

Regarding your second question: ShinyProxy only supports web sockets, no (suboptimal) fallback mechanisms.

We will investigate!

**Comment by gbisschoff** [comment]
This might be related to #65 see my [comment](https://github.com/openanalytics/shinyproxy/issues/65#issuecomment-460197223)?

**Comment by fmichielssen** [comment]
Hi @kforner,

I suspect the Apache configuration must be adjusted. In your post #120 I see this line:

`RewriteRule /(.*) ws://shinyproxy:8080/$1 [P,L]`

But `ws` only works for http. For https, you may have to add a `wss` rewrite as well?

**Comment by kforner** [comment]
Hi @fmichielssen
If the configuration is incorrect, why is it working with all the other browsers and other edge versions ?
I'll try your suggestion. 
thanks.

**Comment by silvano-junior** [comment]
Hi @kforner ,

I'm also trying to make my app use https, but I'm getting only the text "loading app..." and that's it, nothing else happens. Can you share the virtual host code that worked for you?

Thanks in advance,
Silvano

**Comment by LEDfan** [comment]
Hi

We now have documentation on how to use Apache as a reverse proxy for ShinyProxy: https://shinyproxy.io/documentation/security/#https-ssl--tls

This should solve your issue. If you need more help, feel free to re-open or open a new issue.
