### ISSUE TITLE
Add support to port-range-max + port-range-start with internal-networking: true

### ISSUE THREAD

**Issue by VincentGuyader** [openanalytics/shinyproxy#126]
Hi,

in the documentation the combo port-range-max + port-range-start seems to be the way to limite the number of containers. But it doesnt work with internal-networking: true

Can you please add this functionality ?

Regards

Regards

**Comment by shrektan** [comment]
Forgive my ignorance... But if use the internal network, why need to expose the port? I thought shinyproxy uses the container Id to communicate...

**Comment by VincentGuyader** [comment]
Hi,

In fact I need to limit the number of simultaneous number of user

Regards

**Comment by nperp** [comment]
IMHO this is a very useful functionality as there can be a resource issue...

**Comment by LEDfan** [comment]
Hi, a native feature to limit the amount of app instances has been implemented in ShinyProxy 3.1.0, which was released today. See https://shinyproxy.io/documentation/configuration/#max-total-instances .  Thanks again for your suggestion!

**Comment by VincentGuyader** [comment]
thanks !
