### ISSUE TITLE
iframe 50px too short when hide-navbar: true

### ISSUE THREAD

**Issue by jey1401** [openanalytics/shinyproxy#13]
Hi,

I noticed that the iframe is 50px too short when disabling the navbar with `hide-navbar: true` in the config file. Indeed, disabling the navbar does not disable the javascript `setShinyframeHeight()` function.

Cheers

PS: fix in pull request #17

**Comment by fmichielssen** [comment]
Hi jey, thanks for the fix pr!
However, this was a regression bug introduced by one of my earlier commits, and a fix is already forthcoming in the next push.
