### ISSUE TITLE
Ubuntu 18.04 Adding /etc/systemd/system/docker.service.d/override.conf causes docker commands to hang

### ISSUE THREAD

**Issue by tdekelver** [openanalytics/shinyproxy#132]
When adding the  `/etc/systemd/system/docker.service.d/override.conf` file all the docker commands freeze. Meaning, when I run `sudo docker --help` or any other docker comand (ps, version, images, ...) nothing happens. As soon as I remove the file everything works fine again. This is really annoying !!

**Comment by tverbeke** [comment]
Can you provide details on the Docker version and on the contents of the `override.conf`file?

This post may be relevant: https://support.openanalytics.eu/t/request-update-the-getting-started-guide/867

**Comment by tdekelver** [comment]
Docker version:

```
$ docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
and 
```
$ cat /etc/systemd/system/docker.service.d/override.conf
#[Service]
#ExecStart=
#ExecStart=/usr/bin/dockerd -D -H tcp://127.0.0.1:2375

```

**Comment by tdekelver** [comment]
Also I tried by changing `override.conf` like suggested in the link you provided: 
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D -H unix://127.0.0.1:2375
```
But the docker commands still hang...

**Comment by tverbeke** [comment]
That is not what was suggested. It should be

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H unix:// -D -H tcp://127.0.0.1:2375
```

Does that work for you?

**Comment by tdekelver** [comment]
Yes this works for me !! Thanks for the help.

**Comment by tverbeke** [comment]
Thanks for the confirmation - updated https://www.shinyproxy.io/getting-started/#docker-startup-options with this configuration.

**Comment by ckvtvm-arch** [comment]
> ExecStart=/usr/bin/dockerd -H unix:// -D -H tcp://127.0.0.1:2375

I tried all the below and none of them worked:

ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock

ExecStart=/usr/bin/docker daemon -H tcp://172.18.16.1:2375 

ExecStart=/usr/bin/dockerd -H fd:// --dns 8.8.8.8

ExecStart=/usr/bin/dockerd -H unix:// -D -H tcp://127.0.0.1:2375
