### ISSUE TITLE
Cannot access to SHINYPROXY_USERNAME env variable

### ISSUE THREAD

**Issue by DrumSergio** [openanalytics/shinyproxy#135]
This comes from here: https://github.com/rocker-org/shiny/issues/61

Just try this reproducible example:

```
docker pull acsdesk/shinyproxy-demo
docker pull acsdesk/example-username
docker network create shinyproxy-net
docker run -d -v /var/run/docker.sock:/var/run/docker.sock --net shinyproxy-net -p 8080:8080 acsdesk/shinyproxy-demo
```
The repo of all this: https://github.com/DrumSergio/shinyproxy-example
To access ShinyProxy: User "test" and password "test" in http://localhost:8080

This even comes from an earlier post here: https://support.openanalytics.eu/t/shinyproxy-username-in-shiny-user/1038 where I thought the problem was another one.

Thank you! Hope I provided all the info you need.

**Comment by tverbeke** [comment]
Hello @DrumSergio, You should not use a Shiny Server docker image, but a plain R docker image with the Shiny package installed as documented [here](https://www.shinyproxy.io/deploying-apps/#write-a-dockerfile). When doing so, it will work out of the box.

**Comment by DrumSergio** [comment]
Another reproducible example, that's why I finally decided in the first place using the shiny container of rocker, as yours I couldn't get it to work. But let's see:

```
docker pull acsdesk/shinyproxy-demo
docker pull acsdesk/euler-example
docker network create shinyproxy-net
docker run -d -v /var/run/docker.sock:/var/run/docker.sock --net shinyproxy-net -p 8080:8080 acsdesk/shinyproxy-demo
```

The same as before, the repo is at https://github.com/DrumSergio/shinyproxy-example
The dockerhub: https://hub.docker.com/u/acsdesk
To access ShinyProxy: User "test" and password "test" in http://localhost:8080 and click on the euler app.

The error: "Container did not respond in time"
It's just the example you posted on your webpage. What am I missing?

Thank you

**Comment by DrumSergio** [comment]
Hello again, @tverbeke 

I've been all morning long trying to decipher why is not working in my app, and it seems the problem was with the `Rprofile.site` file.

I modified the app for it to set the correct port and hosts, because the instruction `COPY Rprofile.site /usr/lib/R/etc/` doesn't work. 
I don't know why, that's something you will have to investigate, but the line that solves all is:

`CMD ["R", "-e", "shiny::runApp('/root/myapp', port = 3838, host = '0.0.0.0')"]`

Thank you
