### ISSUE TITLE
Google Chrome - Websockets Error - (Opcode -1)

### ISSUE THREAD

**Issue by cmattoon** [openanalytics/shinyproxy#14]
I'm running into an issue in Chrome where websockets are erroring out with "(Opcode -1)". This was originally with 0.9.2, but I just updated to 0.9.3 today and am still having the issue.

* It doesn't seem to be an application error (happens with both good/bad apps)
* No log entries
* Firewall rules allow all relevant ports in both directions

Opcode -1 [isn't a valid opcode](https://tools.ietf.org/html/rfc6455#section-11.8), which led me to Wireshark the connection. This confirmed that data was being sent [after the server sent a close](https://bugs.chromium.org/p/chromium/issues/detail?id=372776#c10) connection. 

The signal appears to be sent from [here](https://github.com/rstudio/shiny/blob/master/R/shiny.R#L1820), but I'm not that familiar with Shiny, and our R devs aren't aware of a reason for this. Firefox reports Firefox can’t establish a connection to the server at <url>`. I understand Shiny should fall back to Ajax, but it doesn't look like that's happening. 

![image](https://user-images.githubusercontent.com/3005498/28243035-50a9f618-698b-11e7-973f-9226a903aae1.png)

![image](https://user-images.githubusercontent.com/3005498/28243036-6bfe00c6-698b-11e7-993a-2c0ad540ef8e.png)

![image](https://user-images.githubusercontent.com/3005498/28243024-278e0026-698b-11e7-9a7d-2db80eaf3691.png)

I'm not positive this is a ShinyProxy problem, but I'm not really sure what's causing it at this point.

**Comment by fmichielssen** [comment]
Hi @cmattoon,

Thanks for the detailed description.
Did you always have this issue, or did it start happening at some version or update?

I cannot imagine what part of ShinyProxy could cause this issue. It uses Undertow as its underlying web server, and beyond setting up a ProxyHandler to the docker container, ShinyProxy does nothing to the proxied connection.

**Comment by cmattoon** [comment]
We've had the issue intermittently, and it seems that this is a generic manifestation of "something went wrong". Currently, everything is working as expected after updating apps and adjusting Netscaler/Haproxy settings, though this was happening with direct connections as well.

I'm going to mark this as closed; thanks for your help!

**Comment by markandsbhatt** [comment]
> ``
