### ISSUE TITLE
R Shiny 1.2.0 breaking change 

### ISSUE THREAD

**Issue by AartGoossens** [openanalytics/shinyproxy#142]
The latest version of R Shiny (1.2.0) is not compatible with the latest version of Shinyproxy (2.2.1), resulting in not loading static files for the frontend. From the browser console (among many similar messages):
```
The resource from “https://example.com/app_direct/app_name/shared/json2-min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```
R Shiny changelog:
https://shiny.rstudio.com/reference/shiny/1.2.0/upgrade.html

Downgrading shiny package to 1.1.0 fixes the issue.

**Comment by mnazarov** [comment]
Please see if this https://support.openanalytics.eu/t/css-not-loading-in-app/1104 (and links there) helps

**Comment by AartGoossens** [comment]
My apologies for replying so late but I was indeed able to fix it with your link (or more specifically: [this](https://stackoverflow.com/a/55602155) stackoverflow answer).
Thanks for your help!
