### ISSUE TITLE
app_direct requires unecessary forward slash in url

### ISSUE THREAD

**Issue by dylancis** [openanalytics/shinyproxy#145]
The `/app_direct/` url will only works if we use:
shinyproxyapp.com/app_direct/myappname/ while shinyproxyapp.com/app/myappname does not require this extra backslah. This is counter intuitive to have set one at the end for the /app_direct/ way.

This has been introduced in ShinyProxy 2.2.0 as earlier we could use `/app_direct/` the same way as `/app/` without the end slash after app name.

**Comment by tverbeke** [comment]
Hi @dylancis, Thanks for creating the issue. I agree we should fix this.

**Comment by dylancis** [comment]
@tverbeke  I believe the line in question is here:
https://github.com/openanalytics/shinyproxy/blob/7c5448223fcff55f29ad630f7ac36d380ff68597/src/main/java/eu/openanalytics/shinyproxy/controllers/AppController.java#L112

**Comment by tverbeke** [comment]
@dylancis Fixed in ShinyProxy 2.2.2!
