### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by trafficonese** [openanalytics/shinyproxy#146]
There are probably quite some improvements that can be made to the Readme and the Docs at https://www.shinyproxy.io/.

I only have 3 suggestions for now:

- The last bullet point of [Write a Dockerfile](https://www.shinyproxy.io/deploying-apps/) is missing the rest of the sentence. 

- The README says to install the package from source `mvn -U clean install` should be run, but I had to include your Nexus repo in our company Nexus as the `containerproxy.jar` was missing. Can be found [here](https://nexus.openanalytics.eu/nexus/content/repositories/releases/eu/openanalytics/containerproxy/0.8.1/).

- The [configuration per app](https://www.shinyproxy.io/configuration/#apps) says `For each app, four fields can be specified:`, but actually 6 bullet points are listed there which are followed by some "non-basic" configuration options.

**Comment by tverbeke** [comment]
Many thanks, @trafficonese!  I already fixed your first and last point. For the second one, it is probably best if we publish containerproxy to maven central
