### ISSUE TITLE
Memory limit when using docker-swarm as backend

### ISSUE THREAD

**Issue by wahani** [openanalytics/shinyproxy#151]
## Versions:

- shinyproxy: 2.2.2
- docker: 18.09.6

## Setup:

I followed the example setup of a shinyproxy server using docker-swarm as backend from https://github.com/openanalytics/shinyproxy-config-examples/tree/master/06-containerized-docker-swarm -- this example works great for me. 

## Problem

Now I would like to add resource constraints to the shiny apps. From the [documentation](https://www.shinyproxy.io/configuration/) I see that there are the fields `container-memory` and as of shinyproxy 2.2.2 also `container-memory-request`, `container-memory-limit`, `container-cpu-request and container-cpu-limit`. These options appear to be only working for docker and kubernetes as backend, and fail to have any impact when using docker-swarm. 

Given the [release notes](https://www.shinyproxy.io/downloads/) from version 2.2.2 I assume this is a missing feature and not a bug. Are there any plans to make these parameters available for the docker-swarm backend in the near future? Or is my configuration not working properly and they should work? Also the use of [constraints](https://success.docker.com/article/using-contraints-and-labels-to-control-the-placement-of-containers) together with swarm would be very helpful.

**Comment by tverbeke** [comment]
Hi @wahani Thanks for your question. It is indeed the case that we did not yet add support for this in the Docker Swarm back-end. No concrete plans or timing yet to do so, but it is 'conceptually speaking' on the roadmap.

**Comment by wahani** [comment]
Thanks for the quick response all your efforts. I will then wait and try Kubernetes in the meantime.

**Comment by LEDfan** [comment]
This is now supported in ShinyProxy 3.0.0, which was released today, see the docs: https://shinyproxy.io/documentation/configuration/#apps
