### ISSUE TITLE
How to specify 'simple' authentication in a separate file

### ISSUE THREAD

**Issue by mg515** [openanalytics/shinyproxy#153]
I'm running shinyproxy as a systemd service (installed through .deb). Is there any way to specify user and password information in a separate, hidden, and protected file. I tried to `chmod 700` the application.yml file also, but the shinyproxy service then couldn't access the file. What is the best practice here? I want to use simple authentication, but not leave passwords exposed.
 
Thanks!

**Comment by michaelhogersosis** [comment]
Hi @mg515 ,

Would the following topic on the openanalytics forum be of any help?

https://support.openanalytics.eu/t/environment-variables-inside-application-yml/787

Best regards,

Michael

**Comment by mg515** [comment]
It seems like a working solution, but overly complicated for a relatively simple problem. I will try it out however, if there isn't a better idea. How would I set permissions of the .yml file to protect it sufficiently and still be able to use it within shinyproxy?

**Comment by LEDfan** [comment]
Hi, in recent releases of ShinyProxy it's possible to specify additional config files to load. I just documented this here: https://shinyproxy.io/documentation/configuration/#config-import

I'll close this issue, but feel free to re-open or open a new issue if you still experience an issue.
