### ISSUE TITLE
When click Hello Application shows Launching Hello Application... no response

### ISSUE THREAD

**Issue by XiaoruiZhu** [openanalytics/shinyproxy#155]
### When click Hello Application shows Launching Hello Application... no response

![image](https://user-images.githubusercontent.com/5043485/58929225-0725c900-8724-11e9-8975-1c2a28e1f34a.png)

### After click the application, first of the direction is not correct, 

![image](https://user-images.githubusercontent.com/5043485/58929293-50761880-8724-11e9-9f12-d2db4894c7fe.png)

### I have to change it manually to: 

![image](https://user-images.githubusercontent.com/5043485/58929317-7d2a3000-8724-11e9-97f5-66aed4174c38.png)

**Comment by LEDfan** [comment]
Hi I think this is caused by a misconfiguration of the `server.servlet.context-path` of ShinyProxy.
However, since this is quite an old issue, I'm going to close it.
Of course, if you still experience the issue, feel free to re-open it.
