### ISSUE TITLE
shinyproxy.io Let's encrypt certificate exired

### ISSUE THREAD

**Issue by TFcfgo** [openanalytics/shinyproxy#156]
This causes an issue when downloading shinyproxy.jar on Linux

**Comment by tverbeke** [comment]
Thanks @TFcfgo We will fix asap. As a workaround you can download from Github e.g.
https://github.com/openanalytics/shinyproxy/releases/download/v2.2.2/shinyproxy-2.2.2.jar

**Comment by TFcfgo** [comment]
Thx for the quick reply! 
In the meantime, I found a solution using the option --no-check-certificate for wget

**Comment by tverbeke** [comment]
Fixed.
