### ISSUE TITLE
run shinyproxy on https?

### ISSUE THREAD

**Issue by DockerAsura** [openanalytics/shinyproxy#157]
Hello there,

am new to shinyproxy, I want run shinyproxy on HTTPS. am not able to understand the "https://www.shinyproxy.io/security/#https-ssl-tls", 
Q:- where do we need to copy the nginx config? If possible please share application.yml with HTTPS.

Thanks
Asura

**Comment by nali-raz** [comment]
Hi Asura, 
You can find a great example that worked for me here : 
https://github.com/TelethonKids/deploy_shiny_app

**Comment by LEDfan** [comment]
HI @DockerAsura 

You have to deploy nginx as a separate piece of software. Nginx will then ensure that the traffic is encrypted and forwards (proxies) it to ShinyProxy. See for example the link of @nali-raz or https://www.linode.com/docs/web-servers/nginx/use-nginx-reverse-proxy/

**Comment by LEDfan** [comment]
As I believe that your question is answered, I'm closing this issue. Feel free to re-open it if you need more help.
