### ISSUE TITLE
allow docker containers to named rather than the random docker way

### ISSUE THREAD

**Issue by wccropper** [openanalytics/shinyproxy#160]
I wonder if there is a way to have the container name specified via some variables. For my specific purposes I would for the name to contain the $SHINYPROXY_USERNAME_applicationname_someuniqid. I spend my time in the Linux CLI and seeing this info there would be faster to know who to contact when the shinyproxy service needs restarting.

**Comment by tverbeke** [comment]
Hi @wccropper, thank you for your question. Are you aware that an admin user can get an instant view of container id, user, app name, endpoint and uptime by clicking on the Admin button? I use this to check before restarting.

**Comment by wccropper** [comment]
Hi @tverbeke, yes I am aware that exists. As I said I spend my time at the terminal. I'm basically asking if something exists that I have not see yet. If nothing exists then this can be closed. But maybe it is something that could be added in the future.

**Comment by LEDfan** [comment]
Hi, this is now part of ShinyProxy 3.1.0, which we released today. Thanks again for your suggestion!
