### ISSUE TITLE
${title} thymeleaf expression is empty on login page

### ISSUE THREAD

**Issue by vpanfilov** [openanalytics/shinyproxy#161]
Checked on ShinyProxy 2.2.2

`${title}` expression is specified in login page template in file https://github.com/openanalytics/containerproxy/blob/master/src/main/resources/templates/login.html

```html
<title th:text="${title}"></title>
```

But page title is not populated from config:

```yml
proxy:
  title: Shiny Proxy
  ...
```

and is rendered as empty string:

```html
<title></title>
```

Proper access to config values is really needed for custom HTML templates.

**Comment by LEDfan** [comment]
Hi

This is now fixed in the 2.5.0 release. Thank you for your report.
