### ISSUE TITLE
Recive additional response from custom HTTP Auth Web server 

### ISSUE THREAD

**Issue by kuzmenkov111** [openanalytics/shinyproxy#162]
Hi there!
Many Thanks for Web server Auth feature. It is absolutely great!

But is it possible to add some function with the following workflow:

1) ShinyProxy sent the http request to Auth Web server ------>
2) Auth Web server answers 200 OK. Plus Web Server sends 
`shinyproxy_json_field {
some string…
} ` 
3) ShinyProxy authorizes user + receive `shinyproxy_json_field` and sends it into container as ENV SHINYPROXY_OPTIONS (just string env, and shiny app developers may use f.e. jsonlite R package to parse this ENV and use different arguments from this ENV).

I suppose this feature greatly improves functionality and interaction between Auth Web Server and Shiny app with small cost (just get custom json field and sent it into container ENV).

Thank you for your amazing solution!

**Comment by kuzmenkov111** [comment]
Hello!

Are there any plans or thoughts about this?

**Comment by LEDfan** [comment]
Hi, this is now part of ShinyProxy 3.1.0, which we released today. Thanks again for your suggestion!
