### ISSUE TITLE
Possible to change docker container user?

### ISSUE THREAD

**Issue by bwlewis** [openanalytics/shinyproxy#164]
I can't seem to figure out how to configure shinyproxy to run docker containers as non-root users (within the container). In other words, how to configure something like the docker command-line

```
docker container run  --user uid:gid ...
```
Is this possible?

**Comment by kuzmenkov111** [comment]
It is possible.
1. You need to create a user on the host with a specific id f.e. `useradd -u 555 dockerapp`
2. In DOCKERFILE you need to create a user with the same id and use USER instruction in the end:
`
FROM debian:stretch

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"
RUN useradd -u 555 dockerapp \
    && mkdir /home/dockerapp\
    && mkdir /home/dockerapp/app \
    && mkdir /home/dockerapp/data \
    && chown -R dockerapp:dockerapp /home/dockerapp  \
    && addgroup dockerapp staff

# Some instruction


VOLUME /home/dockerapp/data
VOLUME /home/dockerapp/app

EXPOSE 3838

USER dockerapp

CMD ["R", "-e shiny::runApp('/home/dockerapp/app',port=3838,host='0.0.0.0')"]

`

**Comment by bwlewis** [comment]
Thanks, perfect!

And also, thanks for this superb tool.
