### ISSUE TITLE
[Improvement][Security] ability to disable java stacktrace incase container failed to start

### ISSUE THREAD

**Issue by dischello** [openanalytics/shinyproxy#167]
It would be nice to hide stacktrace from enduser incase shiny container failed to start.

**Comment by michaelhogersosis** [comment]
It would be nice if we could put an error.html file in a template-path folder, that way we can decide to hide the stack trace and create custom error pages

**Comment by tverbeke** [comment]
Good suggestion, @dischello and @michaelhogersosis  - we will work on it.
