### ISSUE TITLE
Error  Status code: 500  Message: Failed to start container 

### ISSUE THREAD

**Issue by kochkina** [openanalytics/shinyproxy#172]
Hello. I have a problem when I'm trying to start ShinyProxy with Dash. 
I tried this docker image  https://github.com/openanalytics/shinyproxy-dash-demo. Unfortunately there are any examples of application.yml with this container image. I'm novice and it's my first attempt to create dash report in conjuction with Shinyproxy. Could you help me please to figure out where I'm making a mistake

proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
    internal-networking: true
  specs:
  - id: dash-demo
    display-name: Dash Demo Application
    description: Simple random scatterplot
    container-cmd:  ["python", "/app/app.py"]
    container-image: shinyproxy-dash-demo

logging:
  file:
    shinyproxy.log

**Comment by tverbeke** [comment]
@kochkina: You need a custom port `port: 8050` as part of the spec of your app.
