### ISSUE TITLE
Starting Docker Container Using Variables in Volume Mounting

### ISSUE THREAD

**Issue by keqiang** [openanalytics/shinyproxy#18]
Currently, in the application.yml, we can specify paths that to be mounted to run the container for each Shiny app. @fmichielssen mentioned on shinyproxy.io that we can specify environment variables such as $HOME in the path by `docker-volumes: [ "${HOME}/path1:/container/path1" ]`, but as he pointed out, 

> they refer to the ShinyProxy’s process daemon, not the ShinyProxy logged-in user

this way doesn't really make the program dynamic. 

So he suggested making variables like SHINYPROXY_USERNAME available in the context, 

> docker-volumes: [ "/host/mnt/${SHINYPROXY_USERNAME}/path1:/container/path1" ]

this would be very helpful for a lot of use-cases regarding user files.

If this is something you guys think is useful, I can investigate into it and try implementing it.

Another issue is in our Docker container, the Shiny Server is run under user 'shiny', and the volume mounted in could be owned by any logged in user(on the host), therefore, the Shiny app in the docker container does not have the right permission to access these files. I guess this is not really a shinyproxy issue, rather a volume related issue of Docker.

Thanks.

**Comment by tverbeke** [comment]
Hi Keqiang,

Good idea if you ask me!

Could be useful, maybe to indicate the scope using a prefix as in 
```
${shinyproxy: SHINYPROXY_USERNAME}
```
to differentiate between environment variables as known to the Docker host vs. variables related to ShinyProxy properly speaking (?)

Best,
Tobias

**Comment by keqiang** [comment]
Hi @tverbeke 

I guess since the name is already prefixed by "SHINYPROXY_", it should be fine. It's just misleading because we are using the environment variable syntax to evaluate these variables. Maybe we should figure out a different syntax to refer specifically to these per-user variables such as for each app's configuration, use an option 'make-available: SHINYPROXY_USERNAME, SHINYPROXY_LDAP_CN' and then in other parts of this app's configuration, we can directly refer to these variables using another syntax rather than '${}'

**Comment by fmichielssen** [comment]
Hi @keqiang,

A mechanism to choose which variables are exposed, sounds very good to me. And you are right that SHINYPROXY_ is already a prefix by itself.
Regarding the syntax, I believe it would be fine to use ${}, as this may already refer to more than just environment variables. The full list is given here:
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
And I think what we would be doing, is just adding one item to the list, the so-called 'shinyproxy user variables'.

Regards,

**Comment by tverbeke** [comment]
The application.yml file supports SpEL (Spring expression language) since ShinyProxy 2.0.4. This allows to mount user-specific volunes for Shiny apps. Small example:

```
    container-volumes: [ "/home/#{proxy.userId}/app/storage:/app/storage" ]
```
