### ISSUE TITLE
Renaming the JSESSIONID cookie

### ISSUE THREAD

**Issue by k----n** [openanalytics/shinyproxy#181]
Is it possible to rename the JSESSIONID cookie?

~~Is it possible to connect to a proxy instance's websocket without setting the JSESSIONID Cookie in the browser?~~

~~Ideally, I would like to proxy all connections through a server without the end user knowing the JSESSIONID, but I cannot get websockets to load without setting the JSESSIONID Cookie in the browser.~~

Edit: I guess there needs to be some way to verify the user. So the question has been changed.

**Comment by LEDfan** [comment]
Hi

You should be able to change the cookie name using the following code in `application.yml`:

``
server:
    servlet:
      session:
          cookie:
               name: MYSESSIONID
```
