### ISSUE TITLE
User can't belong to multiple groups???

### ISSUE THREAD

**Issue by nali-raz** [openanalytics/shinyproxy#186]
Hi, 

I'm trying to use an `application.yml` file where a user may belong to multiple groups,
but right after login, no app is listed for the user. 

```
- name: user1
    password: xx
    groups: [a, b, c]
- name: user2
    password: yy
    groups: [admins, e]
```
Is it possible?

Thank you, 

Naly

**Comment by mnazarov** [comment]
Yes, it is possible, with the following syntax:
```
- name: user1
    password: xx
    groups: a, b, c
- name: user2
    password: yy
    groups: admins, e
```
