### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by iptizer** [openanalytics/shinyproxy#188]
I am a huge fan of both, ShinyProxy/ContainerProxy and OpenSource. This is why it get's me sad seeing all this people opening PRs, willing to contribute... but don't get a response from the maintainers. Some even for over a year now.

This is why I'm raising the question in the direction of the maintainers, whether there will be an effort on continuing this project?

And don't understand be incorrectly here, I don't want to put pressure on you. I know this is OpenSource and no one is paying you a cent. But maybe we can find a way of continuing the project? I.e. by allowing others to be contributor or accepting the unpaid time to continue on this, before people consider a fork, which would help no one.

**Comment by tverbeke** [comment]
The project is still alive and a release is pending.

**Comment by tverbeke** [comment]
2.3.1 has been released now - more to come!
