### ISSUE TITLE
SAML - service provider metadata download feature

### ISSUE THREAD

**Issue by mskyttner** [openanalytics/shinyproxy#190]
For setting up the Identity Provider side when using SAML authentication, it would be convenient to be able to download the generated metadata from the shinyproxy (service provider) side. 

If that feature is not available, I guess one has to resort to using a tool such as this one to "recreate" the metadata used in shinyproxy for SAML auth when setting up the IdP-metadata: https://www.samltool.com/sp_metadata.php

See some more details on this feature request here: https://github.com/openanalytics/containerproxy/issues/30

**Comment by LEDfan** [comment]
Hi @jat255 

We released ShinyProxy 2.5.0 in which the SAML metadata is now exposed on the `/saml/metadata` path, e.g.: `localhost:8080/saml/metadata`.

Since this is fixed now, I'm closing this issue. As always, feel free to open a new issue if you encounter any problem.
