### ISSUE TITLE
Docker secrets with shinyproxy in a docker swarm setup? 

### ISSUE THREAD

**Issue by evesch** [openanalytics/shinyproxy#191]
Hello,

Are there any plans to make docker secrets available in a container with shinyproxy in a docker swarm setup?  More specific: assuming that the secret(s) have already been created in the swarm, a way to configure in application.yml that the secrets can be read in /run/secrets/... in the container. (https://docs.docker.com/engine/swarm/secrets/)

Thanks a lot in advance!

Kind regards,

Eric

**Comment by vpanfilov** [comment]
@evesch I managed to get it working with modifying **CMD** command in Shiny Proxy Dockerfile like this:
```docker
# https://medium.com/@sedkyaboushamalah_78619/docker-secrets-multiple-environments-and-java-spring-boot-ea6c6c92c0ea
CMD java -jar \
    -Dproxy.ldap.manager-password="$(cat /run/secrets/ldap-password)" \
    /opt/shinyproxy/shinyproxy.jar
```
And property `proxy.ldap.manager-password` should not be present in _application.yml_ file

**Comment by evesch** [comment]
Thanks!

**Comment by jtelleriar** [comment]
@vpanfilov Have you managed to make it work something like this?:

```
container-env:
  VAR1: "${cat run/secrets/my-secret}"
```

I want to pass the secret to the Docker images triggered by ShinyProxy, but I am not able to achieve it.
