### ISSUE TITLE
I can't edit navbar.html file when shinyproxy is in container

### ISSUE THREAD

**Issue by PauloJhonny** [openanalytics/shinyproxy#196]
Hello!

I can't edit navbar.html when ShinyProxy is running as docker container. I tried to put the edited navbar.html in the templates/fragments directory and then copy to /opt/shinyproxy/templates, but still the changes don't show up when I restart the server.

For example, I would like to change "Sign Out" for "Sair".

![image](https://user-images.githubusercontent.com/14023635/77074104-12a26200-69cf-11ea-9756-536c11923ab9.png)

----------------------------------------------------------------------------------------------------------------------------------

**Dockerfile:**

FROM openjdk:8-jre

RUN mkdir -p /opt/shinyproxy/
RUN wget https://www.shinyproxy.io/downloads/shinyproxy-2.3.0.jar -O /opt/shinyproxy/shinyproxy.jar
COPY application.yml /opt/shinyproxy/application.yml
RUN mkdir templates
COPY templates/* /opt/shinyproxy/templates/
RUN mkdir templates/fragments
COPY templates/fragments/* /opt/shinyproxy/templates/fragments/

WORKDIR /opt/shinyproxy/
CMD ["java", "-jar", "/opt/shinyproxy/shinyproxy.jar"]

----------------------------------------------------------------------------------------------------------------------------------

**application.yml:**

proxy:
  title: LicitaR
  landing-page: /
template-path: ./templates
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
      container-network: dnv-net
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: "${proxy.docker.container-network}"
  - id: euler
    display-name: Euler's number
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: euler-docker
    container-network: "${proxy.docker.container-network}"

logging:
  file:
    /log/shinyproxy.log

----------------------------------------------------------------------------------------------------------------------------------

I don't know if i'm doing something wrong. Could you help me, please? Thank you.

Paulo

**Comment by shrektan** [comment]
You should recreate your image. 

BTW, you should not copy the files. Instead, you should make the folder as a volume. In this way, after changing the file, you only need to refresh the browser.

**Comment by PauloJhonny** [comment]
@shrektan thank you for your reply. 

1. After the changes I recreated the image using `sudo docker-compose build`, but nothing changed. Is it right?

2. About the folder as a volume, could you show me an example? I'm new user of ShinyProxy, so I'm a little bit lost. 

Thank you.

**Comment by shrektan** [comment]
Sorry, I don't have time to do this right now but I screenshot a production setup for you. It should be easy to understand.


### The docker file

<img width="634" alt="image" src="https://user-images.githubusercontent.com/8368933/77081954-5bd9cc80-6a36-11ea-9664-5603f4a6026b.png">


### Docker compose YAML

<img width="502" alt="image" src="https://user-images.githubusercontent.com/8368933/77081813-29c86a80-6a36-11ea-8234-870221569e5f.png">

### Folder structure

<img width="562" alt="image" src="https://user-images.githubusercontent.com/8368933/77081863-3f3d9480-6a36-11ea-8ed9-97fc5d3dd821.png">

**Comment by PauloJhonny** [comment]
@shrektan Thank you so much for your help.

1) I created the 'volumes' in the docker-compose.yml and changed the Dockerfile as you said. The files (admin, app, index, login) are used when the page is refreshed (thanks to you). But, the shinyproxy/application.yml are not used, even though I put `sudo docker-compose build` and the command `sudo docker-compose up -d shinyproxy` says "dnv_shinyproxy is up-to-date". So I left one CP in the Dockerfile regarding the application.yml. :( 

---------------------------------------------------------------------------------

**docker-compose.yml**

version: "3.6"
services:
  shinyproxy:
    image: datanovia/shinyproxy
    container_name: dnv_shinyproxy
    restart: on-failure
    build: ./shinyproxy
    networks:
      - dnv-net
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./shinyproxy-logs/server:/log"
      - "./shinyproxy-logs/container:/container-logs"
      - "./shinyproxy/application.yml:/opt/shinyproxy/application.yml"
      - "./shinyproxy/templates/:/opt/shinyproxy/templates"
      - "./shinyproxy/templates/fragments/navbar.html:/opt/shinyproxy/templates/fragments/navbar.html"
  euler:
    image: euler-docker
    container_name: dnv_euler
    build: ./shinyapps/euler-docker
    networks:
      - dnv-net

networks:
  dnv-net:
    name: dnv-net

---------------------------------------------------------------------------------

**Dockerfile**

FROM openjdk:8-jre

RUN mkdir -p /opt/shinyproxy/
RUN wget https://www.shinyproxy.io/downloads/shinyproxy-2.3.0.jar -O /opt/shinyproxy/shinyproxy.jar
COPY application.yml /opt/shinyproxy/application.yml

WORKDIR /opt/shinyproxy/
CMD ["java", "-jar", "/opt/shinyproxy/shinyproxy.jar"]

---------------------------------------------------------------------------------

application.yml

proxy:
  title: LicitaR
  landing-page: /
  hide-navbar: false
  template-path: ./templates/
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: pass
    groups: admins
  - name: jeff
    password: pass
  docker:
      internal-networking: true
      container-network: dnv-net
      work-directory: /home/paulo/shinyproxy-config/
  specs:
  - id: 01_hello
    display-name: Hello Simple APP <3
    description: Application Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: "${proxy.docker.container-network}"    
  - id: euler
    display-name: Euler's number
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: euler-docker
    container-network: "${proxy.docker.container-network}"

logging:
  file:
    /log/shinyproxy.log

---------------------------------------------------------------------------------

2) I still can't change the navbar.html file. When I put `template-path: ./templates/fragments` It was possible, but this way the others files that I changed were not used (admin, app, index, login).

**Comment by shrektan** [comment]
@PauloJhonny 

You can put the fragments inside of templates but you need to claim that in `index.html` or somewhere first (sorry, I don't remember the clear place).

If you don't know what you are doing, you need to place the fragments under `shinyproxy/`. The reason is you need to keep the same folder structure as shinyproxy it does unless you know how it works. See the default folder structure here: https://github.com/openanalytics/shinyproxy/tree/master/src/main/resources 


Well, I actually build a docker-compose example for you. See https://github.com/shrektan/shinyproxy-docker-compose-example. Hope this clarifies your confusion.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/8368933/77168219-68235f80-6af2-11ea-9875-165cf2aa9dec.png">

**Comment by PauloJhonny** [comment]
@shrektan thank you so much. It really helped me.

It worked. I was putting the fragments folder in the wrong place (see the correct tree). All the files are hot-loaded now, except the application.yml. Thank youuu. 

![image](https://user-images.githubusercontent.com/14023635/77179739-a34c7100-6aa7-11ea-95ee-969f35526e68.png)

**Comment by shrektan** [comment]
Good to hear that. 

BTW, closing the issue will be good if you don't have further questions.

Thanks.

**Comment by PauloJhonny** [comment]
Thank you. :)
