### ISSUE TITLE
Group based authentication not working - ShinyProxy + Auth0 Okta authentication

### ISSUE THREAD

**Issue by advanalyticsamateur** [openanalytics/shinyproxy#198]
I am working on shinyproxy with Okta authentication.
Application.yml:
proxy:
  port: 8080
  authentication: openid
  admin-groups: Shinyapp_Readsensitive_pprd
  openid:
    auth-url: ***
    token-url: ***
    jwks-url: ***
    client-id: ***
    client-secret: ***
    roles-claim: ***
    scopes: ["openid","profile"]
    username-attribute: name
    logout-url: ***
  docker:
    url: http://localhost:2375
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-snapshot
    access-groups: [Shinyapp_Readonly_pprd, Shinyapp_Readsensitive_pprd]
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo

logging:
  file:
    shinyproxy.log
  level:
    root: DEBUG
server:
  useForwardHeaders: true

Log Debug:
2020-04-06 14:11:54.152 DEBUG 77224 --- [ XNIO-2 task-14] .s.o.c.w.OAuth2LoginAuthenticationFilter : Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken@af142e83: Principal: Name: [***], Granted Authorities: [ROLE_USER], User Attributes: [at_hash=**, sub=***, ver=1, amr=["pwd"], shinyproxy_roles=["Shinyapp_Readsensitive_pprd"], iss=https://***, preferred_username=***, aud=[***], idp=***, auth_time=1586146312, name=***, exp=Mon Apr 06 15:11:54 AEST 2020, iat=Mon Apr 06 14:11:54 AEST 2020, email=***, jti=***]; Credentials: [PROTECTED]; Authenticated: true; Details: null; Not granted any authorities
2

----------------
After clicking on the url we can authenticate the user with Okta but not able to authorise user groups.
The apps which has access-groups attributes set are not visible on the dashboard.
Can anyone help with role based authentication for apps?
Thanks!

**Comment by PauloJhonny** [comment]
Hi, @advanalyticsamateur. Did you manage to solve this problem? Thank you.

**Comment by advanalyticsamateur** [comment]
Yes it is resolved now. Thanks

**Comment by advanalyticsamateur** [comment]
Hi @butulia 

The roles-claim mentioned was the url and it should be just the name of the claim mentioned in Okta. This was the issue for me.

**Comment by LEDfan** [comment]
Hi @advanalyticsamateur 

Since this seems to be fixed now, I'm closing this issue. As always, feel free to open a new issue if you encounter any problem.

**Comment by erossini-chi** [comment]
> Hi @advanalyticsamateur, I have the same problem. I authenticate against an Identity Server 4. In the shiny proxy log I see how it receives the expected claim with the group membership info, but then it doesn't work. How did you solve the problem? Thanks

How did you resolve the problem? I still have the same issue also with the new version 2.6.1
