### ISSUE TITLE
Multiple apps open at the same time

### ISSUE THREAD

**Issue by samssann** [openanalytics/shinyproxy#2]
Could it be possible to open multiple apps at the same time? e.g. in your shinyproxy-demo - open 01_hello on one browser tab and 06_tabsets on another? Love your work!

**Comment by tverbeke** [comment]
Hi @samssann Currently not possible indeed (proxying is user-specific), but we'll investigate - thanks!

**Comment by aranm** [comment]
Does this mean that shinyproxy can only generate one visual at a time? We were thinking of using it as a back end service where we would put it in an iFrame on our web site and generate multiple visuals for different clients at the same time. Is this not going to be possible?

**Comment by tverbeke** [comment]
@samssann @aranm opening multiple apps at the same time is now possible and released in version 0.7.0. Thanks again for the feedback!

**Comment by rtanalytics** [comment]
Hi there,
Thanks for your great work. Does it also means version 0.7.0 supports multi concurrency?

**Comment by tverbeke** [comment]
@rtanalytics whenever someone uses an app, a container is used for that, so if your machine can handle 100 Docker containers, there can be 100 concurrent users of a single app; if you use Docker swarm, you can easily scale up usage of ShinyProxy beyond the capacities of a single machine and serve as many users as you want.

**Comment by tverbeke** [comment]
@aranm release 0.7.5 solved integration of ShinyProxy with a CMS - probably also useful for your setup.

**Comment by hcountou** [comment]
Hi,

"ShinyProxy with a CMS"...maybee you have more informations about that. Or an example of setup.

Thanks.
