### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by Nybre** [openanalytics/shinyproxy#200]
Hi,

The link https://www.shinyproxy.io/ is not going through

Thanks
Brian

**Comment by christiaanpauw** [comment]
It looks like the security certificate expired 12 days ago?

> On 17 Apr 2020, at 22:19, Nybre <notifications@github.com> wrote:
> 
> 
> Hi,
> 
> The link https://www.shinyproxy.io/ is not going through
> 
> Thanks
> Brian
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Christiaan Pauw
Tel: 044 6950 749
Cell: 082 557 4328
www.nova.org.za
www.aartum.io

**Comment by mskyttner** [comment]
For me this now works, but it seems the support forum is down? https://support.openanalytics.eu/ does not respond for me. I get a redirect 301 to https://support.openanalytics.eu but then a 504 gateway timeout so maybe cert issue there too?

**Comment by tverbeke** [comment]
Thanks for reporting. Site is down indeed. Will be solved shortly.
