### ISSUE TITLE
Failed to start container

### ISSUE THREAD

**Issue by robertoromor** [openanalytics/shinyproxy#202]
Hi Team, 

I am getting the following error when I deploy my app using docker and shinyproxy

> Error
> Status code: 500
> 
> Message: Failed to start container
> 
> Stack Trace:
> eu.openanalytics.containerproxy.ContainerProxyException: Failed to start container
> at eu.openanalytics.containerproxy.backend.AbstractContainerBackend.startProxy(AbstractContainerBackend.java:113)
> at eu.openanalytics.containerproxy.service.ProxyService.startProxy(ProxyService.java:213)
> at eu.openanalytics.shinyproxy.controllers.AppController.getOrStart(AppController.java:109)
> at eu.openanalytics.shinyproxy.controllers.AppController.startApp(AppController.java:68)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> .
> .
> .

> at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
> at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
> at java.base/java.net.Socket.connect(Socket.java:609)
> at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
> at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
> ... 30 more

I already went thru the troublesshoting options here 

https://www.shinyproxy.io/troubleshooting/

and my app works fine when I run it manually the manual deploy command 

`sudo docker run -p 9996:9996 radioimagen5 R -e 'options("shiny.port"=9996,shiny.host="0.0.0.0");rappExt::run_app()'`

this is what I have in my application.yaml:

> proxy:
>   hide-navbar: false
>   support:
>     mail-to-address: roberto.romo.r@gmail.com
>   title: Radioimagen Web App
>   logo-url:
>   port: 9996
>   template-path: ./templates/1col
>   authentication: none
>   container-wait-time: 90000
>   heartbeat-rate: 10000
>   heartbeat-timeout: 20000
>   landing-page: /app/radioimagen5/
>   container-log-path: ./container-logs
>   
>   users:
>   - name: robertoromo
>     password: pass
>     groups: all
>     
>   docker:
>     cert-path: /home/none
>     url: http://localhost:2375
>     port-range-start: 20000
> 
>     
>   specs:
>   - id: radioimagen5
>     display-name: Radioimagen Web App
>     description: Application which demonstrates the basics of a Shiny app
>     container-cmd: ["R", "-e","options('shiny.port'=9996,shiny.host='0.0.0.0');rappExt::run_app()"]
>     container-image: radioimagen5
>     port: 9996
> 
> logging:
>   file:
>     shinyproxy.log
>

**Comment by p-flock** [comment]
Hi, Just wanted to say I am experiencing the same issue. 
I am running CentOS 8 and experience this issue trying to add my own R shiny app with, as far as I can tell, very similar configuration. Curious to see the feedback to this issue.

**Comment by mnazarov** [comment]
Did you try the suggestions here regarding firewall: https://www.shinyproxy.io/troubleshooting/#failed-to-start-container ?
Did you modify [docker startup options](https://www.shinyproxy.io/getting-started/#docker-startup-options)?
Are there any error messages in the full log (you pasted only truncated part)?
Does it work with default `application.yml` and demo apps from shinyproxy-demo image?

**Comment by robertoromor** [comment]
Did you try the suggestions here regarding firewall: https://www.shinyproxy.io/troubleshooting/#failed-to-start-container ?
**disabled firewall and retried same result :Failed to start container**
Did you modify docker startup options?
**No, but just did it and got "Message: Container did not respond in time" message **
Are there any error messages in the full log (you pasted only truncated part)?
**Just this one**
`2020-05-08 18:26:41.986  INFO 28149 --- [XNIO-2 task-3] c.s.docker.client.DefaultDockerClient    : Starting container with Id: fa9136a7b214eb69de76d210a414b4481cf33c6c671e44eb1e0a8c324375fc26
2020-05-08 18:26:44.686  WARN 28149 --- [XNIO-2 task-3] e.o.shinyproxy.ShinyProxyTestStrategy    : Container unresponsive, trying again (2/45): http://localhost:20000
2020-05-08 18:28:13.840 ERROR 28149 --- [XNIO-2 task-3] io.undertow.request                      : UT005023: Exception handling request to /app/radioimagen5/
`
Does it work with default application.yml and demo apps from shinyproxy-demo image?
* Yes, I already got a couple of apps deployed and working**

**Comment by dennisvanderpool** [comment]
My brother has the same issue. Works on my system, not on his system.
Both are running the same docker version, shineyproxy and application.yml
I'm running on Ubuntu 20.04 LTS, he is running 18.04 LTS.
When doing the exact thing i noticed that the proxy could not be created on his system, no other TCP ports using 80, 443, 8080 are open prior to it.

When i compare both logs i saw that the proxy did got created on my system, but not on his, see screenshot and our log files.
![Screenshot at 2020-06-30 22-55-51](https://user-images.githubusercontent.com/24899089/86176638-86ebb600-bb25-11ea-91e3-a2e1fa440e15.png)
[shinyproxy_dennis.log](https://github.com/openanalytics/shinyproxy/files/4854404/shinyproxy_dennis.log)
[shinyproxy_richard.log](https://github.com/openanalytics/shinyproxy/files/4854405/shinyproxy_richard.log)

Going to look into the sourcecode now to see what might it to fail creation of the proxy or does somebody have an idea already? :smiley:

**Comment by dennisvanderpool** [comment]
Just doing an upgrade to Ubuntu 20.04 LTS solved his issue... I hope it helps somebody :sunglasses:

**Comment by dennisvanderpool** [comment]
Sorry, talked too soon. After upgrading to Ubuntu 20.04 LTS it only ran once. Weird.

**Comment by ElCrypo** [comment]
It turns out when I run keycloak on docker this issue occurs. When I kill keycloak container and set the authentication to simple, everything works fine. But launching keycloak in a docker container, even when authentication is still set to simple, after starting the container, the error 500 is back. For the record, the error is NOT Message: Failed to start container, but Message: Container did not respond in time.

**Comment by Dusan-Dingarac** [comment]
Hi Richard,
Is seems to me that both Keycloak and Shinyproxy are working on same port (default 8080). If this is the case run Keycloak from docker with eg. -p 8082:8080 and fchange port on other needed places (eg. reverse proxy...).

**Comment by dennisvanderpool** [comment]
Hey, i got it resolved. It seems that even though the exposed ports were different, it still had issues with running two proxies both on port 8080. Got it working by created a new network with "docker network create keycloak" and use --network=keyclock on the docker run command. Now works fine without any issues. :smiley:

**Comment by LEDfan** [comment]
Hi everyone

As I believe this question is answered, I'm closing this issue. Feel free to re-open it if you need more help. (Please open a new issue if it's unrelated to this one)
