### ISSUE TITLE
ShinyProxy redirect to login page

### ISSUE THREAD

**Issue by jakubkuzilek** [openanalytics/shinyproxy#205]
Hi, I am struggling with the login redirect when accessing the apps in ShinyProxy. Our institution use reverse proxy and redirects external addresses to internal ones. When someone tries to access the app, reverse proxy redirects correctly to the internal application and then shinyproxy creates redirect to the internal address and this causes problem, because this redirect does not work. Is there any way to specify redirect address for the login page?

More details:
Reverse proxy rules

RewriteRule             ^(/blabla/shiny)$ $`'1/

RewriteRule             ^/blabla/shiny(/.*)?$ http://xyz-123.karel.com:8888$`'1 [P,L]

Then when I call http://example.com/blabla/shiny/ it will get redirected to http://xyz-123.karel.com:8888 and ShinyProxy redirects to http://xyz-123.karel.com:8888/login and gets blocked. I would like to have redirect to http://example.com/blabla/shiny/login is this possible to configure?

**Comment by gybeata** [comment]
Hi Jakub, just wondering if you have found a solution to deploy shinyproxy ? I believe we are in a similar situation as the one you describe above.

**Comment by jakubkuzilek** [comment]
> Hi Jakub, just wondering if you have found a solution to deploy shinyproxy ? I believe we are in a similar situation as the one you describe above.

Hi @gybeata,

unfortunately not. I am also facing the problem, that I no longer have the access to the infrastructure. 😄

**Comment by LEDfan** [comment]
I'm not sure how to achieve this with rewrite rules, but I think it would be better to use Apache as reverse proxy instead.
We are using ShinyProxy together with a reverse proxy in many deployments without any issue.
Using the `ProxyPass` directive, ShinyProxy will get the correct Host header and the redirects should fully work.

**Comment by LEDfan** [comment]
Hi 

We now have documentation on how to use Apache as a reverse proxy for ShinyProxy: https://shinyproxy.io/documentation/security/#https-ssl--tls

This should solve your issue. If you need more help, feel free to re-open or open a new issue.
