### ISSUE TITLE
Shinyproxy application context-path is not working in Kubernetes container

### ISSUE THREAD

**Issue by cnukwas** [openanalytics/shinyproxy#208]
Hi,

As per documentation at [configuration](https://www.shinyproxy.io/configuration/) and other examples, we have configured following context-path in application yaml file but the container is failing to start with below error. 

`server:
  servlet:
    context-path: /shinyapp` 

I have checked SessionHelper [source ](https://github.com/openanalytics/containerproxy/blob/master/src/main/java/eu/openanalytics/containerproxy/util/SessionHelper.java)code at and it's using correct path as well.

Error message:
`Failed to bind properties under 'server.servlet' to org.springframework.boot.autoconfigure.web.ServerProperties$Servlet:

    Property: server.servlet
    Value: context-path: /shinyapp
    Origin: URL [file:./application.yml]:32:5
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.boot.autoconfigure.web.ServerProperties$Servlet] `

Any clues on this issue as we're using latest 2.2.x version?

Thanks

**Comment by LEDfan** [comment]
Hi

Maybe it's due to a formatting error, but it is important that there are some newlines between the properties. That is the configuration should look like this in the application.yaml file:

```
server:
  servlet:
    context-path: /abcd
proxy:
  title: Open Analytics Shiny Proxy
  ...

``

**Comment by cnukwas** [comment]
Yes, it was a formatting issue, worked fine later.
