### ISSUE TITLE
Login - Forget Password / Attempts errors

### ISSUE THREAD

**Issue by kaleming** [openanalytics/shinyproxy#209]
Does shinyproxy provide some security features like:

- block user account after many attempts using a wrong password ?
- Is it possible to have a forgot password button as well ?

Thank you

**Comment by Dusan-Dingarac** [comment]
Consider using Keycloak.

**Comment by tverbeke** [comment]
@kaleming Indeed as @Dusan-Dingarac mentions, ShinyProxy typically interfaces with external user management solutions and these offer the desired functionality. See https://www.shinyproxy.io/configuration/#authentication for an overview of all options. I agree that [Keycloak](https://www.keycloak.org/) is a very good option.

**Comment by kaleming** [comment]
Thank you @Dusan-Dingarac and @tverbeke.
