### ISSUE TITLE
ShinyProxy 2.3.1 sha256 check is failing

### ISSUE THREAD

**Issue by aiham** [openanalytics/shinyproxy#212]
The provided sha256 file for 2.3.1 seems to be incorrect. The result of `sha256sum shinyproxy-2.3.1.jar` does not match the contents of `shinyproxy-2.3.1.jar.sha256` so the check is failing. This works fine for `shinyproxy-2.3.0.jar`. The format of the sha256 file also changed from 2.3.0 to 2.3.1 (missing the filename, no longer ends in a new line).

```
[14:38:12][~/apps/shinyproxy]$ ls -al
total 8
drwxr-xr-x 2 aiham aiham 4096 Jun 27 14:38 .
drwxr-xr-x 3 aiham aiham 4096 Jun 27 11:51 ..
[14:38:17][~/apps/shinyproxy]$ curl -LO https://shinyproxy.io/downloads/shinyproxy-2.3.0.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.7M  100 76.7M    0     0   517k      0  0:02:31  0:02:31 --:--:-- 3579k
[14:40:55][~/apps/shinyproxy]$ curl -LO https://shinyproxy.io/downloads/shinyproxy-2.3.0.jar.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    87  100    87    0     0    587      0 --:--:-- --:--:-- --:--:--   587
[14:41:55][~/apps/shinyproxy]$ curl -LO https://shinyproxy.io/downloads/shinyproxy-2.3.1.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.7M  100 76.7M    0     0  4314k      0  0:00:18  0:00:18 --:--:-- 2062k
[14:42:18][~/apps/shinyproxy]$ curl -LO https://shinyproxy.io/downloads/shinyproxy-2.3.1.jar.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0    432      0 --:--:-- --:--:-- --:--:--   432
[14:42:22][~/apps/shinyproxy]$ ls -al
total 157268
drwxr-xr-x 2 aiham aiham     4096 Jun 27 14:42 .
drwxr-xr-x 3 aiham aiham     4096 Jun 27 11:51 ..
-rw-r--r-- 1 aiham aiham 80508913 Jun 27 14:40 shinyproxy-2.3.0.jar
-rw-r--r-- 1 aiham aiham       87 Jun 27 14:41 shinyproxy-2.3.0.jar.sha256
-rw-r--r-- 1 aiham aiham 80514490 Jun 27 14:42 shinyproxy-2.3.1.jar
-rw-r--r-- 1 aiham aiham       64 Jun 27 14:42 shinyproxy-2.3.1.jar.sha256
[14:42:24][~/apps/shinyproxy]$ sha256sum --check shinyproxy-2.3.0.jar.sha256
shinyproxy-2.3.0.jar: OK
[14:42:42][~/apps/shinyproxy]$ sha256sum --check shinyproxy-2.3.1.jar.sha256
sha256sum: shinyproxy-2.3.1.jar.sha256: no properly formatted SHA256 checksum lines found
[14:42:46][~/apps/shinyproxy]$ sha256sum shinyproxy-2.3.0.jar
7853f05cf4ed3b5f8ce3ab25509829e6ec997a038fc0b73f01ab72aabbaeeb75  shinyproxy-2.3.0.jar
[14:43:00][~/apps/shinyproxy]$ cat shinyproxy-2.3.0.jar.sha256
7853f05cf4ed3b5f8ce3ab25509829e6ec997a038fc0b73f01ab72aabbaeeb75  shinyproxy-2.3.0.jar
[14:43:05][~/apps/shinyproxy]$ sha256sum shinyproxy-2.3.1.jar
29b8484a013f81667b325430d5735a1d23ab94752a4d462b9e1b1f680133dfeb  shinyproxy-2.3.1.jar
[14:43:18][~/apps/shinyproxy]$ cat shinyproxy-2.3.1.jar.sha256
d3bae4d11b9f3e1a56bf96d8fd5acad90f33d05820920c92366ce2895d8099ac[14:43:18][~/apps/shinyproxy]$
```

**Comment by aiham** [comment]
Any update on this? I think it's pretty serious if the checksums are not matching. Both the sha256 and md5 checksums do not match the jar files that are on the website and github releases page. They are also in invalid formats (unlike 2.3.0). If it's a bug then it defeats the purpose of the checksums, if it's malicious then that's very serious.

cc @tverbeke

**Comment by aiham** [comment]
Just for context I've held back from upgrading to 2.3.1 because of this since CI automatically checks the checksum during deployment, but I've just hit #140 and am now forced to upgrade. Thanks for taking a look.

**Comment by tverbeke** [comment]
Thanks @aiham - will fix it today.

**Comment by aiham** [comment]
@tverbeke Thanks for the prompt response!

**Comment by tverbeke** [comment]
@aiham the jar files are identical on nexus (https://nexus.openanalytics.eu/service/rest/repository/browse/releases/eu/openanalytics/shinyproxy/2.3.1/), shinyproxy.io and Github. The checksum files hosted on nexus (https://nexus.openanalytics.eu/service/rest/repository/browse/releases/eu/openanalytics/shinyproxy/2.3.1/) are wrong, probably because they are overwritten for different extensions (for `shinyproxy-2.3.1.jar` a file `shinyproxy-2.3.1.md5` is generated instead of `shinyproxy-2.3.1.jar.md5` and this will be overwritten e.g. when a checksum is made for `shinyproxy-2.3.1.pom` which also results in `shinyproxy-2.3.1.md5`). I could not yet pinpoint the exact sequence of steps, but we will definitely fix this for the next release and for now the files and checksums on both shinyproxy.io and Github releases should match. Let me know if you still experience issues.

**Comment by aiham** [comment]
Thanks for the detailed response, the checksum is passing now. Cheers
