### ISSUE TITLE
Google social sign is broken for newer Google projects

### ISSUE THREAD

**Issue by aiham** [openanalytics/shinyproxy#213]
This is an upstream issue caused by containerproxy. I've created an issue there https://github.com/openanalytics/containerproxy/issues/37 and creating one here too for tracking and search-ability.

**Comment by tverbeke** [comment]
Thanks, @aiham - we'll have a look.

**Comment by LEDfan** [comment]
Hi @aiham

Thank you for your investigation. We upgraded the google social dependency in the latest release (ContainerProxy 0.8.5 and ShinyProxy 2.4.0)

Feel free to re-open if you still encounter the issue.
