### ISSUE TITLE
Retrieving Id token from Cognito inside the Container

### ISSUE THREAD

**Issue by Rama-13** [openanalytics/shinyproxy#217]
I'm using Cognito as open ID provider. The access is provided based on role attached to user group to which the user belongs to in the Cognito User pool. The user should be able to access S3 resources according to what his role permits. For this, the user should be able to generate credentials inside the container, so that the scripts call only that bucket and nothing else. For generating these AWS credentials we would be needing the Id token generated during Cognito Authentication. Is there anyway we can set the Id token also as an env variable similar to access token that we're setting at SHINYPROXY_OIDC_ACCESS_TOKEN ? 

Any help is greatly welcome. Let me know if application.yml or any configuration details is needed

**Comment by LEDfan** [comment]
This is now possible with [ShinyProxy 2.6.0](https://shinyproxy.io/downloads/#260) (ContainerProxy 0.8.10).

See https://shinyproxy.io/documentation/spel/ for more documentation.

Thank you for the suggestion!
