### ISSUE TITLE
ctrl+c stop shinyproxy and restart will not stop running container

### ISSUE THREAD

**Issue by shrektan** [openanalytics/shinyproxy#22]
Hi, 

When I use Ctrl+C to stop shinyproxy and restart (e.g., in order to add an app),  I find that the running container will not be stopped. This leads to a consequence that the corresponding port (like 20000) is used and  shinyproxy will not be able to launch the app.

So, my questions are:

1. How can I be able to stop shinyproxy with the related container being stopped first?
1. Why doesn't shinyproxy just use another port if it has been used?
1. What's more bad is: if shinyproxy fails to launch one app once, it seems like the app won't be launched successfully even after the old container being removed.

Thanks.

**Comment by tverbeke** [comment]
The scenario you describe is definitely not the intended or default behaviour. We have 10s of systems in production where restarting ShinyProxy nicely shuts down the containers it manages. Is it possible to share a log file? One thing I observed in the past is that manual shutdowns of containers launched via ShinyProxy could lead to erratic behaviour, but I am not sure how relevant this is for what you report.

**Comment by shrektan** [comment]
Well, I'll try to see if I can reproduce the issue on a cleaner environment. Thanks.
