### ISSUE TITLE
prometheus metrics

### ISSUE THREAD

**Issue by kfox1111** [openanalytics/shinyproxy#220]
It would be great if metrics could be exposed in prometheus format for things like active users, how long it takes to spin up a users container, etc.

**Comment by LEDfan** [comment]
Hi @kfox1111 

ShinyProxy 2.5.0 is now able to expose Prometheus metrics! You can find all information here https://shinyproxy.io/documentation/usage-statistics/#micrometer .
Although we tried to design and test this feature in a good way, we are looking for some feedback on it. Please open an issue when you have some feedback on it.
