### ISSUE TITLE
Navbar Brand Logo Path Error

### ISSUE THREAD

**Issue by jaysnm** [openanalytics/shinyproxy#221]
Hi
First and foremost thank you for this excellent project. 
I have thoroughly reviewed previously submitted issue reports not to open an already existing. 
It happens that ShinyProxy correctly finds the navbar brand logo on landing page (apps listing page) but loses grip of the path once a user launches an app. The relative paths for both landing page and in-app page are the same,  `<img class="navbar-brand" src="./assets/img/brand-logo.png">` . However, full path changes to `https://domain/assets/img/brand-logo.png` and `https://domain/app/assets/img/brand-logo.png` for landing page and in-app page respectively when the relative paths are opened on a new tab. Seems when in app, the `/app/` introduced is the cause of the error. This could be an error on thymeleaf template. Kindly let me know your take on this.
I will also be glad to hear progress with issue #149. 
Thank you in advance.

**Comment by Dusan-Dingarac** [comment]
Hi Jaysnm,

try to use absolute path for logo like this:

logo-url: file:///etc/shinyproxy/logo.png

if you need same logo for all apps. If you need custom logo for each app, I do not think that this is not easily possible to make... But it can be done.

Regards
Dusan

**Comment by jaysnm** [comment]
Thanks for reverting Dusan 
I'm using absolute path which solves the issue.

Leaving my solution here for someone else stuck on this:
I'm using [2col html templete](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template/templates/2col)
```
logo-url: /assets/img/brand-logo.png
favicon-path: /assets/img/brand-logo.png
template-path: ./2col
```
Will go ahead and close the issue.
