### ISSUE TITLE
Shinyproxy error 500

### ISSUE THREAD

**Issue by aysegokce** [openanalytics/shinyproxy#223]
Hi 
I have encounter Error 500 when I try to run shinyproxy. Here are the errors.

`Caused by: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1] failed: Connection refused (Connection refused)`
`Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1] failed: Connection refused (Connection refused)`

and application.yml

`proxy:
  title: Open Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 3838
  authentication: simple
  admin-groups: scientists
  hide-navbar: true

  users:
  - name: jack
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  
 
  docker:
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: Euler
    display-name: Try2
    description: Application which demonstrates the basics of a Shiny app
    port: 3838
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: gokcekeskus/euler
    access-groups: [scientists, mathematicians]

logging:
  file:
    shinyproxy.log`

I allowed port3838 in windows firewall but didnt fix the problem. I checked **Expose daemon on tcp://localhost:2375 without TLS** in docker settings. Uninstall and re-install docker but none of these helped.

**Comment by PauloJhonny** [comment]
Hi, @aysegokce.

Did you try to change port 3838 to 8080?

See the standard configuration here: https://www.shinyproxy.io/configuration/

**Comment by aysegokce** [comment]
Thanks @PauloJhonny  I tried and I got same error. When I run docker image with docker run command it works fine but when I run it through shinyproxy it gives error.

**Comment by mnazarov** [comment]
have you tried configuring docker startup options as described in https://www.shinyproxy.io/getting-started/#docker-startup-options ?

**Comment by aysegokce** [comment]
I removed 
`url: http://localhost:2375`
and it is working now.

**Comment by LEDfan** [comment]
@aysegokce since your problem is solved I'm going to close this issue.
Feel free to open a new issue if you encounter another problem or have a suggestion!
