### ISSUE TITLE
scaling

### ISSUE THREAD

**Issue by kfox1111** [openanalytics/shinyproxy#228]
It would be preferable in a Kubernetes environment to be able to have multiple shinyproxy instances running at once.

This would require that user pods don't terminate when a single instance of shinyproxy goes away and that the cookies contain all data necessary to talk to the backend and any encryption keys for the cookie can be specified to all instances.

**Comment by junkiebev** [comment]
How would one preserve session-state across instances? Some sort of redis cache? Maybe a label-set on the backend pods?

**Comment by kfox1111** [comment]
Yeah. label on the backend pod could work. or a signed cookie (probably the fastest option). redis would work too, but slightly less ideal unless there is a lot of state, as its another service to have to manage. Or maybe a service per users pod. then k8s service discovery (dns) could route the request.

**Comment by tverbeke** [comment]
@kfox1111 @junkiebev We are currently working on session persistence and will take HA into account.

**Comment by kfox1111** [comment]
Awesome. Thanks! :)

**Comment by LEDfan** [comment]
Hi, today we released ShinyProxy 3.0.0, which includes support for High Availability and Scaling!
Checkout out the [release notes](https://shinyproxy.io/downloads/) or the updated [ShinyProxy Operator](https://github.com/openanalytics/shinyproxy-operator)
