### ISSUE TITLE
FYI: Vulnerability in feature of bootsrap 3.3.7 (loaded in BaseController.java)

### ISSUE THREAD

**Issue by CorneeldH** [openanalytics/shinyproxy#232]
During a vulnerability scan of our ShinyProxy app, we got a report that Bootstrap 3.3.7 (loaded in BaseController.java) has security issues (although I don't think the vulnerable feature is used)::

The library bootstrap version 3.3.7 has known security issues. 

For more information, visit those websites: 
https://github.com/twbs/bootstrap/issues/28236

Affected versions: The vulnerability is affecting all versions prior 3.4.1 (between * and 3.4.1)

Other considerations:
The vulnerability might be affecting a feature of the library that the website is not using. If the vulnerable feature is not used, this alert can be considered false positive.

**Comment by LEDfan** [comment]
Hi @CorneeldH 

Thank you for your report. Bootstrap was upgraded to a secure version in the latest release ([ShinyProxy 2.4.0](https://shinyproxy.io/downloads/#240))
