### ISSUE TITLE
2.4.1 Error solved by redownloading 2.3.1:  SAML message intended destination endpoint did not match recipient endpoint

### ISSUE THREAD

**Issue by RoelRotti** [openanalytics/shinyproxy#247]
Caused by: org.opensaml.xml.security.SecurityException: SAML message intended destination endpoint did not match recipient endpoint

**Comment by LEDfan** [comment]
Hi @RoelRotti 

In order to solve this issue, we will need some more information:
 - how are you running ShinyProxy (using the jar, Docker, Kubernetes etc)
 - provide your application.yaml file (remove sensitive values)
 - are you using a load-balancer, which, how is it configured (e.g. is it passing the X-Forwarded headers) etc
 - which SAML provider are you using
 
Thanks

**Comment by RoelRotti** [comment]
Hi,
I'm running from Docker. I believe I am not using a load balancer. although
I am forwarding something in my yml file. My yml file isi the following
(removed sensitive values). I am using SURFconext as SAML provider. Cheers

# See also: https://www.shinyproxy.io/configuration/ proxy: title: Open
Analytics Shiny Proxy logo-url:
http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
########################################################## ## CHANGE APP :
## # 'app/01_hello' is the demo app provided by Shinyproxy # 'app/PFS' is
the Plan For Succes app from the VU # -> both are defined below #
(UN)COMMENT LINES BELOW TO (IN)ACTIVATE #landing-page: /app/01_hello
landing-page: /app/PFS
########################################################## heartbeat-rate:
10000 heartbeat-timeout: 60000 port: 8080 container-log-path:
./container-logs hide-navbar: true
########################################################## ## CHANGE
AUTHENTICATION : ## # 'ldap' is standard authentication provided by
Shinyproxy # TO TEST: UN: 'tesla', PW: 'password' # # (UN)COMMENT LINES
BELOW TO (IN)ACTIVATE authentication: ldap #authentication: saml
########################################################## # This is
connection to SURFconext test environment # Later on this must be specified
with correct entity-id and url saml:
########################################################## ## CHANGE URL to
go from test -> publish : ## idp-metadata-url:
##########################################################
########################################################## ## CHANGE URL to
your own URL : ## app-entity-id: app-base-url:
########################################################## name-attribute:
urn:oid:0.9.2342.19200300.100.1.1 # Example: 'ldap' authentication
configuration ldap: url: ldap://ldap.forumsys.com:389/dc=example,dc=com
user-dn-pattern: uid={0} group-search-base: group-search-filter:
(uniqueMember={0}) manager-dn: cn=read-only-admin,dc=example,dc=com
manager-password: password # Docker configuration docker: cert-path:
/home/none url: http://localhost:2375 port-range-start: 20000 specs: # When
it al works there is no need for the shinyproxy-demo - id: 01_hello
display-name: Hello Application description: Application which demonstrates
the basics of a Shiny app container-cmd: ["R", "-e",
"shinyproxy::run_01_hello()"] container-image:
openanalytics/shinyproxy-demo - id: display-name: container-cmd: ["R",
"-e", "shiny::runApp('', host=getOption('0.0.0.0'), port=3838)"]
########################################################## ## CHANGE to own
app if needed : ## container-image:
########################################################## server:
useForwardHeaders: true logging: file: shinyproxy.log

Op ma 2 nov. 2020 om 11:52 schreef Tobia De Koninck <
notifications@github.com>:

**Comment by RoelRotti** [comment]
I see gmail wasn't too fond of the yml file so I'll post it again:

# See also: https://www.shinyproxy.io/configuration/
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png

  ########################################################## 
  ## CHANGE APP : ##
  # 'app/01_hello' is the demo app provided by Shinyproxy
  # '
  # -> both are defined below         
  # (UN)COMMENT LINES BELOW TO (IN)ACTIVATE

  #landing-page: /app/01_hello
  landing-page: 
  ##########################################################

  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  container-log-path: ./container-logs
  hide-navbar: true

  ##########################################################
  ## CHANGE AUTHENTICATION : ##
  # 'ldap' is standard authentication provided by Shinyproxy
  # TO TEST: UN: 'tesla', PW: 'password'
  #
  # 'saml' is authentication from the VU
  # 
  #  -> both are defined below 
  # (UN)COMMENT LINES BELOW TO (IN)ACTIVATE 
  
  authentication: ldap
  #authentication: saml
  ##########################################################

  
  #
  # Later on this must be specified with correct entity-id and url
  saml:
    ##########################################################
    ## CHANGE URL to go from test -> publish : ##
    idp-metadata-url: 
    ##########################################################
    ##########################################################
    ## CHANGE URL to your own URL : ##
    app-entity-id: 
    app-base-url:
    ##########################################################
    name-attribute: 

  # Example: 'ldap' authentication configuration
  # 
  ldap:
   url: ldap://ldap.forumsys.com:389/dc=example,dc=com
   user-dn-pattern: uid={0}
   group-search-base:
   group-search-filter: (uniqueMember={0})
   manager-dn: cn=read-only-admin,dc=example,dc=com
   manager-password: password
  
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  # When it al works there is no need for the shinyproxy-demo
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: 
    display-name: 
    container-cmd: ["R", "-e", "shiny::runApp('/root/PFS', host=getOption('0.0.0.0'), port=3838)"]
    
    ##########################################################
    ## CHANGE to own app if needed : ##
    container-image: 
    ##########################################################
server:
  useForwardHeaders: true
logging:
  file:
    shinyproxy.log

**Comment by RoelRotti** [comment]
To clarify, my Nginx configuration is like in the following example:
[[https://www.shinyproxy.io/security/]](url)

I again share my yml file since it wasn't readable again. This time without the comments (and sensitive info) so it is readable:

`# See also: https://www.shinyproxy.io/configuration/
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png

  landing-page: /app/01_hello
  #landing-page: 

  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  container-log-path: ./container-logs
  hide-navbar: true

  authentication: ldap
  #authentication: saml

    #idp-metadata-url: 
    idp-metadata-url: 

    app-entity-id: 
    app-base-url: 

    name-attribute: urn:oid:0.9.2342.19200300.100.1.1

  ldap:
   url: ldap://ldap.forumsys.com:389/dc=example,dc=com
   user-dn-pattern: uid={0}
   group-search-base:
   group-search-filter: (uniqueMember={0})
   manager-dn: cn=read-only-admin,dc=example,dc=com
   manager-password: password

  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:

  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: 
    display-name: 
    container-cmd: ["R", "-e", "shiny::runApp('/root', host=getOption('0.0.0.0'), port=3838)"]
    
    container-image: vuanalytics
server:
  useForwardHeaders: true
logging:
  file:
    shinyproxy.log`

**Comment by LEDfan** [comment]
Hi

I'm not sure what is causing this issue. I'm unable to reproduce it. I would try two things:
 - remove the useForwardHeaders option
 - make sure the app-base-url:  is 100% correct

**Comment by RoelRotti** [comment]
Hi LEDfan,
is there any more info I could provide so you will be able to reproduce it? Meanwhile I will look into your suggestions!

**Comment by LEDfan** [comment]
Currently not. Can you also try adding:
```
server:
  forward-headers-strategy: native
``` 
to you configuration? Because of another issue we noticed that this is the (new) correct configuration to setup the forwardHeaders option.

**Comment by RoelRotti** [comment]
Hi, I just tried downloading 4.1, and adding the above beneath 'forwardHeaders: True' and that worked! Without the 'forwardHeaders: True' it didn't work however. Thanks for the advice!
