### ISSUE TITLE
Implementing SSL in shinyproxy running on Kubernetes(EKS)

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy#249]
Hi Team,

I have shiny proxy running on EKS cluster in AWS.
I also have the SSL certs generated and have the .crt and .key file with me.
Can someone please let me know how can I get the https implemented so that the URL can be served on secured connection.
Please find the **service.yaml** as mentioned below:

apiVersion: v1
kind: Service
metadata:
  name: shiny-service
  namespace: shinyproxy
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
   service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: shinyproxy
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8

**Ingress.yaml** file is mentioned below:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: abcdefghtzsxcg34527464538384645373.elb.us-east-1.amazonaws.com
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
  name: shiny-proxy
  namespace: shinyproxy
spec:
  tls:
  - hosts:
    - abcd.example.com
    secretName: shinyapp-tls-secret
  rules:
  - host: abcd.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: shiny-service
          servicePort: http

Using the Loadbalancer type of service, Network Load balancer is used in the background for nginx ingress controller.

**Comment by LEDfan** [comment]
You should configure the nginx ingress to use the certs, see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
You are on the good way, but I think a few pieces are still missing. For example, I don't belies this is correct:
```
 nginx.ingress.kubernetes.io/backend-protocol: HTTPS
```
(since the nginx ingress would now contact the backend using TLS, but ShinyProxy does not support TLS out of itself)

**Comment by aupadh12** [comment]
Hi @LEDfan ,

I was able to fix it and also know the reason why this was not working. It was due to the fact the my setup was bypassing the Ingress controller and as a result, TLS termination was not happening.

**Comment by LEDfan** [comment]
That's great, thanks for letting us know. I'm closing this issue now, but feel free to open a new one if you need some help. Have a nice day!
