### ISSUE TITLE
openid authentication type not working due to invalid redirect_uri

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy#251]
Hi Team,

I am using the shinyproxy running on EKS with nginx ingress controller.
I am using authentication type as openid and want to implement SSO.
The callback url as per the documentation is : 
https://myapps.apps.abc.com/login/oauth2/code/shinyproxy
But after receiving all the required details for configuring this, i.e., 
  auth-url,    token-url,    jwks-url,    client-id: ,    client-secret: , I am not facing the issue where I am getting the error of invalid redirect_uri.
And this is happening because, the redirect_uri which is getting created is http://myapps.apps.abc.com/login/oauth2/code/shinyproxy  instead of https://myapps.apps.abc.com/login/oauth2/code/shinyproxy . So, the issue looks like its http instead of https.
Can someone help me in this to debug?

**Comment by LEDfan** [comment]
Hi @aupadh12 

If you are using a loadbalancer or reverse proxy, you have to add the following configuration to your application.yml.
```
server:
  forward-headers-strategy: native
```
As documented on this page: https://shinyproxy.io/documentation/security/#https-ssl--tls
Please provide more information about your setup if this doesn't solve your issue. Like you ShinyProxy version, loadbalancer or proxy type, application.yaml etc

**Comment by aupadh12** [comment]
Hi @LEDfan ,

I am using ClusterIP as ingress resource, nginx ingress controller which is of loadbalancer type (Network Load balancer) and shinyproxy version is 2.3.1 and so I am already using 
server:
    useForwardHeaders: true
which I think is what is needed.
Please let me know if you need more information?

**Comment by aupadh12** [comment]
@LEDfan : Anything on this which I can try?
