### ISSUE TITLE
Big image container start issue

### ISSUE THREAD

**Issue by kfox1111** [openanalytics/shinyproxy#252]
Saw this with shinyproxy version:
ShinyProxy 2.4.1 (ContainerProxy 0.8.5)

If the pod starts on a node that doesn't have the image and it takes a while to fetch, shinyproxy seems to give up looking for the ip but then tries for a while still with the null address. It should probably retry resolving the pod ip each time, if it is still null

2020-12-02 19:42:13.553  WARN 1 --- [  XNIO-1 task-6] e.o.shinyproxy.ShinyProxyTestStrategy    : Container unresponsive, trying again (231/1800): http://null:3838

**Comment by LEDfan** [comment]
Hi

We were aware of this bug and this is already solved in the next release. There will be a new option that allows you to configure the time, ShinyProxy waits for the pod to become ready. In 2.4.1 this was set to 60 seconds. After this period, the code would simply continue without checking whether the pod is ready. With the new code changes you will be able to configure this timeout and set it to e.g. 120 seconds. If the pod doesn't become ready after this point, an exception is thrown and the app is killed.

**Comment by LEDfan** [comment]
Hi @kfox1111 

This is now included in the [2.4.2 release](https://shinyproxy.io/downloads/#242).

**Comment by kfox1111** [comment]
Awesome. Thank you. :)
