### ISSUE TITLE
location of login.html template

### ISSUE THREAD

**Issue by nbbn** [openanalytics/shinyproxy#253]
Dear Shinyproxy Team,
I'm looking for login.html template that is used by shinyproxy by default.
Unfortunately, searching in code base of this repo allowed me only to find some templates in `src/main/resources/templates` but without this one.
Please direct me to right place.
Best,
Jakub

**Comment by shosaco** [comment]
The used file is located in the `jar`-file:

`shinyproxy-2.4.1.jar\BOOT-INF\lib\containerproxy-0.8.5.jar\templates\`

You can use `template-path: ./templates` in your `application.yml` with different login-Template to change the login experience.

**Comment by LEDfan** [comment]
Hi 

As pointed out above you could find the template file in the containerproxy.jar file. However, it also available at our ContainerProxy repo: https://github.com/openanalytics/containerproxy/tree/master/src/main/resources/templates

**Comment by LEDfan** [comment]
Hi @nbbn 

I think that you question is answered now, therefore I'm closing this issue. As always, feel free to open a new issue if you have any other question or issue.
