### ISSUE TITLE
content blocked due to MIME type error

### ISSUE THREAD

**Issue by jkh1** [openanalytics/shinyproxy#254]
After upgrading to shinyproxy-2.4.x, the login page produces these errors in the browser console:
```
The resource from “http://myserver:8080/webjars/bootstrap/3.3.7/css/bootstrap.min.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)
The resource from “http://myserver:8080/webjars/bootstrap/3.3.7/js/bootstrap.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
The resource from “http://myserver:8080/webjars/jquery/3.3.1/jquery.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
The resource from “http://myserver:8080/webjars/bootstrap/3.3.7/js/bootstrap.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)
```
Reverting to shinyproxy-2.3.1 makes the errors go away.

If that helps, a quick web search lead me [here](https://levlaz.org/spring-security-webjars-and-mime-type-error/) which suggests it could be a spring security configuration issue.

**Comment by LEDfan** [comment]
Hi @jkh1 

This typically happens when loading the JS and CSS files gives an error and therefore the webserver returns a HTML response body. Could you try going to `http://myserver:8080/webjars/bootstrap/3.3.7/css/bootstrap.min.css` and see what is outputted there? It should be a css fie, but I think that in your case some error page in HTML will be shown.

**Comment by jkh1** [comment]
Thanks. I get the css file with no error. Whatever the problem was seems to have resolved itself during the last week. I had given up on it and didn't touch the server in the last 8 days or so and only came back to it to test your suggestion.

**Comment by LEDfan** [comment]
Thanks for reporting back. In that case it was probably a temporary issue (e.g. 503).
I'm closing this issue now, but don't hesitate to open a new one if you encounter any issue.
