### ISSUE TITLE
Setup in documentation will lead to security warning when tryining to login

### ISSUE THREAD

**Issue by Data-Mastery** [openanalytics/shinyproxy#255]
Hello!

I use shinyproxy since 2,5 years, but since a few days I get a warning message when I try to login into our platform. I use nginx in combination with keycloak. My nginx.conf looks like this:
SSL certs are linked as always, there is NO ERROR in the setup, it just produces a warning...

```
   location / {

    proxy_pass          http://shinyproxy:4000; ### Übernahme der servicenamen aus Docker-compose

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 600s;

    proxy_redirect    off;
    proxy_set_header  Host             $http_host;
    proxy_set_header  X-Real-IP        $remote_addr;
    proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Protocol $scheme;
    }

   location /auth/ {
   
    proxy_pass          https://keycloak:8443; ### Übernahme der servicenamen aus Docker-compose

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 600s;

    proxy_redirect    off;
    proxy_set_header  Host             $http_host;
    proxy_set_header  X-Real-IP        $remote_addr;
    proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;

    }
```
This is the warning triggered:

![warning](https://user-images.githubusercontent.com/64363987/102217913-8da49480-3edd-11eb-8fa1-93dbbdc0b901.PNG)

The setup is directly taken from here: https://www.shinyproxy.io/security/

It only happens on Google Chrome, but since it is the most common browser, this is an issue. Have you already encountered this and/or maybe have an idea how to fix it?

Thank you, 
Markus

**Comment by mnazarov** [comment]
this seems to be unrelated to the shinyproxy per se, but rather to your nginx setup. Please see https://bugs.chromium.org/p/chromium/issues/detail?id=1158169#c49 for explanation (tldr you need to avoid mixing http and https)

**Comment by Data-Mastery** [comment]
Yeah, I thought so, hoped you already faced that issue before and you know how to fix it, since 

`proxy_pass          http://shinyproxy:4000`

will not work. But okay, the link is great, maybe I can find something :-)

**Comment by mnazarov** [comment]
Sorry I didn't realize that your example is copied from the documentation, so I will keep the issue open.

**Comment by LEDfan** [comment]
Hi, as explained [here](https://blog.chromium.org/2020/08/protecting-google-chrome-users-from.html) this error by Chrome means that you are on a HTTPs protected page, but you are trying submit a form to a HTTP page.
This could happen when ShinyProxy doesn't know you are accessing the page over HTTPs. Did you properly configure ShinyProxy to use forward-headers, as explained in [our documentation](https://shinyproxy.io/documentation/security/#forward-headers).

**Comment by Data-Mastery** [comment]
Hello! The error does not appear anymore, it also was only on chrome. I guess it was more a chrome issue, than an issue of my setup. forward-headers are set, and now everything works smooth again. Not sure if we can close it for now?!

**Comment by LEDfan** [comment]
Thanks for reporting back, let's close this issue for now.
