### ISSUE TITLE
Can't remove cookie on ShinyProxy 2.4.2

### ISSUE THREAD

**Issue by kuzmenkov111** [openanalytics/shinyproxy#257]
Hi!

It was possible to remove cookies JSESSIONID on the previous version of ShinyProxy 2.3.0. by using
  ```   shinyjs::runjs(
        'Cookies.remove(\'JSESSIONID\');
          window.location.href=window.location.href'
      )
```

On current version 2.4.2, this expression doesn't work. It can't delete JSESSIONID  cookie.

What's wrong?

OR 
How to logout from inside the app (I mean from an inside the container)?

**Comment by LEDfan** [comment]
Hi @kuzmenkov111 

Starting from ShinyProxy 2.3.1, the session cookie (`JSESSIONID`) is created with the `httponly` flag. This means that you cannot edit the cookie using JavaScript. This is an important security feature. If you really want you can turn this off using the 
`server.servlet.session.cookie.http-only=false ` property (you have to expand this in your yaml file).

However, as I said before this is an important security feature, as it protects against certain effects of XSS attacks.

I think you should be able to logout from an app by redirecting to `/logout`, e.g. using:

`window.location.href='/logout'`

**Comment by kuzmenkov111** [comment]
Many thanks! It works!
