### ISSUE TITLE
Launching status prompt not displayed correctly in Chrome

### ISSUE THREAD

**Issue by keqiang** [openanalytics/shinyproxy#26]
I’m accessing my ShinyProxy applications in latest Chrome on the latest MacOS, the status is showing at the bottom of the page and is overlayed on the status bar of the browser.

**Comment by tverbeke** [comment]
thanks for reporting @keqiang - Can you add a screenshot, so we see the erroneous behaviour?

**Comment by keqiang** [comment]
I'm adding a screenshot. Sometimes the status will disappear after the app is launched, but in this case, it's always on the page.
![status](https://user-images.githubusercontent.com/8900180/31965760-5cedc054-b8d6-11e7-8699-3772ca8f083f.jpg)

**Comment by cmattoon** [comment]
I was experiencing this as well, but the issue seemed to resolve itself before I got around to debugging it. (Possibly the 'Disable Cache' checkbox in Chrome DevTools/hard refresh solved it?)

Do you have any JS/websocket errors in the console?

**Comment by keqiang** [comment]
Same here. The issue disappears somehow after a while and in my case I didn't do anything troubleshooting it. I will report back with the console information once I got the issue again.

**Comment by LEDfan** [comment]
As I believe that your question is answered, I'm closing this issue. Feel free to re-open it if you need more help.
