### ISSUE TITLE
when I use container-network: host, the app doesn't launch 

### ISSUE THREAD

**Issue by Andryas** [openanalytics/shinyproxy#260]
I don't know why but when I use this configuration for the app

proxy:
  title: TSER
  landing-page: /
  template-path: ./templates  
  heartbeat-rate: 10000
  heartbeat-timeout: 50000
  port: 8080
  authentication: none
  container-wait-time: 60000
  hide-navbar: true
 
  docker:
    cert-path: /home/none
    url: http://127.0.0.1:2375
    port-range-start: 20000
    
  specs:
  - id: teste
    display-name: teste
    container-cmd: ["R", "-e", "shiny::runApp('/root/app', port = 3838, host = '0.0.0.0')"]
    container-image: tser/simple
    container-network: host
    
   the application doesn't launch through shinyproxy but is available in the IP 0.0.0.0:3838
   
   
![Screenshot from 2021-01-14 18-57-05](https://user-images.githubusercontent.com/24782390/104654303-a0f07e80-569a-11eb-98eb-3f519d292795.png)
![Screenshot from 2021-01-14 18-57-10](https://user-images.githubusercontent.com/24782390/104654304-a221ab80-569a-11eb-9c4f-d276a86cd0d0.png)
![Screenshot from 2021-01-14 18-57-12](https://user-images.githubusercontent.com/24782390/104654307-a2ba4200-569a-11eb-9c5a-127ddd9c3ebb.png)

**Comment by LEDfan** [comment]
Hi @Andryas 

Thanks for checking out ShinyProxy! The issue you are facing is actually the expected behavior. When you tell ShinyProxy to use the `host` network for a container, the container runs more like a normal process on your computer (/server). In other words, it doesn't has the network isolation you normally have when using Docker. Therefore, it is impossible for ShinyProxy to forward any ports to the Docker container. In order to fix this, you have to enable the `internal-networking` feature, which tells ShinyProxy to directly reach the Docker container on `http://localhost:3838` and not use port forwards. You should change your configuraion as follows:

```
# ...
docker:
    cert-path: /home/none
    url: http://127.0.0.1:2375  
    port-range-start: 20000
    internal-networking: true
# ...
```

**Comment by Andryas** [comment]
Thank you @LEDfan for the answer. 

Yes, I tried it before but I had an unexpected behavior. 
When I launch an app it usually works, but when I go back to the home page of shinyproxy and run another, the same app, that I just launch, appears again, not which I just selected. 
Besides that, if I launch an app and then go back to the home page and wait for a while and then run another app everything works perfectly. What happens is that I am waiting for the container to die and then start a new one. But this happens because of this parameter in the YAML `internal-networking: true`. 
In the end, what I am trying to do is to access a local database (MySQL server) but my problem is if I use the internal-networking I had this issue about can't change very fast between the apps, and if I do not use the internal-networking the apps do not launch at the shinyproxy, and if I do not use the container-networking: host I can access the database.

What do you suggest @LEDfan?

**Comment by Andryas** [comment]
If anyone in the future wants to access a local MySQL server inside a container using the bridge network I solve the problem with this:

```
id: teste
display-name: teste
container-cmd: ["R", "-e", "shiny::runApp('/root/app', port = 3838, host = '0.0.0.0')"]
container-image: tser/simple
container-network: host
container-volumes: ["/var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock"]
```

**Comment by LEDfan** [comment]
Thanks @Andryas for sharing your solution!
