### ISSUE TITLE
SHINYPROXY_USERNAME

### ISSUE THREAD

**Issue by fmmattioni** [openanalytics/shinyproxy#263]
Hi, I am currently using AWS cognito for my authentication.

I was wondering if I can have multiple scopes returned, like `username`, and `sub` returned in an environment variable like `SHINYPROXY_USERNAME` in addition to the `SHINYPROXY_USERGROUPS` env var?

In summary, I was looking for a way to have something like:

`SHINYPROXY_USERNAME[1] = username`
`SHINYPROXY_USERNAME[2] = sub`
`SHINYPROXY_USERGROUPS = group name`

Thanks!

**Comment by LEDfan** [comment]
Hi 

Currently we don't support this and we also don't really have plans to do this.
I'll keep this issue open as a feature request and we will keep this in mind!

**Comment by fmmattioni** [comment]
Thank you very much for the reply!

Do you know if there is a hacky way to achieve this? Can I perhaps point the `SHINYPROXY_OIDC_ACCESS_TOKEN` var to another scope variable?

**Comment by LEDfan** [comment]
Hi @fmmattioni 

We re-considered this and similarly to https://github.com/openanalytics/containerproxy/issues/47 we are working on a way to make this possible without causing other issues.

Unfortunately, like the other issue this will not be part of the next release. I'll let you know when we are going to release this (or when you can try it out)

**Comment by fmmattioni** [comment]
Thank you so much!

**Comment by LEDfan** [comment]
This is now part of [ShinyProxy 2.6.0](https://shinyproxy.io/downloads/#260) (ContainerProxy 0.8.10).

See https://shinyproxy.io/documentation/spel/ for more documentation.

Thank you for the suggestion!

**Comment by fmmattioni** [comment]
wow, really cool!!! thank you!!
