### ISSUE TITLE
Usage statistics for shinyproxy running on Kubernetes

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy#266]
Hi Team,

I am running shinyproxy on EKS and have setup Prometheus and Grafana for system metrics.
However, I am also looking at setting up the usage metrics for each shinyapp running on shinyproxy using EKS.
Has anyone implemented any of the available solutions for usage statistics on Kubernetes? If yes, then any help would be much appreciated.

**Comment by aupadh12** [comment]
Hi All,

I was able to launch the influxdb to run on kubernetes and I can see the events getting logged into the influxdb.
I am currently trying to create a dashboard in Grafana and ty to make some sense out of it.
Can someone please help?

**Comment by aupadh12** [comment]
Hi all,

Closing this one. Telegraph is not needed. I was able to get the data into Grafana. Everything is working fine.

**Comment by AdrianHordyk** [comment]
> Everything is working fine.

Any chance you're able to share examples of your queries in the Grafana dashboard?

I've followed the process outlined [here](https://www.databentobox.com/2020/05/31/shinyproxy-with-docker-swarm/#optional-monitoring-shinyproxy-with-grafana-and-influxdbl) and can get a graph of logins over time but nothing else.
