### ISSUE TITLE
landing-page

### ISSUE THREAD

**Issue by fmmattioni** [openanalytics/shinyproxy#269]
I was wondering if there is a way that, after authentication, if the user belongs to a group that has only **one app**, this user could be already redirected to the app without having to click the link on the landing page?

If there isn't a way right now, what would be the source file that I could modify in order to achieve that?

Thank you!
Felipe

**Comment by LEDfan** [comment]
Hi @fmmattioni 

AFAIK there is currently no standard way to do this in ShinyProxy. However, you could try to create a template that does this. 
See https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template for how to configure ShinyProxy to use custom templates.

For example you could add the following code in the `index.html` template, just before `</head>`

```
	<script th:if="${apps.length == 1}">
		window.location.replace("/app/rstudio");
	</script>
```

This is not the most beautiful way to do it, but it works without having to recompile ShinyProxy.

If you don't mind recompiling ShinyProxy you could add the following code:

```
		if (apps.length == 1) {
			return "redirect:/app/" + apps[0].getId();
		}
```
after line 45 of `IndexController`, see: https://github.com/openanalytics/shinyproxy/blob/master/src/main/java/eu/openanalytics/shinyproxy/controllers/IndexController.java#L46

**Comment by fmmattioni** [comment]
This is fantastic!!!

Thank you!!!

**Comment by Dusan-Dingarac** [comment]
Tobia,

maybe you can add second solution to list of features for next version. Together with one switch in application.yml file.

It is really much better solution for users with one app than landing page or direct link to app.

Dusan

**Comment by nickmelis** [comment]
Very similar use case here: 
- We want users to override the default behaviour and land on an app directly, without having to go through the default landing page
- Specifying `proxy.landing-page` with a specific app may not work for all users, due to permissions

I believe this would be easily achievable by having a `proxy.landing-page: auto` option which redirects the logged in user to the first app on the list. See pseudocode below.

IndexController.java
```
[...]
ProxySpec[] apps = proxyService.getProxySpecs(null, false).toArray(new ProxySpec[0]);
    map.put("apps", apps);

    // If set to `auto`, redirect to the first available app in the list
    if (apps.length > 0 && landingPage.equals("auto")) {
      return new RedirectView("/app/" + apps[0].getId());
    }
[...]
```

If there is enough interest, I would be more than happy to submit a PR for this.

**Comment by LEDfan** [comment]
Hi @nickmelis , that would be a great solution, so feel free to open a PR.

**Comment by nickmelis** [comment]
@LEDfan https://github.com/openanalytics/shinyproxy/pull/448 PR is in 😃
