### ISSUE TITLE
Working with API

### ISSUE THREAD

**Issue by jaysnm** [openanalytics/shinyproxy#271]
Hi Shinyproxy team, thank you for this amazing project. We have found it very useful. 

I have configured two instances of shinyproxy, one where no authentication is required and the other one protected. Thought the API is the perfect way I can bring apps on both instances in a single website where by default users see a list of apps from no-auth-required instance and once they log-in other apps in the auth-required instance get appended to the list.

I have tried [API config example](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/07-api-embedded-app) which shows this error which I believe is tied to shinyproxy CORS validation because I'm running the embended api index.html outside shinyproxy (the desired behavior).
![image](https://user-images.githubusercontent.com/20385376/106714649-31bcd900-660d-11eb-8225-7e163d612e57.png)

In addition to above issue, I'm worried the /api/proxyspec is exposing a lot of information some of which I consider sensitive. Presumably, most of these specs are intended for internal use within shinyproxy other than proxy id, description and title

**Comment by LEDfan** [comment]
Hi @jaysnm 

Currently we don't have any way to configure CORS for ShinyProxy. I added this as a feature request in our internal tracker. However, I believe you could also configure this using a reverse-proxy (e.g. nginx).

For the issue with the API, I think I agree that the API may expose too much information in some situations. I also created a feature request for this. Again you could tweak your reverse proxy to don't allow any request to `/api/proxyspec`.

I'm keeping this issue open to keep track of the two feature requests.

**Comment by jaysnm** [comment]
Hi @LEDfan 
Thank you very much for reverting. You and your team are amazing. Also, thank you for supporting shinyproxy, it is incredible compared to what have been using for app deployments.
Looking forward to testing the features.

**Comment by nik-humphries** [comment]
Sorry to revive something old - what was the status on being able to hide or reduce visible info on `/api/proxyspec` by configuration? Is this something still on the backlog?

**Comment by LEDfan** [comment]
Hi @nik-humphries 

This is currently still in development, but I'll definitely make this part of the next release. I don't have an ETA yet for the next release (but a lot of good things are planned :) )

**Comment by LEDfan** [comment]
Hi, today we released ShinyProxy 3.0.0 which by default hides all sensitive values in the API. This is the case for both the proxyspec API and the API returning information about active apps. You can optionally configure ShinyProxy to return the full proxyspec, see: https://shinyproxy.io/documentation/configuration/#hide-spec-details

**Comment by jaysnm** [comment]
Thank you @LEDfan and shinyproxy team for this fantastic job. It has always been a pleasure working with shinyproxy.
@oyogo this could be interesting to you.

**Comment by oyogo** [comment]
@jaysnm Thanks Jason, let me have a look at it.
