### ISSUE TITLE
Issue when jsessionid cookie is disabled and authentication is set none

### ISSUE THREAD

**Issue by psolymos** [openanalytics/shinyproxy#272]
Dear OpenAnalytics!

First of all, thank you for making and supporting ShinyProxy, it is an incredibly useful tool that we have been using for many years without issues. The problem I (and others that I have been in touch with) have been having relates to ShinyProxy configured with `authentication: none`, i.e. when non-authenticated users (general public) can open apps.

We have noticed that ShinyProxy starts to deploy new Docker containers if a user disables cookies (jsessionid) for the ShinyProxy site. The result is that the whole server goes down.

This *might* be because every time the server receives a new connection from the same user (without a cookie), ShinyProxy would treat it as a new user without being able to determine session continuity.

I was wondering if this is a known issue and if there is a work around. Thanks!

**Comment by LEDfan** [comment]
Hi @psolymos 

Thank you for the kind words!

> This might be because every time the server receives a new connection from the same user (without a cookie), ShinyProxy would treat it as a new user without being able to determine session continuity.

Exactly, that's what is happening.
I understand you issue, but I don't think there is any secure way to make it work without cookies. 
You could try two workarounds:
 - change the cookie name, maybe the cookie doesn't get blocked with a different name:
 ```
server:
  servlet:
    session:
      cookie:
        name: MY_SESSIONCOOKIE
``` 
 - if you are using TLS you could try to set:
```
server:
  servlet:
    session:
      tracking-modes: SSL 
```
This will re-use the TLS session for managing the users. I don't have experience with this and I would only advice to use this if you know yourself that this is secure.

Cookies are the best-practice and default way of managing user session's and I would say that almost every website is doing it in this way. Therefore I don't think there are any *good* workarounds for this.

**Comment by psolymos** [comment]
Thanks @LEDfan !
