### ISSUE TITLE
Websocket Workaround?

### ISSUE THREAD

**Issue by rashmead** [openanalytics/shinyproxy#287]
We are trying to implement shinyproxy but are running into a websockets error in our production environment - mainly that they are not allowed by the security team.  The error causes the app to crash right after launching.  Has anyone encountered this issue before and found a workaround?  We have been able to get shiny server products to work successfully in the past in the same environment.  While they do still generate a websockets error if we look closely, it seems they are resilient to the error due to stepping down to alternative protocols (https://docs.rstudio.com/shiny-server/1.5.3/#disabling-websockets-on-the-server).  Thanks for any help.

**Comment by tverbeke** [comment]
Hi @rashmead Thank you for your question. When secured properly WebSockets are not more unsafe than HTTP. ShinyProxy does not support the alternatives based on SockJS (and this is not planned), so the remaining option is to educate your security team (or ask them to use proper configuration of their proxies, see e.g. https://shinyproxy.io/documentation/security/#https-ssl--tls). Many of our corporate customers serve internet-facing Shiny apps using ShinyProxy. HTH, Tobias
