### ISSUE TITLE
TLS cookie without secure flag set

### ISSUE THREAD

**Issue by nbbn** [openanalytics/shinyproxy#289]
Hi,
I've got shinyproxy behind nginx reverse proxy with https.
I recently noted that TLS cookie set by shinyproxy is without secure flag set, what is recommended in this case.
I think it would be good to have some option in config file to inform shinyproxy that we are behind secure connection.
Tested on shinyproxy 2.5.0.

**Comment by tverbeke** [comment]
Hello @nbbn 

See https://shinyproxy.io/documentation/configuration/#security

Best,
Tobias

**Comment by nbbn** [comment]
This is what I need, thank you!
