### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by algo-se** [openanalytics/shinyproxy#307]
Hi, when using ShinyProxy instead of deploying the apps directly through Docker, the responsiveness of the apps in mobile devices is lost. 

I´ve seen there is a [PR](https://github.com/openanalytics/shinyproxy/pull/179) that tries to solve this. Any ETA on when this could be implemented?

**Comment by dseynaev** [comment]
Hi @algo-se,

the linked PR only makes changes to the default theme. You can achieve the same result with a custom theme. More info and examples [here](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template)

there is also a workaround where you can use `/app_direct/<app_name>` endpoints which will serve the app content directly without the iframe that can cause issues on mobile.

**Comment by algo-se** [comment]
Oh I see, thank you for the clarification @dseynaev! So do you have to use a custom theme in order to enable `app_direct` endpoints in the landing page? Is there any other way, can you do it from the application.yml?

**Comment by dseynaev** [comment]
`app_direct` endpoints are be available by default (provided you are using a recent enough version of shinyproxy)

the suggestion to use a custom theme is a completely separate workaround I meant that you could try out the fix implemented in https://github.com/openanalytics/shinyproxy/pull/179 by copying the app.html from that PR and use it as a custom theme

**Comment by dseynaev** [comment]
to have the landing page use `app_direct` links you would need a custom theme indeed. There is afaik no way to do it from the `application.yaml` (unless you only have one app, in which case you could use the `landing-page` setting to skip the landing page)

**Comment by algo-se** [comment]
I´ve followed [these steps](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template) but I can´t see any changes. 

To set up Shiny Proxy I used [this tutorial](https://www.databentobox.com/2020/05/31/shinyproxy-with-docker-swarm/) , so I´m using Docker Swarm.

My folder structure is:
//home/myuser/shinyproxy-docker-swarm-demo/
├── application
│   ├── application.yml
│   └── templates  
├── shinyproxy.yml
└── usagestats.yml

`templates` folder is the one from the shinyproxy-config-examples.

In the `application.yml` I added: `template-path: ./templates/1col`

In order to make the changes effective I restarted Shiny Proxy: `docker service update shinyproxy_shinyproxy --force` but everything stayed the same. Any ideas?

**Comment by dseynaev** [comment]
Looking at the tutorial you linked my guess would be that you need to mount the templates folder into the shinyproxy container in docker-compose configuration `shinyproxy.yml`

**Comment by algo-se** [comment]
Awesome guess! 😉   That worked perfectly, thank you. 

In case it´s useful for other people, here is what I've done:

1. Add `./application/templates:/opt/shinyproxy/templates` to `volumes` in `shinyproxy.yml`
![image](https://user-images.githubusercontent.com/72490678/125596723-f54fbc7a-0250-4399-9f35-37fde0c9f9ed.png)

2. Add [all the templates](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template#where-to-find-the-original-template-files) to the 1col folder.
![image](https://user-images.githubusercontent.com/72490678/125597626-a197c902-0110-46bd-8be2-2f43f11ca6b5.png)

3. Edit the `head` tag of all the templates:
3.1. Add `<meta name="viewport" content="width=device-width, initial-scale=1">` so that thymeleaf works well in mobile devices.
3.2. Add bootstrap calls manually
3.3. Add title manually
3.4. Change the reference to css files according to the [new folder structure](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template/templates).
3.5 Add favicon reference (also [see this](https://github.com/openanalytics/shinyproxy/issues/163#issuecomment-510005415) for favicons when launching an app).
![image](https://user-images.githubusercontent.com/72490678/125598546-f5e04a76-6d7a-441b-b869-b8fa22852e9d.png)

4 Edit the html templates to your liking, for example [here is a nice trick](https://github.com/openanalytics/shinyproxy/issues/144#issuecomment-487473721) to serve some apps in direct mode and some in iframe mode, if thats something you would like to do.
5. Add css files (to 1col/assets/css), [1](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template/templates/1col/assets/css), [2](https://github.com/openanalytics/containerproxy/tree/master/src/main/resources/static/css), [3](https://github.com/openanalytics/shinyproxy/tree/master/src/main/resources/static/css)
6. Add images for the apps and the favicon (to 1col/assets/img)
7. Add `template-path: ./templates/1col` to `application.yml` (right under `proxy:`)
8. Redeploy Shiny Proxy stack: `cd shinyproxy-docker-swarm-demo/`, `export APP_DOMAIN=app.example.com` and `docker stack deploy -c shinyproxy.yml shinyproxy`
9. Enjoy! 🚀
