### ISSUE TITLE
No authentication + app in an iframe leads to producing number of docker containers

### ISSUE THREAD

**Issue by spokowodza** [openanalytics/shinyproxy#314]
Hello, 
I would like to start with big thank you to all openanalytics team for such a great tool.

I have some problem with shinyproxy. Our internal shiny application works on the server with shinyproxy (address1). There is no authentication set there `authentication: none`. If I go directly to adress1, everything works fine. Each person entering addres1 gets 1 docker container. But if I put address1 as an iframe on some other webpage (address2), just for example:

```
<html>
<iframe src="http://address1/app_direct/myapp" width="100%" height="100%" title="iframe"></iframe>
</html> 
```
and I go to address2, now app starts very slowly and I can see producing number of containers on my server what leads to  overloading server very fast. 

I also tried with 
`src="http://address1/app/myapp"` or `src="http://address1"` + setting landing-page in shinyproxy configuration
I have no idea how I can fix it. Could you please help me?

All the best !

**Comment by LEDfan** [comment]
Hi @spokowodza 

This is a very similar issue as in #305, please have a look at the comment I just posted [in that issue](https://github.com/openanalytics/shinyproxy/issues/305#issuecomment-889849259).

**Comment by spokowodza** [comment]
Hi @LEDfan 
Thanks a lot !
