### ISSUE TITLE
header X-Content-Type-Options: nosniff not customizable

### ISSUE THREAD

**Issue by nbbn** [openanalytics/shinyproxy#317]
Hi,
I noted that header `X-Content-Type-Options: nosniff` is present in Shinyproxy responses.
That's nice, but I also add this header on proxy, therefore I would like to turn it off.
Unfortunately, I don't see an option for this.

BTW: it is a little connected to #254, according to it this header was added silently in version 2.4.x. Maybe we could add some switch for it in application.yaml? BTW, I would love to have also some other headers like CSP, X-XSS-Protection, Cache-Control, etc. customizable.

Or maybe I miss something in configuration?
Thanks,
Jakub

**Comment by LEDfan** [comment]
Hi

It's currently indeed not possible to tweak these headers. What you could do is to configure the proxy to remove the `X-Content-Type-Options` header. For example for nginx, you can use:

```
proxy_hide_header X-Content-Type-Options;
```

Nevertheless, I understand that it would be useful to configure the headers a bit more. 
Do you think it would make sense to have one property that disables all headers set by ShinyProxy and the another property in ShinyProxy where you can specify all your customs headers? For example:

```yaml
proxy:
  disable_security_headers: true
  add_response_headers: 
   - "myHeader: myValue:
   - etc
```

BTW if you would end up with a working CSP policy (or any other useful header), could you please share this with us? I did not have the time to dig into how those headers could secure ShinyProxy, though it could be very interesting to have these.

**Comment by kabbz** [comment]
Hi, I guess this issue affected my work, I've changed the default html, so I use French character, but I'm having issue with the response because shiny proxy is using the default header  **Content-Language: en-US**

**Comment by LEDfan** [comment]
Hi, today we release ShinyProxy 3.0.0, in which it is now possible to customize these headers, please have a look at the documentation: https://shinyproxy.io/documentation/configuration/#disable-no-sniff-header
