### ISSUE TITLE
Deployment Option for Reading HTTPOnly Cookie

### ISSUE THREAD

**Issue by saikatmitra71** [openanalytics/shinyproxy#321]
I'm trying to read HTTPOnly cookie from shiny application and add some rules based on it. I've tried session$request$HTTP_COOKIE which works fine in rstudio, but fails at shiny server as it drops some HTTP headers. I've tried ShinyProxy with rocker/shiny-verse docker image, it fails too.

Is there any way to achieve the functionality with some other docker image? Any kind of guideline would be very much helpful.

**Comment by tverbeke** [comment]
Hi @saikatmitra71 There is no need to use Shiny server with ShinyProxy. The intended use is to use a Docker image with R and the shiny package. See the explanations at https://www.shinyproxy.io/documentation/deploying-apps/ Maybe that helps?

**Comment by LEDfan** [comment]
Hi @saikatmitra71 

Since your problem is solved now, I'm closing this issue. Feel free to open a new issue if you encounter any problem.
