### ISSUE TITLE
Documentation improvement: easy edit systemd overrides

### ISSUE THREAD

**Issue by burgerga** [openanalytics/shinyproxy#326]
In https://www.shinyproxy.io/documentation/getting-started/#docker-startup-options it is suggested that 
>  one can create a file /etc/systemd/system/docker.service.d/override.conf

However this directory might not exist, so I wasn't sure if the instructions were applicable to my Manjaro Linux installation. So an easier approach that works for all systemd systems is to use `sudo systemctl edit docker`, this will create the appropriate directories and opens an override file for editing; easy and foolproof ;)

PS I also don't see a difference between the contents for Ubuntu and CentOS/RHEL

**Comment by LEDfan** [comment]
Hi

Thanks for the suggestion. In practice, I'm also using this edit command, but I never updated the docs.
The docs are fixed now and will soon be updated online.
