### ISSUE TITLE
Can't start shinyproxy on Java 16

### ISSUE THREAD

**Issue by burgerga** [openanalytics/shinyproxy#327]
Related to #4, with `openjdk version "16.0.2" 2021-07-20` I get 

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalAccessError: class org.springframework.ldap.core.support.AbstractContextSource (in unnamed module @0x4fcd19b3) cannot access class com.sun.jndi.ldap.LdapCtxFactory (in module java.naming) because module java.naming does not export com.sun.jndi.ldap to unnamed module @0x4fcd19b3
```

As suggested, running `java --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED -jar shinyproxy-2.5.0.jar` works, however, https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above#spring-ldap suggests that this is fixed in spring-ldap 2.3.4 which is available in [spring-boot v2.5.0](https://github.com/spring-projects/spring-boot/releases/tag/v2.5.0)

**Comment by burgerga** [comment]
(added required spring boot version to description)

**Comment by LEDfan** [comment]
Hi

ShinyProxy 2.6.0 (which will be released very soon), supports both JDK 16 and 17.

**Comment by LEDfan** [comment]
[ShinyProxy 2.6.0](https://shinyproxy.io/downloads/#260) (ContainerProxy 0.8.10) has now been released, which is compatible with JDK 16 and 17.

Thanks for opening the issue.
