### ISSUE TITLE
Add authorisation callback URL to the documentation of social authentication

### ISSUE THREAD

**Issue by nuno-agostinho** [openanalytics/shinyproxy#331]
I think this should be available in the documentation. Thanks!

**Comment by LEDfan** [comment]
Thank you for the suggestion, in the mean time the social authentication backend has been removed. Instead, you should now use the generic openid backend. We have extended the OpenID documentation (https://shinyproxy.io/documentation/configuration/#openid-connect-oidc) and it should now be easier to start using it.
