### ISSUE TITLE
2.6.0 'InResponseToField doesn't correspond to sent message' error

### ISSUE THREAD

**Issue by zacseas** [openanalytics/shinyproxy#335]
After upgrading from 2.5.0 to 2.6.0, using the same application.yml, saml authentication with azure AAD from aks cluster with Load Balancer is not more working, getting 'InResponseToField doesn't correspond to sent message' error.
This is my configuration in application.yml (same of the one I used with 2.5.0, that is working)
...
  saml:
    idp-metadata-url: https://login.microsoftonline.com/YYYYYYYYYYY/FederationMetadata/2007-06/FederationMetadata.xml
    app-entity-id: api://XXXXXXXXXXXXX
    app-base-url: https://ZZZZZZ.westeurope.cloudapp.azure.com
    force-authn: true
    lb-server-name: ZZZZZZ.westeurope.cloudapp.azure.com
    lb-scheme: https
    roles-attribute: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
    logout-url: https://ZZZZZZ.westeurope.cloudapp.azure.com/logout-success
  container-backend: kubernetes
....

**Comment by LEDfan** [comment]
Hi

This is caused by a change in the default value for the SameSite cookie policy of ShinyProxy. Although this was an important change, this unfortunately breaks SAML. You can fix this by following the steps explained here https://shinyproxy.io/documentation/configuration/#samesitecookies-and-saml

**Comment by zacseas** [comment]
when configuring application.yml with:

proxy:
  same-site-cookie: None
  secure-cookies: true

I get:
2021-11-22 12:05:12.415  WARN 1 --- [           main] ication$$EnhancerBySpringCGLIB$$3ff25ba8 : WARNING: Invalid configuration detected: same-site-cookie policy is set to None, but secure-cookies are not enabled. Secure cookies must be enabled when using None as same-site-cookie policy 

And saml authentication doesn't work.

I've tried with a different configuration:
server:
   secure-cookies: true
proxy:
  same-site-cookie: None

but same result.

**Comment by zacseas** [comment]
OK it works with:
server:
  secure-cookies: true
proxy:
  same-site-cookie: None

secure-cookies is a server parameter, so it would be better to correct the documentation:

 https://shinyproxy.io/documentation/configuration/#samesitecookies-and-saml

Thanks a lot !

**Comment by LEDfan** [comment]
Thanks for letting us know that it works now. Indeed the documentation was incorrect here, this is now fixed: https://shinyproxy.io/documentation/configuration/#samesitecookies-and-saml
