### ISSUE TITLE
Shinyproxy authentication by supabase.io

### ISSUE THREAD

**Issue by JorisGanne** [openanalytics/shinyproxy#336]
Hello everyone,

I'm quite new to the programming world but fascinated by the whole shiny framework. At this moment I am experimenting with shiny apps in different ways. I like to use tools developed by startups instead of using the established version. Therefore, I have the following question: is it possible to integrate the authentication module of supabase with shinyproxy. And if the answer is yes, which settings do I need to adapt?
Thank you all in advance!

**Comment by LEDfan** [comment]
Hi

I looked into the documentation of supabase, and I don't see any way of integrating it with ShinyProxy. I think the main idea of supabase is to have authentication in apps built using supabase and not external apps. Therefore this requires additional development effort before we can support this. However, looking at the system it won't be very easy to support it in ShinyProxy.

**Comment by JorisGanne** [comment]
Thank you for your point of view. I will look for another authentication system.
