### ISSUE TITLE
embedding apps on cross-sites

### ISSUE THREAD

**Issue by jaysnm** [openanalytics/shinyproxy#345]
Much appreciations to shinyproxy maintainer team. Improvements and new features in version 2.6.0 are splendid. I have used shinyproxy in production for about two years now and the journey has been fantastic.

At the moment, our current need is to embed apps into other websites. I have tried the example on [08-api-embedded-app](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/08-api-embedded-app) taking notes on [how-to-embed-shinyproxy-using-an-iframe-](https://shinyproxy.io/faq/#how-to-embed-shinyproxy-using-an-iframe-on-a-different-domain) but I don't seem to make any progress. From `requestDump` and browser request inspection, the problem seem to be  `CORS` related. My `application.yml` has 
```
server:
  secure-cookies: true
  frame-options: disable
proxy:
  same-site-cookie: None

```
and both shinyproxy and `index.html` are served using HTTPS. I have tried setting `Access-Control-Allow-Origin` on `ajax request` but errors persist as shown in screenshots below.

```
headers: {
   "Access-Control-Allow-Origin": "*",
   'Content-Type': 'application/json',
}
```

![shinyproxy-request-dump](https://user-images.githubusercontent.com/20385376/145255310-858dde84-5978-4cab-a271-a260355cce79.png)

![cors-denied](https://user-images.githubusercontent.com/20385376/145255328-7ff7e60a-83e7-4b72-914a-61bcbc28f091.png)

**Comment by LEDfan** [comment]
Hi, thanks for the kinds words!

If I understand correctly you are trying to access the API from another domain? This should work, with the given settings. However, it seems like you don't send any cookies for authentication with the request (both in the Firefox screenshot and in the request dump I see no cookies).
You first have to authenticate with the API (using the login form or OAuth2 etc) and then send either a cookie or Bearer token with the request.

**Comment by jaysnm** [comment]
Thanks Tobia for reverting. To set the context clear, I'm running shinyproxy on `https://domain1.xyz` and running `index.html` of [08-api-embedded-app](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/08-api-embedded-app) on `https://domain2.xyz`. With `hostURL` and `proxySpecId` appropriately changed, `launchProxy` event fails with above errors. 

I'm curious whether Authentication header is required when authentication is disabled with `authentication: none`. This is the setting I have on my `application.yml`.

**Comment by LEDfan** [comment]
Hi

Sorry for the late follow-up.

> I'm curious whether Authentication header is required when authentication is disabled with authentication: none. This is the setting I have on my application.yml.

No, this should not be required, I seem to have misunderstood the problem in my previous post.

The problem you are facing is indeed because of CORS. There is a check in Spring that validates whether CORS is enabled. By default this is not the case and thus Spring shows an error message. Unfortunately, I don't think there is a workaround using `application.yml` properties or by configuring a reverse proxy.
The only solution I see is that we add a configuration option to ShinyProxy.

However, in the meantime, if this issue is about embedding ShinyProxy apps, there is a different approach, which I believe is more suited. You should be able to just use an iframe to embed the app and the ShinyProxy code will make sure to properly startup the application. For example:

```html
<!DOCTYPE html>
<html>
<head lang="en">
    <title>Example: Using API to embed an app</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <style>
        body ,html {
            padding: 0;
            margin: 0;
            height: 100%;
            width: 100%;
            overflow: hidden;
        }
        iframe {
            height: 100%;
            width: 100%;
            border: none;
        }
    </style>
</head>
<body>
    <iframe frameborder="0" src="http://localhost:8080/app/06_tabsets"></iframe>
</body>
</html>
```

Note that you will still need `same-site-cookie: None`

**Comment by jaysnm** [comment]
Hello Tobia

Thank you for reverting and apologies for coming to party late. The shared example approach is clear, works and solves the problem.

**Comment by LEDfan** [comment]
Hi

I'm happy to hear this solved you problem, therefore I'll close this issue. Feel free to open a new issue if you encounter any issue.
