### ISSUE TITLE
Are there any plans to support docker's inter-process communication?

### ISSUE THREAD

**Issue by tbrittoborges** [openanalytics/shinyproxy#348]
Shinyproxy works excellent overall, but handling data loading (without a database) is a problem. I found an [old question](https://support.openanalytics.eu/t/general-usage-question/371) that mentions that shinyproxy does not support `docker -ipc`. Is that still current? Sharing memory between containers could help with the data load times issue. Are there any plans to support that? 

Thank you for developing such a great framework!

**Comment by LEDfan** [comment]
Hi

At time of writing this is indeed not supported in ShinyProxy. We also don't have any plans for it currently, although I think it takes relatively low effort to implement it. I'll keep this issue open as a feature request and will consider it for one of the next releases.

**Comment by algo-se** [comment]
I'd like it : )

**Comment by LEDfan** [comment]
Hi, this is now part of ShinyProxy 3.1.0, which we released today. See https://shinyproxy.io/documentation/configuration/#docker-ipc .  Thanks again for your suggestion!
