### ISSUE TITLE
'No Session ID Found' when use another browser or after the session expired

### ISSUE THREAD

**Issue by keqiang** [openanalytics/shinyproxy#35]
I'm using the latest ShinyProxy 1.0.2 and is experiencing an issue where after opening an app in one browser and then try using another browser to access the same app, the page only shows 'No session ID found'.

After a while, I guess when the session does expire, even using the original browser will have the same issue.

**Comment by PlasmaPower** [comment]
If both browsers are signed into the same user, this would definitely happen. I'll work on a solution.

**Comment by PlasmaPower** [comment]
#36

**Comment by PlasmaPower** [comment]
If the session expires though, that's intended behaviour. That means you have no authentication, so it makes since that you can't access your app instance. However, I am working on another method of authentication that wouldn't expire.

**Comment by PlasmaPower** [comment]
If the session expires though, that's intended behaviour. That means you have no authentication, so it makes since that you can't access your app instance. However, I am working on another method of authentication that wouldn't expire.

**Comment by keqiang** [comment]
Hi @PlasmaPower ,

Thanks for the fast response and fix.  I understand when the session expires, user should have no access unless they are logged in. But in this case, I'm logged back in, but still see the 'session id not found' error. I guess this is the same for using another browser because the session ID changed? But this will still be an issue because user then lose access to that app until the container heartbeat time out is reached, which in my case has been set to a very long time.

**Comment by PlasmaPower** [comment]
If you have another valid session token, then yes, you should get access (and the pull request fixes that).

**Comment by keqiang** [comment]
I saw the changes you made and looking forward to it being merged.

**Comment by keqiang** [comment]
Another question is when I logged out my account, I noticed the containers were killed. Is this the desired behavior?

**Comment by PlasmaPower** [comment]
Looking at the code, it's intentional, but it may simply be that the author(s) didn't consider multiple sessions per user.

**Comment by fmichielssen** [comment]
Hi @keqiang , @PlasmaPower ,

The original design was indeed to limit each user to one session per app.
The fact that a user could access the same proxy from multiple browsers, was unintentional.
Looking at the PR, it makes sense to me to remove this limitation.

However, some more changes would be needed, e.g. to the logout and heartbeat code, so that the proxy is released only when no active sessions remain.

**Comment by keqiang** [comment]
@fmichielssen 
Yea, I think it would make more sense that heartbeat setting is honored no matter if the user is logged in or logged out. I feel killing all the containers once the user logged out might not be intuitive.

**Comment by PlasmaPower** [comment]
My pull request has been updated to change the logout and heartbeat code. I've added a configuration option to change the logout behavior, `shiny.proxy.stop-on-logout`. Should it default to true or false?

**Comment by PlasmaPower** [comment]
This issue (or at least part of it) just appeared in our environment. I believe it was caused by a session token expiring, then getting renewed to a new value. However, I'm not sure.
