### ISSUE TITLE
Usergroups not visible inside pods for some users

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy#350]
Hello,

We have seen an issue where the usergroups to which a user is assigned to are not visible inside the pod. This does not happen with all the users though. For example, when I check the pod started by some other users, I can see the usergroups the user is part of but when I check the pod started by me, I notice that its blank.
Do I need to something to see the groups I am part of?
Also, I can access shinyproxy application but its just that the groups are not visible. We are running on version 2.6.0.

**Comment by LEDfan** [comment]
Hi

I'm not sure what is causing this issue. However, I suspect that the pod-patches may cause this. The user groups are passed to the pod using environment variables, and it could be that you are overriding these values.
Could you share the configuration of an app that is having this issue?

**Comment by aupadh12** [comment]
Hi,

How can we override the env variable SHINYPROXY_USERGROUPS in the yaml file?

**Comment by aupadh12** [comment]
Hi,

Closing this issue as the issue is fixed by limiting the security groups which needs to be allowed to pass for a specific application.
