### ISSUE TITLE
ShinyProxy WebURL QueryString to ShinyApp

### ISSUE THREAD

**Issue by littlenetcoder** [openanalytics/shinyproxy#351]
Hi,
I have built an custom docker image using official ShinyProxy (2.6.0) image
`FROM openanalytics/shinyproxy:2.6.0
COPY application.yml /opt/shinyproxy/application.yml
EXPOSE 8088`

I have accessed ShinyProxy URL with querystring like  "abc=xyz". And i could see all of my ShinyApps under http://localhost:8088/?abc=xyz. But whenever I tried to launch any ShinyApp i am loosing my query string and not able to access them inside my app. 

Is there anyway to get that information ?
Also there is another issue which might cause problem is whenever i clicked on Navbar link (Title) from ShinyApp that time also it redirects to http://localhost:8088
My application.yml is standard one.

'proxy:
  title: Hey Shiny Proxy !!
  port: 8088  
  authentication: openid   
  docker:      
      url: http://host.docker.internal:2375
      #net: "host"
      cert-path: /home/none
      port-range-start: 20000
  #default-max-instances: 1
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    #max-instances: 1

  - id: shinyapp
    display-name: Demo application from container
    description: Demo App
    container-cmd: ["R", "-e", "shiny::runApp('/root/testApp')"]
    container-image: shinyapp-abc  
   #max-instances: 1 

server:
  forward-headers-strategy: native
  secureCookies: false

logging:
  root: debug 
  file:
    shinyproxy.log'

**Comment by LEDfan** [comment]
Hi

Currently ShinyProxy does not pass-though the query-strings to the app. Also, when you click on a link the querystring will not be preserved. 

When we add  support for Shiny bookmarks (https://github.com/openanalytics/shinyproxy/issues/300), this should be supported.  We still want to support this, but we currently don't have a planned date for it.

**Comment by LEDfan** [comment]
Hi

Starting with ShinyProxy 3.0.0, any querystring, subpath or hash path added to the URL will be passed down to the app URL. Therefore, the above should work.

BTW, you can change the template of the navbar to change the behavior of the links and buttons, see https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template
