### ISSUE TITLE
Im not getting logs for 500 error in portal

### ISSUE THREAD

**Issue by wallystart** [openanalytics/shinyproxy#354]
Hi, i have a 500 error in portal but it doesn't logging with stdout and stderr. I'm sure that is an error om R code but i need details

Portal error when i start an app

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/25191329/156846996-c298cb51-c71f-451f-bd16-4c1d89a8b49f.png)

And in my folder i have logs of others apps, in application.yml i have set the path and it works fine for those apps except for this one gets 500

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/25191329/156847403-083d1d34-2507-427e-a759-f37f45eb6c12.png)

![image](https://user-images.githubusercontent.com/25191329/156848457-46abe6d5-eb3b-4823-979f-95c6e2f2c5f8.png)

Too, i tried with manual docker run but i got a listening and no errors

Regards

**Comment by LEDfan** [comment]
Hi

ShinyProxy only collects the logs of apps that are successfully started. I understand this is not very helpful in your case.

> Too, i tried with manual docker run but i got a listening and no errors

This is a good idea. On what port is your application listening? If it is different than the default 3838, you have to specify it in your configuration:

```yaml
container-port: 4242
```
