### ISSUE TITLE
Using OIDC Access Token in index.html

### ISSUE THREAD

**Issue by nik-humphries** [openanalytics/shinyproxy#356]
Scenario:
I want to use a custom navbar that interfaces with an API and therefore requires an access token to use. I need to insert this into all of the .html files in a script as follows

```js
<script>		
document.querySelector('yyy').config = {
			accessToken: 'xxx',
			ServiceEndpoint: 'https://zzz-api.com'
		}
</script>
```

The token doesn't appear to be stored in the local storage or equivalent and I cannot figure out if it is exposed in any other way where I can reference it in the above js.

Question:
Is there a way to access the access token, or will I have to make changes to the underlying Java to expose it?

EDIT
---
Been advised that passing token from a server managed process to a front end is a bad idea!

**Comment by LEDfan** [comment]
Hi

> Been advised that passing token from a server managed process to a front end is a bad idea!

Indeed, I agree with this. In any case, you can get some properties of the OIDC user using:

```html
<div>
    Hello your sub is: <span th:text="${@userService.currentAuth.principal.attributes['sub']}"></span>
</div>
```

**Comment by nik-humphries** [comment]
Thanks, shame I can't use it!
