### ISSUE TITLE
Access to a mysql database on host from a dockerized shinyproxy apps 

### ISSUE THREAD

**Issue by RozennGZ** [openanalytics/shinyproxy#357]
Hi,

I have a working shinyproxy app that requires a connexion to a mysql on **host**. I am using a custom bridge network (sp-net). In the shiny webapp, I call the sql  database using dbconnect, with the host as the IP adress of the SQL server and the correct port. 

The app is deployed without any issues, but the SQL connexion failed (I can see the error in the R log : Warning: Error in : Failed to connect: Can't connect to MySQL server on IP '*********' (110)). 

When the app is deployed on another server (different than the server which host the sql database), everything is working perfectly. Therefore the issue seems to access to the sql on the host from the container. I already tried the solution suggested in #260 to add "container-volumes: ["/var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock"]" but it doesn't solve my problem.

Here is my docker compose : 

version: '3.5'

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
     - shinyproxy
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - "8080:8080"
    networks:
      - sp-net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  shinyproxy:
    image: ******/shinyproxy:v2.001
    depends_on:
      - myapp
    container_name: shinyproxy
    expose:
      - 8080
    volumes:
      - ./apps/shinyproxy/application.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs

    networks:
      - sp-net
  myapp:
    image:  ******/***********

networks:
  sp-net:
    name: sp-net

My shinyproxy yml : 

proxy:
  hide-navbar: true
  port: 8080  

  container-wait-time: 30000
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-log-path: /container-logs
  
  authentication: none
    docker:
      internal-networking: true 
  specs:
  - id: myapp
    display-name: shinyapp
    container-cmd: ["R", "-e", ""shiny::runApp(port=3838,host='0.0.0.0')"]
    container-image: ******/***********
    container-network: sp-net

logging:
  file:
    /log/shinyproxy.log
    
spring:
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB

**Comment by LEDfan** [comment]
Hi

Is the mysql server run as a docker container as well? If not, you are not required to use a docker network and should be able to directly reach the mysql server on its IP address. 
In both cases I would try to debug this by launching the Shiny app. Next login into the container using `docker exec` and try reaching the MySQL server using `ping` or `telnet`.

**Comment by LEDfan** [comment]
Hi, this issue was opened a long time ago and I think that the answer above should do the trick. Therefore, I'm going to close this issue. If you are still facing an issue, please re-open the issue or open a new one.
