### ISSUE TITLE
dash app developed in jupyter

### ISSUE THREAD

**Issue by BiernatPiotr** [openanalytics/shinyproxy#359]
Hi,

_I'm repeating my issue from jupyter-notebook-demo, as nobody really looks there._

do you have any idea, how to preview dash app developed in jupyter notebook in shinyproxy? When I try to run app from notebook I have no idea how to access it.

app.run_server(mode='external', host="127.0.0.1", port=8049)
Dash app running on http://127.0.0.1:8049/

When I run a shiny app in RStudio in shinyproxy and try to preview it there is info about address where app is running from R like:
Listening on http://127.0.0.1:6331

And new tab appears with some specific address like:
https://mydomain.com/app_direct_i/rstudio/_/p/ccae08ce/

Is there any way to get such an address for dash app?

**Comment by LEDfan** [comment]
Hi

I think this JupyterLab extensions does exactly what you want: https://github.com/plotly/jupyter-dash
It provides a similar workflow as with RStudio.
Please let us know if this extension is useful, we could then update the README of the jupyter demo.
