### ISSUE TITLE
The OpenID user's token is not refreshed

### ISSUE THREAD

**Issue by adellam** [openanalytics/shinyproxy#365]
Hi all, we use `openid` to authenticate the shinyproxy users, and some apps are trying to use it to access other services of our infrastructure.
But the token is never refreshed, so the authorization to those services fail after the token is expired.

I see that there's a `proxy.saml.max-authentication-age` options, but there's no equivalent for `openid`.
Is it possible to add a similar option?

**Comment by LEDfan** [comment]
Hi

If I understand correctly, you are using the access token passed to the container to access other services? Indeed this access token will not get refreshed. Instead, you'll have to pass the refresh token as an env variable to the container and use that to refresh the token yourselves. See https://github.com/openanalytics/containerproxy/issues/47#issuecomment-1012996052 for an example.

**Comment by adellam** [comment]
I guess the issue can be closed.
