### ISSUE TITLE
ShinyProxy Dash Compability issue

### ISSUE THREAD

**Issue by nsyed4** [openanalytics/shinyproxy#366]
Hi, 

I ran Dash demo application https://github.com/openanalytics/shinyproxy-dash-demo Dash 1.19.0 on ShinyProxy 2.5.0 it worked. 

Apart from the above versions, I checked with ShinyProxy 2.5.0 & Dash 1.21.0, Dash 2.0.0, Dash 2.3.0. None of these worked.
Similarly, I checked with ShinyProxy 2.6.0 and Dash 2.0.0 and this didn't work as well.

We are using Dash 2.3.0 and we need ShinyProxy to work with it. Can someone please advice? In all the above version combinations that I ran, I get the same error:

Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import dash
  File "/usr/local/lib/python3.8/dist-packages/dash/__init__.py", line 5, in <module>
    from .dash import Dash, no_update  # noqa: F401,E402
  File "/usr/local/lib/python3.8/dist-packages/dash/dash.py", line 18, in <module>
    from werkzeug.debug.tbtools import get_current_traceback
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/usr/local/lib/python3.8/dist-packages/werkzeug/debug/tbtools.py)

**Comment by LEDfan** [comment]
Hi

I'm not sure whether the error you get is related to ShinyProxy. To me it seems that python has a problem with importing the dash module. Is this the full error you get?

You could also look here https://github.com/openanalytics/shinyproxy-dash-demo/issues/3 for some tips on using ShinyProxy with Dash 2.0. I'll update the docs also for using ShinyProxy with Dash 2.0
