### ISSUE TITLE
Upgrade to 2.6, now select button in Shiny doesn't work

### ISSUE THREAD

**Issue by janzjos** [openanalytics/shinyproxy#374]
Hello - had been running shinyproxy 2.2 with an Shiny App deployed.  Now upgrade to shinyproxy 2.6 and unable to select with button.  Any thoughts on why?  Here are my current libraries:

`# basic shiny functionality
RUN R -e "install.packages(c('shiny'), repos='http://cran.us.r-project.org')"

# to install specific versions: 
RUN R -e "install.packages('devtools')"
RUN R -e "require(devtools)"

RUN R -e "devtools::install_version('shinydashboard', version = '0.7.1', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('rmarkdown', version = '2.8', repos = 'http://cran.us.r-project.org')"
#RUN R -e "devtools::install_version('V8', version = '3.4.2', repos = 'http://cran.us.r-project.org')"
RUN R -e "install.packages(c('V8'), repos='http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinyjs', version = '2.1.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('dplyr', version = '1.0.6', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('sass', version = '0.3.1', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('leaflet', version = '2.0.3', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('htmltools', version = '0.5.1.1', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('httr', version = '1.4.2', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('jsonlite', version = '1.7.2', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('reactR', version = '0.4.4', repos = 'http://cran.us.r-project.org')"

RUN R -e "devtools::install_version('fresh', version = '0.2.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinydashboardPlus', version = '2.0.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('odbc', version = '1.2.2', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinyBS', version = '0.61', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinyWidgets', version = '0.4.3', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('echarts4r', version = '0.2.3', repos = 'http://cran.us.r-project.org')"

RUN R -e "devtools::install_version('lubridate', version = '1.7.10', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('DT', version = '0.18', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('tidyverse', version = '1.3.1', repos = 'http://cran.us.r-project.org')"
`

**Comment by mnazarov** [comment]
Hi @janzjos I am afraid your description is not enough for understanding what goes wrong. Could you please be more specific about what doesn't work - what do you mean by "unable to select with button"? - and whether you see any error messages? If you could provide (at least a part of) the shiny app that fails it would also be helpful. You could also check if running the app outside of shinyproxy (still from the container) works
