### ISSUE TITLE
Updating pathname in dash config stops container from starting

### ISSUE THREAD

**Issue by mathlete76** [openanalytics/shinyproxy#383]
I can successfully run the dash demo by pulling the image from dockerhub and adding to the application.yml.

I have my own dash app I'd like to deploy, but after several days of trying to get it to work I am now down to a minimal dash app, and it is clear that trying to set the pathname prefix causes the container to fail to start.

If I miss out the app.config.update for the prefixes the container will start, but the app doesn't get past loading. I can see in 'sources' in the chrome devl panel that the prefix has not been set and that is expected.

I have checked the container logs and if I output the SHINYPROXY_PUBLIC_PATH attribute to there I can see it is picking up correctly.

So I tried simply setting the prefix manually to that value, and this still causes the container to fail to start.

I then tried different versions of dash, but to no avail. Whenever I try to set the prefix the container will fail to start and without it the app doesn't get past loading.

As a last gasp attempt I cloned the github demo and manually built the same image that I had pulled from dockerhub, and it also fails to start.

Can anyone suggest some settings/versions that will provide a working dash app inside shinyproxy.

**Comment by LEDfan** [comment]
Hi

Some changes are required for newer versions of Dash, please have a look at this pull request for more information: https://github.com/openanalytics/shinyproxy-dash-demo/pull/6

**Comment by LEDfan** [comment]
Hi, I think this question has been answered, therefore I'll close this issue, please open a new issue or re-open this issue if you are still experiencing an issue.
