### ISSUE TITLE
ShinyProxy Nginx Login Screen Loop

### ISSUE THREAD

**Issue by spepperkumc** [openanalytics/shinyproxy#387]
I followed the guide here (https://www.shinyproxy.io/documentation/security/#https-ssl--tls) to setup ssl using Nginx, but when using SAML or simple authentication I am stuck in an endless login screen loop. In simple login mode after entering my information I am sent to a new login screen telling me to 'Please sign in:' .

Any Ideas where I went wrong?

Here are some changes I made to the shinyproxy yml for ssl to work

```
proxy:
   port: 8085
   bind-address: 127.0.0.1

server:
    useForwardHeaders: true
    forward-headers-strategy: native
```

 Below is my relevant Nginx config

```
server {
  listen                443 ssl;
  server_name          shinyproxy.yourdomain.com;
  access_log            /var/log/nginx/shinyproxy.access.log;
  error_log             /var/log/nginx/shinyproxy.error.log error;
  #underscores_in_headers on;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

  ssl_certificate       /etc/ssl/certs/yourdomain.com.cer;
  ssl_certificate_key   /etc/ssl/private/yourdomain.com.key;

   location / {
       proxy_pass          http://127.0.0.1:8085;

       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_read_timeout 600s;

       proxy_redirect    off ;
       proxy_set_header  Host              $host;
       proxy_set_header  X-Real-IP         $remote_addr;
       proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
       proxy_set_header  X-Forwarded-Proto $scheme;
      # proxy_pass_request_headers      on;
     }

}
```

**Comment by LEDfan** [comment]
Hi

I'm unable to tell exactly what the problem is, however, it is probably related to cookies. ShinyProxy stores a session in a cookie and sends this cookie with every request. If this cookie is not working properly, ShinyProxy is unable to identify you and store the login information.

Did you change anything regarding cookie settings? (e.g. same-site-policy, secure cookies).
Can you try opening the developer console of your browser and reloading the page and look for warnings?

**Comment by spepperkumc** [comment]
Firefox, Edge, and Chrome only report the ico error below in the console.
GET https://shinyproxy.yourdomain.com/favicon.ico 500 (Internal Server Error)

I didn't change anything related to cookies, all I did was follow the guide to setup Nginx.
The server worked fine as http but not after the Nginx reverse proxy was added which is odd.

**Comment by spepperkumc** [comment]
Figured it out, my usage-stats-url: was pointing to an deleted database. Some reason this kept looping the login process.

**Comment by tverbeke** [comment]
Thanks for sharing the origin of the issue!
