### ISSUE TITLE
White page for AngularJS app in ShinyProxy

### ISSUE THREAD

**Issue by DidierMurilloF** [openanalytics/shinyproxy#389]
Hi, I am trying to deploy an AngularJS app on ShinyProxy, the docker container starts well, but I got a white page for the app. Maybe I need some advanced configuration in shinyproxy to properly deploy this kind of app, but I have no idea how to move forward. 

![exlibris](https://user-images.githubusercontent.com/79462830/199339924-4b8ddec5-1efb-4c69-bfd5-2748f1cc65b1.JPG)

**Comment by LEDfan** [comment]
Hi

What's happening here is that ShinyProxy loads the app on a subpath of the shinyproxy URL. For example, the app will be loaded on `shinyproxy-demo.local/app_proxy/<id>/`. However, your Angular app tries to load the CSS and JS files on the root path of shinyproxy (i.e. `shinyproxy-demo.local`), but instead it should load these relative to the root of the app on shinyproxy (i.e. `shinyproxy-demo.local/app_proxy/<id>/`). You should either modify the HTML code to load the assets relative to the HTML file or use the `SHINYPROXY_PUBLIC_PATH` environment variable to load the files with an absolute url.

**Comment by LEDfan** [comment]
Hi, I think this question has been answered, therefore I'll close this issue, please open a new issue or re-open this issue if you are still experiencing an issue.
