### ISSUE TITLE
Docker secrets when using the docker swarm backend

### ISSUE THREAD

**Issue by MarniTausen** [openanalytics/shinyproxy#390]
I can't find any instances or settings in the documentation which allow for using a docker secret when you are using the docker swarm backend.

There seems to be no equivalent to using the '--secret' flag when starting the container as a service.

Related issues: https://github.com/openanalytics/containerproxy/issues/9 are still open, or https://github.com/openanalytics/shinyproxy/issues/191 use weird indirect approaches.

What is the recommend way to handle secrets like this when not using kubernetes, where it looks to be supported?

**Comment by LEDfan** [comment]
This has been implemented in ShinyProxy 3.0.0, please check out the documentation: https://shinyproxy.io/documentation/configuration/#docker-swarm-secrets
