### ISSUE TITLE
请问有什么办法让ShinyProxy重启时不影响正在运行的应用？

### ISSUE THREAD

**Issue by iBelen** [openanalytics/shinyproxy#392]
以下配置了 但是参数没生效？
`proxy:
    stop-proxies-on-shutdown: false
    recover-running-proxies: true
    recover-running-proxies-from-different-config: true`

What can I do to make ShinyProxy restart without affecting running applications?
The following parameters do not take effect 
Sorry My English is not good.

**Comment by tverbeke** [comment]
Do you deploy on Kubernetes? If yes, you need the ShinyProxy operator to avoid downtime for running applications. On a Docker deployment this is not possible.

**Comment by LEDfan** [comment]
In addition to the above, if you are not using Kubernetes, you could use app recovery (https://shinyproxy.io/documentation/app-recovery/).
Since I think this question has been answered, I'll close this issue, please open a new issue or re-open this issue if you are still experiencing an issue.
