### ISSUE TITLE
Bootstrap Version

### ISSUE THREAD

**Issue by nik-humphries** [openanalytics/shinyproxy#393]
I've been using some of newer features of bootstrap for changing the lists of applications into cards. Cards aren't available in bootstrap 3.4.1, so have had to update bootstrap on the java file.

I've done this by adding the following to `pom.xml`
```xml
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>bootstrap</artifactId>
			<version>5.0.2</version>
		</dependency>
```
and changing lines 122 and 123 of `BaseController.java` to 

```java
		map.put("bootstrapCss", "/webjars/bootstrap/5.0.2/css/bootstrap.min.css");
		map.put("bootstrapJs", "/webjars/bootstrap/5.0.2/js/bootstrap.min.js");
```
from 3.4.1.

This also required me to add in the following to the html templates 
```html
	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<!-- JavaScript Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
```
Although I did this a long time ago so can't remember all the bits that are necessary.

I have 2 questions:
1 - Is this the best way of doing this or am I overcomplicating things as I have to rebuild the java file?
2 - Is there any desire to update SP to be using a newer version of Bootstrap OOTB?

Example card usage included.
![image](https://user-images.githubusercontent.com/20989616/205902421-3c3a76a5-0ad3-47a9-8c28-0d52eb440b44.png)

**Comment by mnazarov** [comment]
Regarding question 1, I think it would be sufficient to replace the lines
```
<link rel="stylesheet" media="screen" th:href="@{${bootstrapCss}}"/>
<script th:src="@{${bootstrapJs}}"></script>
```
in the default template by the links to bootstrap 5 that you pasted without the need to modify the source.

_(alternatively if you've modified the source, you don't need to include the links to css and js manually again since default template includes the lines above which in that case would already load bootstrap 5)_

**Comment by nik-humphries** [comment]
By source are you referring to the source .jar file? 

I would have thought just changing those two bits that you say to be links to the style sheet and .js file would be sufficient, but I just seem to have a memory of it _not working_ for some reason. I'm going to test using a stock SP .jar and changing the stylesheet and script tag and see if that works.
