### ISSUE TITLE
-H fd:// in the systemd unit file doesn't allow to start docker (Fedora)

### ISSUE THREAD

**Issue by malexan** [openanalytics/shinyproxy#40]
I followed [Getting Started](https://www.shinyproxy.io/getting-started/) guide and edited `/lib/systemd/system/docker.service` as recommended: `ExecStart=/usr/bin/dockerd -H fd:// -D -H tcp://127.0.0.1:2375`.

After daemon reloaded and restarted I got an error. Excerpts from `journalctl  -xe`:

```
no sockets found via socket activation: make sure the service was started by systemd
docker.service: Start request repeated too quickly. 
```

In moby/moby#22847 there is a [comment](https://github.com/moby/moby/issues/22847#issuecomment-236318630) that states:

> Docker 1.12 on CentOS no longer uses socket activation, so you need to remove the -H fd:// from the systemd unit file

I don't know is it related to Fedora, but without `-H fd://` docker starts normally and demo apps from ShinyProxy work.

```
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:17 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

 service docker status
Redirecting to /bin/systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-11-27 16:57:02 +04; 20min ago
     Docs: https://docs.docker.com
 Main PID: 21535 (dockerd)
    Tasks: 26 (limit: 4915)
   Memory: 20.5M
      CPU: 5.645s
   CGroup: /system.slice/docker.service
           ├─21535 /usr/bin/dockerd -D -H tcp://127.0.0.1:2375
           └─21543 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout
```

**Comment by e-user** [comment]
It doesn't start because it's missing `-H unix://` which provides `/var/run/docker.sock` and is the default, unless any `-H` option is given explicitly.

**Comment by LEDfan** [comment]
Hi 

This is quite an old issue and in the meantime we have updated our documentation. Therefore I'm closing this issue. Feel free to re-open it if you need more help.
