### ISSUE TITLE
Template Properties

### ISSUE THREAD

**Issue by nik-humphries** [openanalytics/shinyproxy#401]
Now I don't know if I'm missing something obvious here.. but.

For Template Groups, we can pass additional properties `template-groups` then `properties` 
For Apps we can pass additional properties: `specs` then `template-properties` (template-properties)

How do you do this for the overall webpages themselves? i.e. outside of a template group or an app specification. I have a few versions of ShinyProxy being used and would like to conditionally show bits on a navbar configured in the `application.yaml` rather than by using different overall templates. Or is the solution here to have multiple templates and configure it this way?

**Comment by LEDfan** [comment]
Indeed, there is no configuration option specific to ShinyProxy for this. However, you can access the [`Environment`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/Environment.html) class of the Spring framework and use that to read any property from the configuration file. 

For example:

```html
<span th:text="${@environment.getProperty('proxy.title')}"></span>
```

**Comment by nik-humphries** [comment]
Thanks that's great.
