### ISSUE TITLE
Maven Build Fails Due to License

### ISSUE THREAD

**Issue by nik-humphries** [openanalytics/shinyproxy#407]
I see the license had been updated to `Copyright (C) 2016-2023 Open Analytics` from `Copyright (C) 2016-2021 Open Analytics`. This hasn't been reflected in the files though so throws an error on build 

```
[ERROR] Failed to execute goal com.mycila.maven-license-plugin:maven-license-plugin:1.9.0:check (check-copyright-headers) on project shinyproxy: Some files do not have the expected license header -> [Help 1]
```

**Comment by LEDfan** [comment]
Hi, indeed that was a mistake during the release procedure. This will be fixed when we push the code for `3.0.1` which will be released soon.

**Comment by LEDfan** [comment]
I just pushed the code for 3.0.1 and also released that version. This should be fixed now.

**Comment by nik-humphries** [comment]
Can confirm that's fixed it, thank you!
