### ISSUE TITLE
Maven Build of 3.0.0 Missing Main-Class

### ISSUE THREAD

**Issue by nik-humphries** [openanalytics/shinyproxy#408]
Having issues with compiling shinyproxy v3.0.0. After a `mvn -U clean install` (tried maven 3.6.3 and 3.9.0) I'm getting the following error when trying to run it.

I'm using wsl2 with Ubuntu 20.04

```
no main manifest attribute, in shinyproxy-3.0.0.jar
```

Research tells me it's something to do with their being no `Main-Class` in `META-INF/MANIFEST.MF`
The following appears in shinyproxy v2.6.1 but does not appear when I compile v3.0.0

```
Main-Class: org.springframework.boot.loader.JarLauncher
Start-Class: eu.openanalytics.containerproxy.ContainerProxyApplication
Spring-Boot-Version: 2.5.12
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
Spring-Boot-Classpath-Index: BOOT-INF/classpath.idx
Spring-Boot-Layers-Index: BOOT-INF/layers.idx
```

Is there something new in the build process that needs to be done?

**Comment by LEDfan** [comment]
Hi

Besides the `shinyproxy-3.0.0.jar` file, you will also find a `shinyproxy-3.0.0-exec.jar` file in the `target/` directory. This is the file you should use as an executable file. The  `shinyproxy-3.0.0.jar` file only contains the library code, but not the dependencies etc.

**Comment by nik-humphries** [comment]
That makes total sense. Sorry for asking a silly question and I appreciate you taking the time to help me.
