### ISSUE TITLE
Problem of connection with my web browser

### ISSUE THREAD

**Issue by a-velt** [openanalytics/shinyproxy#41]
Dear Shinyproxy developers,

I have developped a shiny application and I want to use your great tool Shinyproxy to easily manage users and groups. But maybe there is one thing that I misunderstood, but I cannot access the application on my web browser.

Here my application.yml file : 

> shiny:
>   proxy:
>     title: Open Analytics Shiny Proxy
>     logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
>     landing-page: /
>     heartbeat-rate: 10000
>     heartbeat-timeout: 60000
>     port: 8085
>     authentication: none
>     admin-groups: admin
>     # Example: 'simple' authentication configuration
>     users:
>     - name: avelt
>       password: test
>       groups: admin
>     # Example: 'ldap' authentication configuration
>     ldap:
>       url: ldap://ldap.forumsys.com:389/dc=example,dc=com
>       user-dn-pattern: uid={0}
>       group-search-base:
>       group-search-filter: (uniqueMember={0})
>       manager-dn: cn=read-only-admin,dc=example,dc=com
>       manager-password: password
>     # Docker configuration
>     docker:
>       cert-path: /home/none
>       url: http://148.121.147.112:2375
>       port-range-start: 20000
>   apps:
>   - name: 01_hello
>     display-name: Hello Application
>     description: Application which demonstrates the basics of a Shiny app
>     docker-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
>     docker-image: openanalytics/shinyproxy-demo
>     groups: admin
> 
> logging:
>   file:
>     shinyproxy.log

For now, I don't use authentication with LDAP, I prefer to walk things one by one. I work on a server whose address is of type : http: //148.121.147.112: 2375. I use the 2375 port, which seems to be the default port of docker.

I have built your image in my docker. 

sudo docker images : 

> REPOSITORY                      TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
> greatshinyapp                   latest              debe57f07ec7        17 hours ago        2.172 GB
> hello-world                     latest              690d80202531        9 days ago          1.848 kB
> openanalytics/shinyproxy-demo   latest              59a414c9b6e5        11 days ago         828 MB
> thinkr/rfull                    latest              26f8217e95a3        8 months ago        2.018 GB

I chose port 8085 for shinyproxy because my 8080 port is already used.

Now, I launched : 
java -jar /path/to/shinyproxy-1.0.2.jar

All seem to work fine, I have the following lines : 

> ...
> 2017-11-30 10:18:19.081  INFO 46695 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2017-11-30 10:18:19.918  INFO 46695 --- [           main] o.s.l.c.support.AbstractContextSource    : Property 'userDn' not set - anonymous context will be used for read-write operations
> 2017-11-30 10:18:20.203  INFO 46695 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
> 2017-11-30 10:18:20.390  INFO 46695 --- [           main] b.c.e.u.UndertowEmbeddedServletContainer : Undertow started on port(s) 8085 (http)

Ok, I open my web browser and I type : 
http://148.121.147.112:8085/

But I have "ERR_CONNECTION_REFUSED" in Google chrome and "The connection failed" in Firefox. I don't understand the problem. I use shiny server on my port 3838 and when I type : 
http://148.121.147.112:3838/greatshinyapp

I can access to my application.

Can you see the problem ? I used the false address ?

Thank you.
Best,
Amandine

**Comment by tverbeke** [comment]
Hi @a-velt, quick sanity check: did you open port 8085 in your firewall?

**Comment by a-velt** [comment]
Hi,

Yes, I typed : 
iptables -A INPUT -m state --state NEW -p tcp --dport 8085 -j ACCEPT

And then : 
java -jar /path/to/shinyproxy-1.0.2.jar

Same message : 

> 2017-12-01 09:08:35.431  INFO 8483 --- [           main] o.s.l.c.support.AbstractContextSource    : Property 'userDn' not set - anonymous context will be used for read-write operations
> 2017-12-01 09:08:35.599  INFO 8483 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
> 2017-12-01 09:08:35.672  INFO 8483 --- [           main] b.c.e.u.UndertowEmbeddedServletContainer : Undertow started on port(s) 8085 (http)
> 2017-12-01 09:08:35.675  INFO 8483 --- [           main] eu.openanalytics.ShinyProxyApplication   : Started ShinyProxyApplication in 4.978 seconds (JVM running for 5.403)

But when I go on  : 
http://148.121.147.112:8085/

I have the error "The connection failed" ...

**Comment by fmichielssen** [comment]
Hi @a-velt ,

I strongly suspect this is a network or firewall problem.
Does it work if you go on the server and use http://localhost:8085/ ?

**Comment by a-velt** [comment]
Ok, you're right, I stopped my shiny-server and start shinyproxy on 3838 port, and it's ok, I have the shinyproxy interface, but the page is blank, your application does not display anything, is it normal? in any case I have no errors. Thank you for your help !

**Comment by fmichielssen** [comment]
If `authentication` is set to `none`, you should see all apps listed.
In other cases, you could indeed see an empty list, if the authorization of the apps (i.e. the `groups` attribute) does not match any group memberships of the logged-in user.
