### ISSUE TITLE
Keycloak Authentication Frontend Url

### ISSUE THREAD

**Issue by EkremBayar** [openanalytics/shinyproxy#413]
Hi,

I'm a data analyst, not a developer. That's why, I don't know how to handle kind of these things.

I developed Shiny applications  and ShinyProxy runs on 8080 port. In order to authenticate shinyproxy, I ran a keycloak docker container on 8081 port. I took a domain from IT department such as `mydomain.com`.

By using nginx and reverse proxy, I assigned the domain to `http://my-ip-address:8080` (the shinyproxy app url).

When I want to go to the app (`mydomain.com`), I have to login with keycloak. and I see the frontend url on the browser like

**`http://*.* .*.* :8081/auth/realms/shinyproxy/protocol/openid-connect/auth?response_type=code&client_id=shinyproxy&redirect_uri=http%3A%2F%[2Fmydomain.com](http://2fmydomain.com/)%2Fsso%2Flogin&state=858f3a51-b2ba-499c-bef4-804170f2f82b&login=true&scope=openid`**

![6ec108ceb05555ef8034967d48105f7b2924b279](https://user-images.githubusercontent.com/35973642/230400173-eb9ee083-4775-4e9c-a363-0f117cef4bff.jpeg)

Do I need two different domains for this problem? For example,

- App: `app.mydomain.com`
- Keycloak: `keycloak.mydomain.com`

Or can I use single domain for both of them? If it is possible, how nginx file or keycloak settings should be?

I couldn't any advise or documentation for this problem from the begining to the end.

**Comment by LEDfan** [comment]
Hi

You can use both shinyproxy and nginx on the same domain name. 
The easiest way is to have both keycloak and shinyproxy running under a sub-path. E.g. `https://example.com/keycloak` and `https://example.com/shinyproxy`. 
When logging into ShinyProxy using keycloak, it's correct that you'll be redirected to the URL of keycloak. After login, you'll be redirect back to shinyproxy.

Here is an example nginx configuration:

```
server {
	listen 80;
	server_name           example.com
	rewrite     ^(.*)     https://$server_name$1 permanent;

}

server {
	listen 443 ssl;

	server_name           example.com

        #ssl_certificate  .. ;
        #ssl_certificate_key  ..;


   	location /shinyproxy {
		proxy_pass          http://127.0.0.1:8080/shinyproxy;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_read_timeout 600s;

		proxy_redirect    off;
		proxy_set_header  Host             $http_host;
		proxy_set_header  X-Real-IP        $remote_addr;
		proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header  X-Forwarded-Proto $scheme;
	}

   	location /keycloak {
		proxy_pass          http://127.0.0.1:9090/keycloak;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_read_timeout 600s;

                proxy_buffers 8 128k;
                proxy_buffer_size 128k;

		proxy_redirect    off;
		proxy_set_header  Host             $http_host;
		proxy_set_header  X-Real-IP        $remote_addr;
		proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header  X-Forwarded-Proto $scheme;
	}

}
```

**Comment by LEDfan** [comment]
Hi, I think this question has been answered, therefore I'll close this issue, please open a new issue or re-open this issue if you are still experiencing an issue.
