### ISSUE TITLE
[Documentation Improvement] Logout with OpenID Connect (OIDC) - Auth0

### ISSUE THREAD

**Issue by riyadhradhi** [openanalytics/shinyproxy#423]
**My Goal** 

To make `logout-url` works with my shiny app using `Auth0`

**What I tried**

Following documentation to add the `logout-url` as documented [here](https://www.shinyproxy.io/documentation/configuration/#miscellaneous-settings). 

**Error I faced** 

The "returnTo" querystring parameter "http://www.example.com/logout-success" is not defined as a valid URL in "Allowed Logout URLs". To add a new URL, please do it here: https://manage.auth0.com/

**Fix**

After reading [this](https://community.auth0.com/t/the-returnto-querystring-parameter-is-not-defined-as-a-valid-url-in-allowed-logout-urls/45615). I found out that I had to update my shinyproxy `application.yml`, exactly instead of this 
 
```
proxy:
  openid:
    logout-url: https://YOUR_AUTH0_DOMAIN/v2/logout?returnTo=http%3A%2F%2Fwww.yourshinyproxyserver.com
 ```
 
 I made this 
 
 ```
 proxy:
  openid:
    logout-url: https://YOUR_AUTH0_DOMAIN/v2/logout?returnTo=http%3A%2F%2Fwww.yourshinyproxyserver.com&client_id=YOUR_CLIENT_ID
 ```
 
 I got stuck in this for few days, I thought it will be helpful for the others to put it here until the documentations are updated.

**Comment by LEDfan** [comment]
Thanks for reporting this! We have updated the documentation. We have some improvements to the OIDC docs planned as well.
