### ISSUE TITLE
Azure AD B2C -  OAuth 2.0 Access Token Issue

### ISSUE THREAD

**Issue by BernardWilliam** [openanalytics/shinyproxy#425]
I trying to use Azure AD B2C to authenticate with ShinyProxy and I believe this is possible. I have tested by Azure AD B2C set via jwt.ms and another application so I think my issue does not lie on this side. 

The error below is what I encounter

==============================================================
2023-06-26 17:40:30.192 ERROR 2608 --- [XNIO-1 task-2] e.o.c.a.i.OpenIDAuthenticationBackend    : org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: Error while extracting response for type [class org.springframework.security.oauth2.core.endpoint.OAuth2AccessTokenResponse] and content type [application/json;charset=utf-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: An error occurred reading the OAuth 2.0 Access Token Response: tokenValue cannot be empty; nested exception is java.lang.IllegalArgumentException: tokenValue cannot be empty
2023-06-26 17:40:30.195  INFO 2608 --- [XNIO-1 task-2] io.undertow.request.dump                 : 
----------------------------REQUEST---------------------------

My application.yml is here:

``
proxy:
port: 8080
authentication: openid
openid:
auth-url: https://my-tenant/B2C_1_signin_signup/oauth2/v2.0/authorize
token-url: https://my-tenant/B2C_1_signin_signup/oauth2/v2.0/token
jwks-url: https://my-tenant/B2C_1_signin_signup/discovery/v2.0/keys
client-id: 53.....
client-secret: 5sH....
docker:
url: http://localhost:2375/
specs:

id: 01_hello
display-name: Hello Application
description: Application which demonstrates the basics of a Shiny app
container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
container-image: openanalytics/shinyproxy-demo
id: 06_tabsets
container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
container-image: openanalytics/shinyproxy-demo
logging:
requestdump: true
file:
name: shinyproxy.log
`
I wonder if you could please confirm if it is possible to use Azure AD B2C to authenticate and if it is if you can suggest any way to work around this issue

**Comment by BernardWilliam** [comment]
The log is below:
----------------------------REQUEST---------------------------
               URI=/
 characterEncoding=null
     contentLength=-1
       contentType=null
            cookie=JSESSIONID=mklN0FWId8WYXOEHuGjH0g4XXl-y1XpBjGJ1lenL
            header=Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
            header=Accept-Language=en-US,en;q=0.9
            header=Sec-Fetch-Mode=navigate
            header=Accept-Encoding=gzip, deflate, br
            header=sec-ch-ua="Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
            header=sec-ch-ua-mobile=?0
            header=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
            header=Sec-Fetch-User=?1
            header=Sec-Fetch-Dest=document
            header=Connection=keep-alive
            header=Sec-Fetch-Site=none
            header=sec-ch-ua-platform="Windows"
            header=Cookie=JSESSIONID=mklN0FWId8WYXOEHuGjH0g4XXl-y1XpBjGJ1lenL
            header=Upgrade-Insecure-Requests=1
            header=Host=localhost:8080
            locale=[en_US, en]
            method=GET
          protocol=HTTP/1.1
       queryString=
        remoteAddr=/0:0:0:0:0:0:0:1:51472
        remoteHost=0:0:0:0:0:0:0:1
            scheme=http
              host=localhost:8080
        serverPort=8080
          isSecure=false
--------------------------RESPONSE--------------------------
     contentLength=0
       contentType=null
            cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7; domain=null; path=/
            header=Expires=0
            header=Cache-Control=no-cache, no-store, max-age=0, must-revalidate
            header=Set-Cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7; path=/; HttpOnly; SameSite=Lax
            header=X-XSS-Protection=1; mode=block
            header=Pragma=no-cache
            header=Location=http://localhost:8080/login
            header=Date=Mon, 26 Jun 2023 17:40:28 GMT
            header=Connection=keep-alive
            header=X-Content-Type-Options=nosniff
            header=Content-Length=0
            status=302

==============================================================
2023-06-26 17:40:28.721  INFO 2608 --- [XNIO-1 task-2] io.undertow.request.dump                 : 
----------------------------REQUEST---------------------------
               URI=/login
 characterEncoding=null
     contentLength=-1
       contentType=null
            cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7
            header=Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
            header=Accept-Language=en-US,en;q=0.9
            header=Accept-Encoding=gzip, deflate, br
            header=Sec-Fetch-Mode=navigate
            header=sec-ch-ua="Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
            header=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
            header=sec-ch-ua-mobile=?0
            header=Sec-Fetch-User=?1
            header=Sec-Fetch-Dest=document
            header=Connection=keep-alive
            header=Sec-Fetch-Site=none
            header=sec-ch-ua-platform="Windows"
            header=Cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7
            header=Upgrade-Insecure-Requests=1
            header=Host=localhost:8080
            locale=[en_US, en]
            method=GET
          protocol=HTTP/1.1
       queryString=
        remoteAddr=0:0:0:0:0:0:0:1/0:0:0:0:0:0:0:1:51472
        remoteHost=0:0:0:0:0:0:0:1
            scheme=http
              host=localhost:8080
        serverPort=8080
          isSecure=false
--------------------------RESPONSE--------------------------
     contentLength=0
       contentType=null
            header=Expires=0
            header=Cache-Control=no-cache, no-store, max-age=0, must-revalidate
            header=X-XSS-Protection=1; mode=block
            header=Pragma=no-cache
            header=Location=http://localhost:8080/oauth2/authorization/shinyproxy
            header=Date=Mon, 26 Jun 2023 17:40:28 GMT
            header=Connection=keep-alive
            header=X-Content-Type-Options=nosniff
            header=Content-Length=0
            header=Content-Language=en-US
            status=302

==============================================================
2023-06-26 17:40:28.747  INFO 2608 --- [XNIO-1 task-2] io.undertow.request.dump                 : 
----------------------------REQUEST---------------------------
               URI=/oauth2/authorization/shinyproxy
 characterEncoding=null
     contentLength=-1
       contentType=null
            cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7
            header=Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
            header=Accept-Language=en-US,en;q=0.9
            header=Accept-Encoding=gzip, deflate, br
            header=Sec-Fetch-Mode=navigate
            header=sec-ch-ua="Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
            header=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
            header=sec-ch-ua-mobile=?0
            header=Sec-Fetch-User=?1
            header=Sec-Fetch-Dest=document
            header=Connection=keep-alive
            header=Sec-Fetch-Site=none
            header=sec-ch-ua-platform="Windows"
            header=Cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7
            header=Upgrade-Insecure-Requests=1
            header=Host=localhost:8080
            locale=[en_US, en]
            method=GET
          protocol=HTTP/1.1
       queryString=
        remoteAddr=0:0:0:0:0:0:0:1/0:0:0:0:0:0:0:1:51472
        remoteHost=0:0:0:0:0:0:0:1
            scheme=http
              host=localhost:8080
        serverPort=8080
          isSecure=false
--------------------------RESPONSE--------------------------
     contentLength=0
       contentType=null
            header=Expires=0
            header=Cache-Control=no-cache, no-store, max-age=0, must-revalidate
            header=X-XSS-Protection=1; mode=block
            header=Pragma=no-cache
            header=Location=https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/B2C_1_d_signin_signup/oauth2/v2.0/authorize?response_type=code&client_id=5392ecba-259c-4948-8433-a4cfad1c16c2&scope=openid%20email&state=Y5_lnOcogvag_aTqLSfFgAi1CP5yx9URXomwRVLsqd8%3D&redirect_uri=http://localhost:8080/login/oauth2/code/shinyproxy&nonce=hzlXk6OWKeyErbpqgxINwfG3MvUkaNGx3GOpg3giHC4
            header=Date=Mon, 26 Jun 2023 17:40:28 GMT
            header=Connection=keep-alive
            header=X-Content-Type-Options=nosniff
            header=Content-Length=0
            status=302

==============================================================
2023-06-26 17:40:30.192 ERROR 2608 --- [XNIO-1 task-2] e.o.c.a.i.OpenIDAuthenticationBackend    : org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: Error while extracting response for type [class org.springframework.security.oauth2.core.endpoint.OAuth2AccessTokenResponse] and content type [application/json;charset=utf-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: An error occurred reading the OAuth 2.0 Access Token Response: tokenValue cannot be empty; nested exception is java.lang.IllegalArgumentException: tokenValue cannot be empty
2023-06-26 17:40:30.195  INFO 2608 --- [XNIO-1 task-2] io.undertow.request.dump                 : 
----------------------------REQUEST---------------------------
               URI=/login/oauth2/code/shinyproxy
 characterEncoding=null
     contentLength=-1
       contentType=null
            cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7
            header=Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
            header=Accept-Language=en-US,en;q=0.9
            header=Accept-Encoding=gzip, deflate, br
            header=Sec-Fetch-Mode=navigate
            header=sec-ch-ua="Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
            header=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
            header=sec-ch-ua-mobile=?0
            header=Sec-Fetch-User=?1
            header=Sec-Fetch-Dest=document
            header=Connection=keep-alive
            header=Sec-Fetch-Site=none
            header=sec-ch-ua-platform="Windows"
            header=Cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7
            header=Upgrade-Insecure-Requests=1
            header=Host=localhost:8080
            locale=[en_US, en]
            method=GET
         parameter=code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..nMogVi07Tu7dI4DL.muie9pOk0FAv2T9WP0caRpJibGrRVMjbw-Void5RvRXndouYdFZNUOkzSBydu9rb3vm7WoQaq-cwrQkrdWhw5F4ZoohiSsH8aNduaA7oZvTh-pnuov94kYOLpP14faVW_4F_9ryIOcbm9wTKjaSvOm8NU8VOs2XLBdw5QjgmOldMmKYpyNXpOgmBsVdAt08utaCLc_KmL-0I8PKYtNBKgQp-ruc3x6T9ZtBsjkrLmlNw1LEZtuxbENBJCKubRJlFgRizwP9pjlO3KI8sfxgU5s6TPt5pS0ykXwnm_Lq7-iYzJaLAnxKu_uLzLmzaaY58BjsEqk1j224mV-Cptua3pksCBkSyEpuE9isxocwBWMXno1HL50arMxe5xyNmx1v2fgq0Q1tKPbRBBg7zrFvd-jhBUkQVXPvhpqf4f_KfgELewdhgZyot3fF0fQLtM7KYECz-CLMeeCMSkpvEaNgpLqgoGwMmYA7y8DJvxwMW_M9v3_mqbI3u0Ves7bNbjhkgJf97wDNkmGn4BNw8ftfrr4O0c8KByxqQWRnfvifIqTwuo559rOKX76iBVCRWV60iRxHoZAnSThrqzKOZvO3Izs3sl7epmloxXD-G-jq3SOTdPcBvzxg.CA1Nt1cTq4GlnxYLiOkIYg
         parameter=state=Y5_lnOcogvag_aTqLSfFgAi1CP5yx9URXomwRVLsqd8=
          protocol=HTTP/1.1
       queryString=state=Y5_lnOcogvag_aTqLSfFgAi1CP5yx9URXomwRVLsqd8%3d&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..nMogVi07Tu7dI4DL.muie9pOk0FAv2T9WP0caRpJibGrRVMjbw-Void5RvRXndouYdFZNUOkzSBydu9rb3vm7WoQaq-cwrQkrdWhw5F4ZoohiSsH8aNduaA7oZvTh-pnuov94kYOLpP14faVW_4F_9ryIOcbm9wTKjaSvOm8NU8VOs2XLBdw5QjgmOldMmKYpyNXpOgmBsVdAt08utaCLc_KmL-0I8PKYtNBKgQp-ruc3x6T9ZtBsjkrLmlNw1LEZtuxbENBJCKubRJlFgRizwP9pjlO3KI8sfxgU5s6TPt5pS0ykXwnm_Lq7-iYzJaLAnxKu_uLzLmzaaY58BjsEqk1j224mV-Cptua3pksCBkSyEpuE9isxocwBWMXno1HL50arMxe5xyNmx1v2fgq0Q1tKPbRBBg7zrFvd-jhBUkQVXPvhpqf4f_KfgELewdhgZyot3fF0fQLtM7KYECz-CLMeeCMSkpvEaNgpLqgoGwMmYA7y8DJvxwMW_M9v3_mqbI3u0Ves7bNbjhkgJf97wDNkmGn4BNw8ftfrr4O0c8KByxqQWRnfvifIqTwuo559rOKX76iBVCRWV60iRxHoZAnSThrqzKOZvO3Izs3sl7epmloxXD-G-jq3SOTdPcBvzxg.CA1Nt1cTq4GlnxYLiOkIYg
        remoteAddr=0:0:0:0:0:0:0:1/0:0:0:0:0:0:0:1:51472
        remoteHost=0:0:0:0:0:0:0:1
            scheme=http
              host=localhost:8080
        serverPort=8080
          isSecure=false
--------------------------RESPONSE--------------------------
     contentLength=0
       contentType=null
            header=Expires=0
            header=Cache-Control=no-cache, no-store, max-age=0, must-revalidate
            header=X-XSS-Protection=1; mode=block
            header=Pragma=no-cache
            header=Location=http://localhost:8080/auth-error
            header=Date=Mon, 26 Jun 2023 17:40:30 GMT
            header=Connection=keep-alive
            header=X-Content-Type-Options=nosniff
            header=Content-Length=0
            status=302

==============================================================
2023-06-26 17:40:30.585  INFO 2608 --- [XNIO-1 task-2] io.undertow.request.dump                 : 
----------------------------REQUEST---------------------------
               URI=/auth-error
 characterEncoding=null
     contentLength=-1
       contentType=null
            cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7
            header=Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
            header=Accept-Language=en-US,en;q=0.9
            header=Accept-Encoding=gzip, deflate, br
            header=Sec-Fetch-Mode=navigate
            header=sec-ch-ua="Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
            header=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
            header=sec-ch-ua-mobile=?0
            header=Sec-Fetch-User=?1
            header=Sec-Fetch-Dest=document
            header=Connection=keep-alive
            header=Sec-Fetch-Site=none
            header=sec-ch-ua-platform="Windows"
            header=Cookie=JSESSIONID=wcHTRttkPUMPxofJReEZhElGHm5XLRJ4ig9boiT7
            header=Upgrade-Insecure-Requests=1
            header=Host=localhost:8080
            locale=[en_US, en]
            method=GET
          protocol=HTTP/1.1
       queryString=
        remoteAddr=0:0:0:0:0:0:0:1/0:0:0:0:0:0:0:1:51472
        remoteHost=0:0:0:0:0:0:0:1
            scheme=http
              host=localhost:8080
        serverPort=8080
          isSecure=false
--------------------------RESPONSE--------------------------
     contentLength=-1
       contentType=text/html;charset=UTF-8
            header=Expires=0
            header=Cache-Control=no-cache, no-store, max-age=0, must-revalidate
            header=X-XSS-Protection=1; mode=block
            header=Pragma=no-cache
            header=Date=Mon, 26 Jun 2023 17:40:30 GMT
            header=Connection=keep-alive
            header=X-Content-Type-Options=nosniff
            header=Transfer-Encoding=chunked
            header=Content-Type=text/html;charset=UTF-8
            header=Content-Language=en-US
            status=200

**Comment by BernardWilliam** [comment]
Hi 

Thank you for your reply.

- I can authenticate with asp.net application using the same tenet and client secret so I think this is correct.
- The token url also seems to be correct, if I add an addition character to the policy name component of the url, it comes back with a not found error.

- I am running shinyproxy on an azure vm at the moment using the JAR
openjdk version "1.8.0_372-372"
OpenJDK Runtime Environment (build 1.8.0_372-372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)

- It is not going through a proxy and I can use a similar command to the below and it returns so the machine seems to be able to  hit this B2C endpoint 

`curl -X GET "https://your-tenant-name.b2clogin.com/your-tenant-name.onmicrosoft.com/v2.0/.well-known/openid-configuration"`

**Comment by BernardWilliam** [comment]
@LEDfan 
I have checked and doubled checked all the configuration on Azure AD B2C, the client secret and the token url. I have tried different machines all to no avail. I can see on the Azure AD B2C audit log that a token is generated. 
I wonder if you could please share the structure of the application.yml that you use with Azure AD B2C?

Thanks

**Comment by BernardWilliam** [comment]
@LEDfan I am still facing this issue. Are you able to offer any guidance please?

Thanks,
Bernard

**Comment by nik-humphries** [comment]
We found that using Azure B2C we needed to explicitly define a scope (otherwise we get the above error). Your app registration needs to have API permissions against itself or another service app registration (which is what we do).

```yaml
    authentication: openid
    openid:
      auth-url: https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/b2c_1a_signin_portal_test/oauth2/v2.0/authorize
      token-url: https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/b2c_1a_signin_portal_test/oauth2/v2.0/token
      jwks-url: https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/b2c_1a_signin_portal_test/discovery/v2.0/keys
      client-id: ${shinyproxy_client_id}
      client-secret: ${shinyproxy_client_secret}
      scopes: ["openid", "https://{tenant}.onmicrosoft.com/{service-app-registration}/user.access"]
      roles-claim: "roles"
      logout-url: https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/oauth2/v2.0/logout?p=b2c_1a_signin_portal_test
```

**Comment by LEDfan** [comment]
Hi @BernardWilliam 

In addition to the suggestion of @nik-humphries , I see that for one deployment, we add the client-id as a scope, e.g.:

```yaml
proxy:
  openid:
    # ...
    client-id: 9c7f8a63-03df-48de-8b0b-69333cac5b0c
    scopes: ['9c7f8a63-03df-48de-8b0b-69333cac5b0c']
```

Could you give this a try and let us know whether one of these solutions work?

**Comment by BernardWilliam** [comment]
Hi @LEDfan and @nik-humphries 

Thanks you both very much for your replies. I will check out your suggestions and let you know

**Comment by BernardWilliam** [comment]
@LEDfan I have made some progress taking the account of yours and @nik-humphries suggestions. The issue I am facing now is https://shinyproxy.io/faq/#authentication-using-openid-does-not-work-because-of-missing-attribute-email-in-attributes-exception

However when I try to 
username-attribute: with any value to my application.yml shinyproxy just will not load
I have also tried proxy.openid.username-attribute at the root of the yml with no luck.

Any ideas?
Thanks,
Bernard

**Comment by BernardWilliam** [comment]
@LEDfan It is actually working. I must have had some syntax errors. So the solution to my issue was adding the client-id to scopes and using `proxy.openid.username-attribute: aud `on the very last line of the application.yml. Thanks for your suggestions. This issue can be closed.

**Comment by LEDfan** [comment]
Hi @BernardWilliam 
Thanks for reporting back, since your problem is solved, I'm going to close this issue.
