### ISSUE TITLE
Bookmarking - Redirect to correct app endpoint if app is not running

### ISSUE THREAD

**Issue by joakibo** [openanalytics/shinyproxy#426]
Hi!

Thanks for the ShinyProxy v3 upgrade. A lot of good changes across the board. 

Especially the app bookmarking and being able to track internal app endpoints is very useful! It seems to work very well as long as an app is running, however, it would be very valuable to be able to link directly to a specific page for an app and app would startup and enter that page if not running.

Current behaviour (app already running; this is OK):

1. Try to access `/app/myapp/hello`
2. Goes directly to `/app/myapp/hello`

Current behaviour (app not running):

1. Try to access `/app/myapp/hello`
2. Redirects to `/app/myapp` to startup
3. Lands at `/app/myapp` when started up
4. Can again go to `/app/myapp/hello`

Expected behaviour (app not running):

1. Try to access `/app/myapp/hello`
2. Redirects to `/app/myapp` to startup
3. Lands at `/app/myapp/hello` when started up

Thanks!

**Comment by LEDfan** [comment]
It's nice to hear you like the latest release.
This is a good idea and we will take this into account for the next release.

**Comment by joakibo** [comment]
@LEDfan Another question on this: it doesn't seem like the URL of the app updates if you click links to internal pages. If you go directly to an internal page, f.ex. `/about` then it works fine (as long as app is running as mentioned earlier), but if you're on f.ex. `/` and then click the link to `/about` the URL doesn't update. 

What is the expected behaviour here?

**Comment by LEDfan** [comment]
This should work, we have tested this with different applications. Do you have the `track-app-url` setting enabled for your app? If so, what technology are you using for the app, or could you share an example app that doesn't work?

**Comment by joakibo** [comment]
The `track-app-url` has been overlooked on our side. Sorry for that, and thanks a lot! Enabling that will most likely solve it then 👍

**Comment by LEDfan** [comment]
With the release of ShinyProxy 3.0.2, it is now possible to start an application with existing subpaths and/or querystrings, therefore I'm closing this issue.

**Comment by joakibo** [comment]
Awesome @LEDfan , thanks for quick fix. Looking forward to upgrade 👍
