### ISSUE TITLE
Scale down to Zero or Uninstall for ShinyProxy deployment causes orphan pods

### ISSUE THREAD

**Issue by littlenetcoder** [openanalytics/shinyproxy#427]
Hi, I am running ShinyProxy (3.0.1) [containerized Kubernetes config](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/03-containerized-kubernetes) example on Kubernetes (Minikube and Azure Kubernetes Service ). Whenever i scale down ShinyProxy to Zero or Uninstall. All the pods that were spun up by the  ShinyProxy get left behind as zombie's. 

I have tried terminationGracePeriodSeconds  but didn't work. ShinyProxy container removed immediately. 

I am aware of App Recovery feature but I want to scale down ShinyProxy to Zero to save cost during Non-operational hours. So it's very important for me to remove orphan pods. 

Thank You.

**Comment by LEDfan** [comment]
Hi

The example you linked to is very basic, with this configuration it's possible you experience orphaned pods. Instead, we advice to use the [ShinyProxy operator](https://github.com/openanalytics/shinyproxy-operator) which is the best way to use ShinyProxy on kubernetes.

Once you use the operator, you can easily scale to zero, however, this will keep the current pods running (and also the metadata will still be stored in Redis). Therefore, the correct procedure is to first stop all apps using the API and then scale to zero. Here is an example script:

```bash
#!/usr/bin/env bash

# fetch all proxies
PROXIES=$(curl https://shinyproxy-demo.local/admin/data -k -u "jack:password"  | jq -r ".data[].proxyId")

# stop all proxies
for proxy in $PROXIES
do
  echo "Stop: $proxy"
  curl -X PUT -H "Content-Type: application/json" https://shinyproxy-demo.local/api/$proxy/status -k -u "jack:password" -d '{ "desiredState": "Stopping" }' -v
done

# scale to zero
kubectl patch -n shinyproxy shinyproxy/shinyproxy --patch '{"spec":{"replicas": 0}}'  --type merge
```

You need to change the URL of ShinyProxy and change the username and password.

That being said, I created an internal issue to better support scaling to zero.

**Comment by littlenetcoder** [comment]
Thank you for your response.

In order to reproduce the issue with limited information, I utilized the provided example. However, in a real-world scenario, we have integrated ShinyProxy into our Enterprise App and embedded it within an iframe. We have a multitude of Shiny (R) Apps customized for individual clients, allowing access only to the apps they have subscribed to. Furthermore, we have extensively customized the ShinyProxy code to incorporate authentication and authorization functionalities.

I appreciate your suggestion to use the ShinyProxy operator, but I would prefer to utilize a simple kubectl command to locate and delete pods when uninstalling ShinyProxy from our DevOps pipeline. This approach might offer a more straightforward solution in the short term. However, I am interested in implementing App Recovery and utilizing ShinyProxy Session management through Redis in the long run.

**Comment by LEDfan** [comment]
Thanks for the additional information.

You can find pods created by shinyproxy using the following command (in the shinyproxy namespace):

```bash
kubectl get -n shinyproxy pod -l "openanalytics.eu/sp-proxied-app=true"
```

In order to stop all these apps you can use:

```bash
kubectl delete -n shinyproxy pod -l "openanalytics.eu/sp-proxied-app=true" --force
```

You can use the `-A` option to delete in all namespaces:

```bash
kubectl delete -A pod -l "openanalytics.eu/sp-proxied-app=true" --force
```

I hope this helps for your current problem.

**Comment by littlenetcoder** [comment]
Thank you for your reply. I utilized a single statement to employ the same approach.

`kubectl get po -n default -l 'openanalytics.eu/sp-proxied-app=true' -o name | xargs kubectl delete -n default`
