### ISSUE TITLE
Unix Socket Instead of TCP

### ISSUE THREAD

**Issue by dragoonis** [openanalytics/shinyproxy#43]
As per the following code in your file: 
`src/main/java/eu/openanalytics/services/DockerService.java`

``` java
       @Bean
        public DockerClient getDockerClient() {
                try {
                        return DefaultDockerClient.builder()
                                .dockerCertificates(DockerCertificates.builder().dockerCertPath(Paths.get(environment.getProperty("shiny.proxy.docker.cert-path", ""))).build().orNull())
                                .uri(environment.getProperty("shiny.proxy.docker.url"))
                                .build();
                } catch (DockerCertificateException e) {
                        throw new ShinyProxyException("Failed to initialize docker client", e);
                }
        }
```

It looks like you're forcing all users to communicate to docker using a TCP address. It's more compatible with docker hosts for us to just mount the `docker.sock` file and not need to modify our daemons to expose docker over TCP ports.

I've reviewed the underlying spotify docker client code here:
https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L397-L401

``` java
    if (originalUri.getScheme().equals(UNIX_SCHEME)) {
      this.uri = UnixConnectionSocketFactory.sanitizeUri(originalUri);
    } else {
      this.uri = originalUri;
    }
```

As such: it looks like your software is already compatible with unit sockets, by specifying: `unix://...`

Could you please tell me what the .yml configuration `uri` value should be in order to communicate with the mounted unix socket?

Thanks

**Comment by dragoonis** [comment]
@dseynaev

**Comment by PlasmaPower** [comment]
https://github.com/openanalytics/shinyproxy/pull/33 fixes this by making the default to communicate with docker through the socket.

**Comment by dragoonis** [comment]
Update: I am trying `unix:///var/run/docker.sock` but untested right now

**Comment by dragoonis** [comment]
@PlasmaPower

I'm using docker-compose, on a single host btw

 if the spotify docker client supports UNIX_SCHEME then why do we still need an external bridge network?

**Comment by PlasmaPower** [comment]
Shinyproxy still needs to communicate with the underlying containers, not just the docker daemon. The bridge network is for the former.

**Comment by dragoonis** [comment]
@PlasmaPower 

AFAIK shiny proxy needs to spin up its own containers, and it can do this with the docker daemon socket,

can you educate me on what "underlying containers" means?

**Comment by PlasmaPower** [comment]
Shinyproxy spins up the containers and then forwards requests to them. For instance, shinyproxy might spin up a container with the name `boring_cori`. Then, a request to `localhost:8080/boring_cori/subpath` would be forwarded to `/subpath` in the container. That requires a network connection.

**Comment by dragoonis** [comment]
@PlasmaPower if my shinyproxy and shiny are using docker-compose with their own `default` bridge network .. will all containers that shinyproxy spins up be in the same network? which network do you attach your `boring_cori` containers to ?

**Comment by PlasmaPower** [comment]
@dragoonis You'll have to manually set the `docker-network` option to the network that docker compose creates. For instance, if the `docker-compose.yml` is in a folder named `example_app`, the default network will be named `example_app_default`.

**Comment by dragoonis** [comment]
@PlasmaPower okay - i have tried the unix socket syntax but i was getting permission denied (500) on creating a container, so I modified the docker daemon and now my docker connection string is `172.x.x.x:PORT`

The outstanding issue for us (OasisLMF team) is:

The shiny_proxy makes containers on the fly, but we don't know how to `correlate the containers made on-the-fly with the containers in the docker-compose network, therefore when we do our teardowns it keeps alive the on-the-fly ones`

What can we tweak/do to easily detect which containers were made on the fly, so we can tear them them too?

* we are loading up in a docker-compose.yml file
* our docker-compose containers are: `flamingo_server, flamingo_shiny and shiny_proxy `
* our teardowns are: `docker-compose down -v`

**Comment by dragoonis** [comment]
@dseynaev

**Comment by fmichielssen** [comment]
Unix sockets can now be used either by specifying `docker.host: unix:///var/run/docker.sock` or by omitting the `docker.host` setting entirely.
This functionality was enabled by PR #33 as @PlasmaPower mentioned.

**Comment by romunov** [comment]
@fmichielssen just to be clear, this option could be used instead of `url` in `application.xml`?
