### ISSUE TITLE
RStudio can't upload file (with shiny-proxy 3.0.0 and 3.0.1)

### ISSUE THREAD

**Issue by avraam-inside** [openanalytics/shinyproxy#430]
When trying to upload a file via the upload button, the error "Unexpected response from server" appears (regardless of the file size). There is no such problem on the version of shiny-proxy 2.6.1

Please, fix it

**Comment by LEDfan** [comment]
Please have a look at this issue https://github.com/openanalytics/shinyproxy/issues/419#issuecomment-1547969131
We are in the progress of releasing a final release that includes this fix.

**Comment by avraam-inside** [comment]
Yes, Google did not give me it out, these nexus-cloud developments seems are working, thank you! Now we are looking forward to the official update to 3.0.2!)
