### ISSUE TITLE
Get full openid profile 

### ISSUE THREAD

**Issue by magralo** [openanalytics/shinyproxy#434]
Is it possible to get the raw json of the user that logs in using OIDC?

i am wondering if it is possible to get the full raw HTML since I need additional information in the profile to personalize the app experience.

Basically, I am using outh0 and I want to access the app_metadata field that comes with the raw json!

Thanks

**Comment by LEDfan** [comment]
Hi, this is possible by using SpEL expression, see the documentation: https://shinyproxy.io/documentation/spel/
