### ISSUE TITLE
3.0.2 jar file on website does not match jar from GitHub releases

### ISSUE THREAD

**Issue by dfsnow** [openanalytics/shinyproxy#436]
The JAR file linked on the [website downloads page](https://shinyproxy.io/downloads/shinyproxy-3.0.2.jar) points to a [124 KB file](https://shinyproxy.io/downloads/shinyproxy-3.0.2.jar), while the executable JAR [listed in the releases](https://github.com/openanalytics/shinyproxy/releases/download/v3.0.2/shinyproxy-3.0.2-exec.jar) is 130 MB. I believe the Downloads page is an error since all previous releases listed on that page point to the full executable.

**Comment by LEDfan** [comment]
Hi, thanks for reporting this. I uploaded the wrong artifact and this has now been fixed.
