### ISSUE TITLE
Update Auth0 docs to use actions instead of rules

### ISSUE THREAD

**Issue by AlexH-BoxFish** [openanalytics/shinyproxy#439]
In November 2024 Auth0 will be [discontinuing rules](https://auth0.com/blog/preparing-for-rules-and-hooks-end-of-life/) in favour of actions. The docs currently say to create a rule with:

```
function (user, context, callback) {
  context.idToken['https://shinyproxy.io/shinyproxy_roles'] = user.app_metadata.shinyproxy_roles;
  callback(null, user, context);
}
```

Which won't work for new Auth0 customers after October this year. Based on their [migrate from rules to actions docs](https://auth0.com/docs/customize/actions/migrate/migrate-from-rules-to-actions) this would become a `Login / Post Login` action:

```
exports.onExecutePostLogin = async (event, api) => {
  api.idToken.setCustomClaim("https://shinyproxy.io/shinyproxy_roles", user.app_metadata.shinyproxy_roles);
};
```

Which is working for me.

**Comment by LEDfan** [comment]
Thanks a lot for reporting this! I have updated the documentation.
