### ISSUE TITLE
Memory / RAM Increases

### ISSUE THREAD

**Issue by nik-humphries** [openanalytics/shinyproxy#442]
I'm running multiple instances of ShinyProxy across different regions and on different AKS clusters.

I've noticed that on most of my deployments, the memory usage appears to be increasing through time and is getting to ~1.6GB.

Example 1 (v3.0.2):
![image](https://github.com/openanalytics/shinyproxy/assets/20989616/fd5214bd-12be-4ea4-95d4-ff8b8847e3c9)

Example 2 (v3.0.2):
![image](https://github.com/openanalytics/shinyproxy/assets/20989616/70f5f4f2-c0cd-4c74-acb1-8e0e29545e52)

Example 3 (v3.0.2):
![image](https://github.com/openanalytics/shinyproxy/assets/20989616/28dfde1d-ebc2-44ff-88d4-7c46c6474285)

I have made some alterations to the ShinyProxy .jar (pushing some things to the front end like the app params as I have added a dropdown on the navbar). I can't think that anything I've added will have led to memory increases like this.

I updated the containers on August 1st to version 3.0.2 
![image](https://github.com/openanalytics/shinyproxy/assets/20989616/5aa1d3b0-f2f8-47c0-8405-d102316fb87b)

I am also using redis sentinel and ShinyProxy Operator 2.0.0 as recommended.

I'm just wondering if anybody else is seeing behaviour like this or if there's a reason for it? I'd like to keep the memory usage as low as possible of course!

**Comment by LEDfan** [comment]
Hi

I checked a few of your ShinyProxy servers (similar setup) and here we see that the ShinyProxy pod is using about 0.5 GB RAM. In addition the memory usage is relatively stable.

However, memory management in Java is complex and is also partially designed to be fast with the consequence that it uses more memory. In short, it could be that the JVM is allocating memory, but no longer needs it and then releasing it. 

What I would try is adding a k8s resource limit, that limits the pod memory to e.g. 2GB. If you then see the pod is using about 1.5GB maximum, you could decrease it further. 
Here is an example of defining the resource limits: https://github.com/openanalytics/shinyproxy-operator/blob/master/docs/deployment/overlays/1-namespaced/resources/shinyproxy.shinyproxy.yaml#L69-L77

**Comment by nik-humphries** [comment]
I've assigned memory req/lim for the pods, was just wondering if people had observed changed behaviour. Sitting in at 1.5GB is manageable to run on the cluster but I'll observe to see if it acts erratically.

Conclusion is, let's blame Java :)
