### ISSUE TITLE
Blank white screen after launching an app

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy#446]
I am trying to migrate existing platform to use new version of shinyproxy (3.0.2) and shinyproxy operator(2.0.0). we are running EKS version 1.26.
But when I am trying to start an app, I just get a blank white screen. I do not see any errors as well in shinyproxy logs or shinyproxy operator logs.
But I did notice that the proxy is not starting and app container is not getting launched as well.
Do you know what could be the potential issue here?
Below you can find the configuration:
`apiVersion: openanalytics.eu/v1alpha1
kind: ShinyProxy
metadata:
  name: shinyproxy-dev
  namespace: dev
spec:
  spring:
    session:
      store-type: redis
    redis:
      #host: redis
      password: ${REDIS_PASSWORD}
      sentinel:
        master: shinyproxy
        password: ${REDIS_PASSWORD}
        nodes: redis-node-0.redis-headless.redis:26379, redis-node-1.redis-headless.redis:26379, redis-node-2.redis-headless.redis:26379
      #database: 1
  management:
    endpoints:
      web:
        exposure:
          include: info,health,beans,prometheus,metrics
    metrics:
      export:
        prometheus:
          enabled: true
  server:
      #useForwardHeaders: true
      secureCookies: true
      frameOptions: sameorigin
      forward-headers-strategy: native
  proxy:
      store-mode: Redis
      stop-proxies-on-shutdown: false
      title: DEV- ShinyProxy
      logoUrl: ""
      landing-page: /
      heartbeat-rate: 10000 #in miliseconds
      heartbeat-timeout: 60000 #in miliseconds
      container-wait-time: 60000 #in miliseconds
      default-proxy-max-lifetime: 1440 #in minutes
      port: 8080
      authentication: openid
      #admin-groups: <AD Group>
      openid:
        auth-url: [https://login.microsoftonline.com/3ac94b33-45368567-4821-9502 /discovery/v2.0/keys](https://login.microsoftonline.com/3ac94b33-9135-4821-9502-eafda6592a35/discovery/v2.0/keys)
        token-url: [https://login.microsoftonline.com/3ac94b33-45368567-4821-9502 /discovery/v2.0/keys](https://login.microsoftonline.com/3ac94b33-9135-4821-9502-eafda6592a35/discovery/v2.0/keys)        
        jwks-url: [https://login.microsoftonline.com/3ac94b33-45368567-4821-9502 /discovery/v2.0/keys](https://login.microsoftonline.com/3ac94b33-45368567-4821-9502%20/discovery/v2.0/keys)
        client-id: a346bfa4-d0c3-4987-a906-e1ebdf3d0b3d
        client-secret: ${azure_dev}
        username-attribute: email
        roles-claim: roles #groups #accessToken  #idToken
        #scopes: ["email","profile"]
      usage-stats-url: micrometer
      container-backend: kubernetes
      kubernetes:
        internal-networking: true
        namespace: dev
        pod-wait-time: 600000 #in milliseconds
        image-pull-policy: IfNotPresent
        image-pull-secrets :
        - name: secret-docker
      template-path: ./templates
      template-groups:
      - id: analytical
        properties:
          display-name: ANALYTICAL
          group-icon: assets/img/analytical.svg
      - id: chemistry
        properties:
          display-name: CHEMISTRY
          group-icon: assets/img/chemistry.svg
      - id: demo
        properties:
          display-name: DEMO
      specs: []
      logging:
      file:
        name: shinyproxy.log
      level:
        root: DEBUG
      spring:
      servlet:
        multipart:
          max-file-size: 50MB
          max-request-size: 50MB
  kubernetesPodTemplateSpecPatches: |
      - op: add
        path: /spec/containers/0/env/-
        value:
          name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
      - op: add
        path: /spec/containers/0/env/-
        value:
          name: azure_dev
          valueFrom:
            secretKeyRef:
              name: secret
              key: azure_dev
      - op: replace
        path: /spec/containers/0/livenessProbe
        value:
          failureThreshold: 2
          httpGet:
            path: /actuator/health/liveness
            port: 9090
            scheme: HTTP
          periodSeconds: 1
          initialDelaySeconds: 140
          successThreshold: 1
          timeoutSeconds: 1
      - op: replace
        path: /spec/containers/0/readinessProbe
        value:
          failureThreshold: 2
          httpGet:
            path: /actuator/health/readiness
            port: 9090
            scheme: HTTP
          periodSeconds: 1
          initialDelaySeconds: 140
          successThreshold: 1
          timeoutSeconds: 1
      - op: add
        path: /spec/volumes/-
        value:
          name: shinyproxy-templates-dev
          persistentVolumeClaim:
            claimName: shinyproxy-templates-dev
      - op: add
        path: /spec/containers/0/volumeMounts/-
        value:
            mountPath: "/opt/shinyproxy/templates"
            name: shinyproxy-templates-dev
      - op: add
        path: /spec/containers/0/resources
        value:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.5
            memory: 1Gi
      - op: add
        path: /spec/serviceAccountName
        value: default
  kubernetesIngressPatches: |
    - op: add
      path: /metadata/annotations
      value:
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/affinity: cookie
        nginx.ingress.kubernetes.io/proxy-read-timeout: "420"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "420"
        nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
        nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
        nginx.ingress.kubernetes.io/proxy-body-size: 5000m
        cert-manager.io/cluster-issuer: sectigo
    - op: add
      path: /spec/ingressClassName
      value: nginx
    - op: add
      path: /spec/tls
      value:
        - hosts:
          - beta-dev.com
          secretName: beta-dev-tls
  image: docker.artifactrepo.com/openanalytics/shinyproxy:3.0.2
  imagePullPolicy: Always
  image-pull-secrets :
  - name: secret-docker
  replicas: 1
  fqdn: beta-dev.com`

**Comment by LEDfan** [comment]
Hi @aupadh12 

As discussed this is probably caused by outdated templates, you'll have to use the latest version of the ShinyProxy templates and re-apply your changes on top of it. See: https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template

Feel free to re-open if you still run into an issue.
