### ISSUE TITLE
Failed to load Swagger API docs 

### ISSUE THREAD

**Issue by nickmelis** [openanalytics/shinyproxy#451]
Following [this](https://www.shinyproxy.io/documentation/api/) link in the documentation, I try to navigate to https://www.shinyproxy.io/downloads/swagger/. 
The resulting page shows the following error:

### Errors
 
```
Fetch error
response status is 404 /3.0.0-preview/downloads/api/v3.0.0.json
```

**Comment by LEDfan** [comment]
Hi

Thanks a lot for reporting this! Something went wrong when deploying the final version of the documentation of the 3 release, I have now fixed this.

**Comment by nickmelis** [comment]
Thanks a lot @LEDfan , I can confirm it works now 😃
