### ISSUE TITLE
Can not connect to docker daemon after docker upgrade

### ISSUE THREAD

**Issue by keqiang** [openanalytics/shinyproxy#46]
This issue was mentioned in [this post](https://support.openanalytics.eu/t/shiny-proxy-not-working-after-latest-docker-upgrade/318)

Looks like the issue will be gone if the docker.service is edited. However, as my last reply to the above post, in my case, I have a CentOS 7 and the config needs to be `ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock -D -H tcp://127.0.0.1:2375 ` rather than what the document says `ExecStart=/usr/bin/dockerd -H fd:// -D -H tcp://127.0.0.1:2375`. Unfortunately this setting would not work with Swarm node, saying time out to start swarm container.

**Comment by KrzysztofPrzygodzki** [comment]
ExecStart=/usr/bin/dockerd -D -H unix:// -D -H tcp://127.0.0.1:2375   ?

**Comment by LEDfan** [comment]
Hi 

This is quite an old issue and in the meantime we have updated our documentation. Therefore I'm closing this issue. Feel free to re-open it if you need more help.
