### ISSUE TITLE
templates volume overwriting all other volumes for shiny apps after upgrading to 3.0.2

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy#461]
hi Team,

We use shinyproxy 3.0.2 and shinyproxy operator 2.0.0 in our deployment.
We have stored our templates folder on a windows fileshare and we mount it using kubernetesPodTemplateSpecPatches as shown below:
`kubernetesPodTemplateSpecPatches: |
   - op: replace
      path: /spec/containers/0/livenessProbe
      value:
        failureThreshold: 2
        httpGet:
          path: /actuator/health/liveness
          port: 9090
          scheme: HTTP
        periodSeconds: 1
        initialDelaySeconds: 140
        successThreshold: 1
        timeoutSeconds: 1
    - op: replace
      path: /spec/containers/0/readinessProbe
      value:
        failureThreshold: 2
        httpGet:
          path: /actuator/health/readiness
          port: 9090
          scheme: HTTP
        periodSeconds: 1
        initialDelaySeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
    - op: add
      path: /spec/volumes/-
      value:
        name: shinyproxy-templates-dev
        persistentVolumeClaim:
          claimName: shinyproxy-templates-dev
    - op: add
      path: /spec/containers/0/volumeMounts/-
      value:
          mountPath: "/opt/shinyproxy/templates"
          name: shinyproxy-templates-dev`

We also mount other filesystems and windows drive as a volume mount using kubernetes pod patches inside a shiny app running on shinyproxy as shown below:

`kubernetes-pod-patches: |
          - op: add
            path: /spec/volumes
            value:
              - name: db1
                persistentVolumeClaim:
                  claimName: db1-dev
          - op: add
            path: /spec/containers/0/volumeMounts
            value:
              - mountPath: "/opt/images/"
                name: db1`

However, we have noticed that the volume mounted on the shiny app is not from the kubernetes pod patches but from the kubernetesPodTemplateSpecPatches.
When I do not mount the templates, then I can the correct volume gets mounted.
Thus I can conclude that the templates volume is getting overlayed on all other shiny apps.

Can you please help us here to identfy the actual issue and why is this happening? Our migration to latest version is blocked because of this.

**Comment by LEDfan** [comment]
This has been resolved offline.
