### ISSUE TITLE
[Documentation] OIDC example when using keycloak

### ISSUE THREAD

**Issue by danielloader** [openanalytics/shinyproxy#463]
I noticed there's a deprecation warning on [using the keycloak bespoke authentication](https://www.shinyproxy.io/documentation/configuration/#single-sign-on--keycloak) option, but the OIDC examples are currently limited to Auth0 and Cognito.

Would it be possible to extend the documentation to cover this gap and add keycloak steps via OIDC?

Thanks

**Comment by LEDfan** [comment]
Hi, as part of the deprecation we are planning a complete overhaul on the OIDC/auth documentation, withe examples for common providers. The idea is to have complete examples and also some instructions on configuring the IDP. Furthermore, these examples will be put in a single place, currently they are bit spread. 
For the time being, I updated the example on using [Keycloak groups](https://shinyproxy.io/faq/#how-to-use-keycloak-groups-in-shinyproxy) and added an entry for [Keycloak roles](https://shinyproxy.io/faq/#how-to-use-keycloak-roles-in-shinyproxy)

**Comment by LEDfan** [comment]
Hi, we now have a complete example for integrating ShinyProxy with Keycloak, see https://github.com/openanalytics/shinyproxy-config-examples/tree/master/12-openid-keycloak .
If you need more information, please open a new issue or re-open this issue.
