### ISSUE TITLE
Container unresponsive

### ISSUE THREAD

**Issue by ConYel** [openanalytics/shinyproxy#466]
Hello and thank you for this great solution to host shiny applications.
I am working on a shinydashboard project and I would like to use shinyproxy for this application.
I will be using a host provider but first I am testing locally.

So I followed the guide for creating the application.yml and it seems that I get theshinyproxy running, but it doesn't seem to keep the "app" container running.
Peculiarities of my tools:
I use `podman` instead of `docker` so I followed the instruction from here:  https://github.com/openanalytics/shinyproxy/issues/385
you can find the dockerfile I am using here: https://github.com/ConYel/dashboard_survey/blob/main/dashboard_container/Dockerfile
On my machine I pulled the image of shinyproxy from dockerhub:
`docker.io/openanalytics/shinyproxy  3.0.2`

When I get to run the shinyproxy container with this application.yml:
https://github.com/ConYel/dashboard_survey/blob/main/application.yml
running this command:
```
podman system service -t 0 tcp:127.0.0.1:2375 & podman run --rm -ti --name shinyproxy  --net host -v ./application.yml:/opt/shinyproxy/application.yml  docker.io/openanalytics/shinyproxy:3.0.2
```

I always get:
```
specId=01_dashboard] Container unresponsive, trying again (13/110): http://localhost:20000
2023-11-26 18:07:40.948  WARN 1 --- [pool-1-thread-1] e.o.shinyproxy.ShinyProxyTestStrategy    : [user=jeff proxyId=9eef5494-c23b-41f5-b380-590853c665c6 specId=01_dashboard] Container unresponsive, trying again (14/110): http://localhost:20000
```

and I also check if the container has started properly and then I login using the basic credentials but when I try to run the included app on browser from shinyproxy 

```
~$ podman ps -a
CONTAINER ID  IMAGE                               COMMAND               CREATED        STATUS                    PORTS                    NAMES
b5c3eca3c047  localhost/dashboard_rminimal:0.03b  Rscript dashboard...  4 minutes ago  Exited (1) 4 minutes ago  0.0.0.0:20000->3838/tcp  objective_yonath
cd496023d99c  localhost/dashboard_rminimal:0.03b  Rscript dashboard...  3 minutes ago  Exited (1) 3 minutes ago  0.0.0.0:20000->3838/tcp  beautiful_bhaskara
f55457adc3ef  localhost/dashboard_rminimal:0.03b  Rscript dashboard...  3 minutes ago  Exited (1) 2 minutes ago  0.0.0.0:20000->3838/tcp  nervous_ramanujan
[1]+  Done                    podman system service -t 0 tcp:127.0.0.1:2375  (wd: ~)
```
the containers seem to not be destroyed after being called and not responding.

Any help would be much appreciated!
@LEDfan

**Comment by mnazarov** [comment]
Looking at your code, I think it might be sufficient to remove the line ENTRYPOINT line https://github.com/ConYel/dashboard_survey/blob/main/dashboard_container/Dockerfile#L30C1-L30C46 (or adjust the `container-cmd` accrodingly).
I suggest reading about the differences between ENTRYPOINT and CMD, e.g. https://spacelift.io/blog/docker-entrypoint-vs-cmd
