### ISSUE TITLE
Error in docs for OIDC with Auth0

### ISSUE THREAD

**Issue by psolymos** [openanalytics/shinyproxy#475]
The [Auth0 specific parts of the OIDC docs](https://www.shinyproxy.io/documentation/configuration/#auth0) state that the login / post-login flow action should be:

```
exports.onExecutePostLogin = async (event, api) => {
  api.idToken.setCustomClaim("https://shinyproxy.io/shinyproxy_roles", user.app_metadata.shinyproxy_roles);
};
```

However, `user` is part of the `event` object, thus the correct code is:

```
exports.onExecutePostLogin = async (event, api) => {
  api.idToken.setCustomClaim("https://shinyproxy.io/shinyproxy_roles", event.user.app_metadata.shinyproxy_roles);
};
```

I tested this modification using both the the Auth0 API and ShinyProxy 3.0.2 and it works.

**Comment by DzimitryM** [comment]
This finding by @psolymos helped me a lot!
Recently I started getting messages kind of 'Proxy failed to start'. The above fix, as well as the removal of permission to download docker images, brought the system back to life.
```
proxy:
  docker:
    image-pull-policy: Never
```

**Comment by LEDfan** [comment]
Thanks a lot for reporting this issue, I just fixed this on our website.
