### ISSUE TITLE
Container Logs to s3 Issue

### ISSUE THREAD

**Issue by sjhawkins01** [openanalytics/shinyproxy#477]
Hello! I am running shinyproxy with docker swarm and am trying to get the container logs to write to s3. I was able to get log files written to s3 just fine when I run shinyproxy directly on an ec2. But for some reason when I use the exact same parameters in the swarm set up, the files don't appear in s3. Any idea what might be happening? 

I was able to change the container-log-path and mount a volume to access the files from the container on the host machine, but when I use nano to open the files, it's just an empty file. Could this have something to do with it?

**Comment by LEDfan** [comment]
Hi @sjhawkins01 

Thanks a lot for reporting this issue! Indeed, collection of logs when using Docker swarm with multiple nodes was not working. I implemented a fix and this will be part of the upcoming release.

**Comment by sjhawkins01** [comment]
Fantastic! Thank you so much!

**Comment by sjhawkins01** [comment]
Fantastic, thank you so much!

Serena
________________________________
