### ISSUE TITLE
Customizable support email title

### ISSUE THREAD

**Issue by nickmelis** [openanalytics/shinyproxy#479]
At the moment, support requests from ShinyProxy are always sent with the same title: "ShinyProxy Error Report" (see https://github.com/openanalytics/shinyproxy/blob/master/src/main/java/eu/openanalytics/shinyproxy/controllers/IssueController.java#L90).

It would be good (especially when running multiple ShinyProxy instances for different clients) to be able to customise the email title, so that automatic filtering can be applied on the recipient side.

It could be as simple as adding a new config variable: 

```
proxy:
  support:
    email-title: Custom ShinyProxy Error Report for client XYZ
```

It'd be good to gather interest for such a feature, happy to PR this if people think it can be useful.

**Comment by LEDfan** [comment]
Hi, this is now part of the ShinyProxy 3.1.0 we released today. See https://shinyproxy.io/documentation/configuration/#reporting-issues and https://shinyproxy.io/documentation/configuration/#app-support-mail-subject Thanks again for your suggestion!
