### ISSUE TITLE
OpenID Connect docs: Use `scopes` instead of `openid-scopes`

### ISSUE THREAD

**Issue by akkornel** [openanalytics/shinyproxy#480]
Hello!  I would like to report an issue with a documentation page on www.shinyproxy.io.  Specifically, in the OIDC configuration section at https://www.shinyproxy.io/documentation/configuration/#openid-connect-oidc.  Apologies if I submitted this issue into the wrong repo.

In the *Miscellaneous settings* section, the `openid-scopes` setting should be renamed to `scopes`.

I say that because it looks like the configuration is being parsed in https://github.com/openanalytics/containerproxy/blob/2c71c88a0f8a8f71e2551343e09b659c6f11c1fe/src/main/java/eu/openanalytics/containerproxy/auth/impl/oidc/OpenIDConfiguration.java#L68, and that refers to `scopes` instead of `openid-scopes`.

Please let me know if you have any questions about my report.  Thanks much!

**Comment by LEDfan** [comment]
Thanks a lot for reporting this! I just fixed our website.
