### ISSUE TITLE
Docker parameters when calling container image

### ISSUE THREAD

**Issue by Fix3dll** [openanalytics/shinyproxy#483]
I need to add nvidia-ctk parameter `--gpus all` when call container image. I checked the documentation but failed. Is it possible on current Shinyproxy version?

**Comment by LEDfan** [comment]
Hi, this is now part of the ShinyProxy 3.1.0 we released today. Thanks again for your suggestion! See https://shinyproxy.io/documentation/configuration/#docker-device-requests . Note that in the Docker API there is no way to have the same behavior as with `--gpus all`, so the configuration is a bit different.
