### ISSUE TITLE
Allow user groups via web based authentication

### ISSUE THREAD

**Issue by derfl0** [openanalytics/shinyproxy#485]
As our shiny setup grows more and more in groups and users, I've implemented a small web application that handles the authentication in combination with a password reset mechanism via mail.
Unfortunately according to the documentation web based auth has no option to set groups for the users. This way web based auth is not usable in our case.

Could you please add the option to send groups with the http response 200, e.g. as a comma separated list, in the response body?

Thank you in advance and thank you for this great project

**Comment by LEDfan** [comment]
This will be possible in the next release, which will be out soon.

**Comment by LEDfan** [comment]
Hi, this is now part of the ShinyProxy 3.1.0 we released today. Thanks again for your suggestion!
