### ISSUE TITLE
Example for Shiny app reading HTTP headers

### ISSUE THREAD

**Issue by corey-dawson** [openanalytics/shinyproxy#487]
With the new container initialization functionality, username and access groups are no longer set as ENVs in the container, but can be sent as HTTP headers. Is there a shiny example of a shiny app that reads the http headers that can be used to incorporate "initialized containers" functionality? Thanks in advance

**Comment by LEDfan** [comment]
Hi, thanks for your interest! We will provide a full example soon, in the meantime, you can access the usernames through the session object like this:

```R
session$request$HTTP_X_SP_USERID
session$request$HTTP_X_SP_USERGROUPS
```

**Comment by LEDfan** [comment]
We just published a demo for this: https://github.com/openanalytics/shinyproxy-shiny-demo-auth
I'll close this issue, but of course feedback is welcome!
