### ISSUE TITLE
Redis documentation is misaligned after 3.1.0

### ISSUE THREAD

**Issue by danielloader** [openanalytics/shinyproxy#490]
Since 3.1.0 the [docs](https://shinyproxy.io/documentation/configuration/#enabling-session-persistence) around session persistence and Redis both suggest you need a data key and not for the redis config under spring.

For clarification it works with it, and fails without it, but the examples should reflect this.

**Comment by LEDfan** [comment]
Thanks for reporting this, this has been fixed! I'll close this issue, please re-open or open a new issue if you find another problem in the docs.
