### ISSUE TITLE
Embedding apps into website

### ISSUE THREAD

**Issue by sjmgarnier** [openanalytics/shinyproxy#5]
I would like to embed my shiny apps running on shinyproxy into a website running out of a different server. I've tried using iframes, but for some reason the iframe sent by shinyproxy is empty (see here: http://theswarmlab.com/shiny/opinion_dynamics/), while the app displays properly on the shinyproxy server (http://165.230.88.17:8080/app/01_opinion_dynamic). 

I have no clue why this is happening. I don't think there is anything weird with the way I use iframes since the app shows properly when running out of a shiny server (here is another app embedded on the same website using iframes from a shiny server: http://theswarmlab.com/shiny/axelrod/).

**Comment by sjmgarnier** [comment]
Here is the error when inspecting the page containing the iframe in Chrome: 

> Refused to display 'http://address/of/the/app' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by tverbeke** [comment]
@sjmgarnier should be solved in release 0.7.8: the header preventing iframe embedding has been disabled.

**Comment by sjmgarnier** [comment]
@tverbeke Thanks for the update. Any set date for the release of 0.7.8 yet?

**Comment by tverbeke** [comment]
@sjmgarnier: it is already on Github and since a few seconds on the shinyproxy.io site

**Comment by sjmgarnier** [comment]
@tverbeke Well, that was fast :-) I guess you can close this issue now.
