### ISSUE TITLE
Are ports 20.000 and greater accessible to the outside?

### ISSUE THREAD

**Issue by aciobanusebi** [openanalytics/shinyproxy#50]
Are ports 20.000 and greater accessible to the outside world? 

I mean when a user opens an app, then a port (20.000 or greater by default) is opened and I can access the docker container on ADDRESS:PORT even though I am not logged in! I only tested this on my local machine (not on an actual server). Isn't this a security issue? Are there any solutions?

**Comment by aciobanusebi** [comment]
Tried with another configuration (with port forwarding) and there is no problem at all. Perhaps I should study more about networks :).

**Comment by serk12** [comment]
I tried this in a "internal production server by IP" and yes, ports greater than 20.000 are accessible if you have direct access to the machine. WIth IPtables you should be able to fix this.
