### ISSUE TITLE
Configuration files inside docker volume

### ISSUE THREAD

**Issue by ConYel** [openanalytics/shinyproxy#508]
Hello and thank you for this very useful tool!

I am having trouble to connect to shinyproxy when I try to use a "users.yml" file and authentication "simple".
I run the docker with volumes:

 -v ./application.yml:/opt/shinyproxy/application.yml -v ./users.yml:/opt/shinyproxy/users.yml -v logo.png:/opt/shinyproxy/logo.png  docker.io/openanalytics/shinyproxy:3.0.2

in the application.yml I have put:

spring:
  config:
    import:
     - ./users.yml
proxy:
  title: Shiny Proxy Apps
  logo-url: ./logo.png

Furthermore I have the same issue when I put a custom logo. 

Are the volumes wrongly pointed? or is there any other way to configure it?
I have posted the question here #https://github.com/openanalytics/shinyproxy-docker/issues/1#issue-2388203320  too

**Comment by LEDfan** [comment]
Hi, for the logo you'll have to provide an absolute path to the logo, prefixed by `file://`, e.g.:

```yaml
proxy:
    logo-url: file:///opt/shinyproxy/logo.png
```

The `spring.config.import` syntax is only supported since ShinyProxy 3.1.0, therefore please upgrade to ShinyProxy 3.1.1

**Comment by LEDfan** [comment]
The `/opt/shinyproxy/users.yml` location you used is fine, you can then use:

```yaml
spring:
  config:
    import:
     - users.yml
```

**Comment by ConYel** [comment]
Regarding the logs from shinyproxy, where should be pointed a specific volume so we can get them written on the host?

**Comment by LEDfan** [comment]
You can configure the location of the logs, see: https://shinyproxy.io/documentation/configuration/#basic-settings

e.g. if you add

```yaml
logging:
  file:
   name: logs/shinyproxy.log
```

the logs will be in `/opt/shinyproxy/logs` and you can mount this directory as volume.

**Comment by ConYel** [comment]
Thank you!
