### ISSUE TITLE
Wiki unavailable?

### ISSUE THREAD

**Issue by Lovingyourwork** [openanalytics/shinyproxy#51]
Hi - First of all, thank you for Shinyproxy!
Looking forward to authentication via JDBC and would also love authorisation at group level by a mixture of both that and LDAP. (LDAP for the authentication, JDBC for the group) ;-)

Oh yea, I can't get to the wiki anymore - not sure if it's gone or blocked from here?

Cheers!

**Comment by skulmunkie** [comment]
Cant access their site either

**Comment by tverbeke** [comment]
thanks for the feedback - site up again.
