### ISSUE TITLE
Scrolling Issue with reactable in Shiny Application Deployed on ShinyProxy

### ISSUE THREAD

**Issue by flash0926** [openanalytics/shinyproxy#514]
I have a Shiny application with a page developed using reactable. In the development environment, content exceeding the page limits shows a scrollbar, and I can scroll up and down using the mouse wheel, as seen in Figure 1. However, after deploying it to ShinyProxy, I'm unable to view content that extends beyond the page, and scrolling with the mouse wheel doesn't respond, as shown in Figure 2.
There are no hints or errors in the console, within the Shiny program, or in ShinyProxy. Could you assist me in resolving this issue? Might there be any additional compatibility configurations required?
<img width="1212" alt="1" src="https://github.com/user-attachments/assets/56979284-b998-43cb-b19f-e162fb16310d">
<img width="961" alt="3" src="https://github.com/user-attachments/assets/817ed729-e992-4861-a2cf-eef179852de3">

**Comment by LEDfan** [comment]
Hi, I just tested with reactable and for me the scrollbar inside ShinyProxy is working fine.
I tested with the following code:

```R
library(shiny)
library(reactable)

ui <- fluidPage(
  titlePanel("reactable example"),
  reactable(iris, resizable = TRUE, pagination = FALSE, onClick = "expand",
    highlight = TRUE, height = "90vh", columns = list(Sepal.Length = colDef(name = "Sepal Length",
        aggregate = "max", format = colFormat(suffix = " cm",
            digits = 1)), Sepal.Width = colDef(name = "Sepal Width",
        defaultSortOrder = "desc", aggregate = "mean", format = list(aggregated = colFormat(suffix = " (avg)",
            digits = 2)), cell = function(value) {
                    if (value >= 3.3) {
                      classes <- "tag num-high"
                    } else if (value >= 3) {
                      classes <- "tag num-med"
                    } else {
                      classes <- "tag num-low"
                    }
                    value <- format(value, nsmall = 1)
                    span(class = classes, value)
                  }), Petal.Length = colDef(name = "Petal Length",
        aggregate = "sum"), Petal.Width = colDef(name = "Petal Width",
        aggregate = "count"), Species = colDef(aggregate = "frequency")),
    details = function(index) {
          if (index == 3) {
            tabsetPanel(
              tabPanel("plot", plotOutput("plot")),
              tabPanel("subtable", reactable(iris[1:3, 1:2], fullWidth = FALSE))
            )
          } else if (index == 5) {
            paste("Details for row:", index)
          }
        })
)


server <- function(input, output, session) {
  #output$table <- renderReactable({
    #reactable(iris)
  #})
}

shinyApp(ui, server)
```

Can you share an example that is not working for you?
