### ISSUE TITLE
"Default" added to thge app name in browser tab 

### ISSUE THREAD

**Issue by dylancis** [openanalytics/shinyproxy#515]
Each of the app deployed in ShinyProxy shows a suffix to the app name `- Default`. 
Why is that and how can turn that off please?

![image](https://github.com/user-attachments/assets/da86b8b2-deb0-458c-bc50-f9f4b632d1e8)

**Comment by jkkbuddika** [comment]
@dylancis This gets added from the `app.html` template. I ended up adding a custom `app.html` using `proxy.template-path` configuration parameter.

See the following line from default `app.html`:
https://github.com/openanalytics/shinyproxy/blob/14a3224df6b75d70fae676d5e54c6ad691549b97/src/main/resources/templates/app.html#L27

You can basically modify this line to get rid of "- Default".

**Comment by dylancis** [comment]
Thanks a lot @jkkbuddika

**Comment by dylancis** [comment]
Thanks a lot @jkkbuddika
