### ISSUE TITLE
[feature request] application table for non admin users to summary running apps

### ISSUE THREAD

**Issue by parisni** [openanalytics/shinyproxy#532]
hi

currently the admin has a table with all running apps accross the sp instance, and it can be used to kill apps.

the same table would be useful for a given (non-admin) user to be able to quickly release resources, or restore some app.

currently this process is quite painful since user has to lookup every single app to check if there is running instances.

**Comment by LEDfan** [comment]
Hi, this is supported by setting the `my-apps` property to either `Modal` or `Inline`, see the first section and screenshots here: https://shinyproxy.io/documentation/ui/

**Comment by parisni** [comment]
This is exactly what I was dreaming about
