### ISSUE TITLE
How to authenticate Shiny proxy user through token from another server.

### ISSUE THREAD

**Issue by praneetchandra** [openanalytics/shinyproxy#58]
I am trying to authenticate Shiny proxy from token based on my application but don't see any way of doing it. Any tips on it ? I am also fine to pay for custom development.

**Comment by fmichielssen** [comment]
Hi @praneetchandra ,

What type of token is it? OpenID? Shinyproxy currently only supports Keycloak as an OpenID provider, though I believe there have been some requests for other types as well.

**Comment by praneetchandra** [comment]
@fmichielssen - We use Auth0 for authentication, can we do some custom work to support it. I am currently looking for someone to come in and do that custom piece of work for us.

**Comment by fmichielssen** [comment]
ShinyProxy 2.0 supports Auth0.
Please see https://www.shinyproxy.io/configuration/#openid-connect-oidc for details.
