### ISSUE TITLE
Error: status code 500

### ISSUE THREAD

**Issue by lawwu** [openanalytics/shinyproxy#6]
I built and ran the project using  java -jar shinyproxy-0.8.0.jar and navigated to http://localhost:8080/. Logged in and tried to navigate to the test applications but am getting a status code 500 error.

```
Error
Status code: 500

Message: Failed to start container: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
```

**Comment by tverbeke** [comment]
Hi @lawwu,

Thanks for your interest in ShinyProxy. Did you check the relevant section in our [troubleshooting guide](http://www.shinyproxy.io/troubleshooting/#failed-to-start-container)? It that does not help, don't hesitate to post on our [support portal](https://support.openanalytics.eu/) and we'll help you get up and running.

Best,
Tobias
