### ISSUE TITLE
Is there a way I can use this login functionality in any Rinno app

### ISSUE THREAD

**Issue by vikram-rawat** [openanalytics/shinyproxy#61]
There is a project called Rinno

https://github.com/ficonsulting/RInno

It takes for shiny app and convert it into a desktop app. And lately I have been using it to create apps for my colleagues but now my IT team had intervained because they are not secure enough.

I just want to know shiny proxy has a java login functionality. Is there a way we can use it in rinno app.

**Comment by fmichielssen** [comment]
Hi @vikram-rawat ,

ShinyProxy's authentication backends are implemented in Java, yes. But I don't really understand your use case. What kind of integration did you have in mind?

**Comment by vikram-rawat** [comment]
Shiny doesn't have an authentication system at all. Shiny proxy can help
people on server build an authentication if we can do that in local windows
app then it would be complete in building standard software. I do create
rinno app regularly for colleagues but its very hard to get approval for
installation from IT team. That why I wondered if I can use shiny proxy
authentication system.

I just wondered... Nothing much.

गुरु, 31 मई 2018, 5:33 pm को Frederick Michielssen <notifications@github.com>
ने लिखा:

**Comment by tverbeke** [comment]
Thanks for the feedback @vikram-rawat  In terms of maintenance and ease of deployment, using Shiny as a web application (inside ShinyProxy) will probably be more effective (compared to provisioning desk top applications for which updates will probably more difficult to push to users etc.). Out of the box integration with Rinno is not possible, I think.

**Comment by vikram-rawat** [comment]
Thanks for the reply I just wanted to know if that's isolated enough that
can be used outside in an RInno app.

No worries kudos for such a great project anyways. Keep up the work.

And thanks for answering.

गुरु, 31 मई 2018, 9:17 pm को Tobias Verbeke <notifications@github.com> ने
लिखा:
