### ISSUE TITLE
Redirect to homepage after successful send of error report

### ISSUE THREAD

**Issue by donarus** [openanalytics/shinyproxy#63]
Hi everyone, 
  I hit a problem that when a user sends an error report using the "Report issue" button, he is redirected back to the homepage. I think this is an invalid behaviour and can be considered as a bug because it is possible that the error is somehow recoverable or just not crucial, but the current R/Shiny session is lost. It should be possible to send the error report and stay at the current page.

**Comment by fmichielssen** [comment]
Hi @donarus ,

A good point. As you can see here, we intended to do that, but it hasn't been implemented yet: [IssueController](https://github.com/openanalytics/shinyproxy/blob/master/src/main/java/eu/openanalytics/shinyproxy/controllers/IssueController.java#L50)

**Comment by LEDfan** [comment]
As I mentioned in https://github.com/openanalytics/shinyproxy/issues/149 , the issueform is now a client-side form and will not reload or redirect the page. This is now included in [ShinyProxy 2.6.0](https://shinyproxy.io/downloads/#260) (ContainerProxy 0.8.10).

Thank you for the suggestion!
