### ISSUE TITLE
App does not show, but container is activated successfully

### ISSUE THREAD

**Issue by mg515** [openanalytics/shinyproxy#64]
To describe what's going on briefly: I successfully log into shinyProxy, click on the application link I want to start. Loading screen shows on, container is spinning up. Finally, when container is finished and the shiny app is supposed to show up, firefox gives me a `We can’t connect to the server at unruffled_bell`, where `unruffled_bell` is the name of the container used.

In the `shinyproxy.log` I can see `Proxy activated [user: user1] [app: app1]`as expected.

I suspect some sort of a weird port problem. 
Relevant part of the application.yml:
`docker-cmd: ["R", "-e", "shiny::runApp('/path/to/shinyapp', port = 3838, host = '0.0.0.0')"]`
Also, if I use `host = '127.0.0.1'` fun ends where the container just never gets responsive and it keeps on loading.

Any ideas?

**Comment by fmichielssen** [comment]
Hi @mg515 ,

Are you running shinyproxy on a context path other than `/` ?
If yes, make sure to set the `contextPath` setting, more info at https://www.shinyproxy.io/configuration/#general

**Comment by mg515** [comment]
Thanks for your reply @fmichielssen !
I tried running shinyproxy also on other paths than `/`, but without success. However, in the end what solved my problem was starting docker containers at `20000` instead of `25000`, which was my previous setting. No idea how that has any impact on it, but it works.

**Comment by fmichielssen** [comment]
Ok, closing the issue then. Feel free to reopen if the issue should occur again.
