### ISSUE TITLE
logo-url is not working

### ISSUE THREAD

**Issue by KZARCA** [openanalytics/shinyproxy#66]
Hi,
logo-url does not seem to be working with version 1.1.1: the logo http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png does not show, instead we get the spring leaf  :)
Best.

**Comment by tverbeke** [comment]
Thanks for the feedback, @KZARCA. We have 1.1.1 instances where the `logo-url` seems to be working properly, but will investigate.

**Comment by Brianicest** [comment]
Hi @tverbeke 

The logo-url in the application.yml file only changes the nav-bar logo. I wanted the same custom logo to be on the browser tab but I still see the spring leaf, is there a way to solve this?
Thanks for the work.

**Comment by fmichielssen** [comment]
The `logo-url` was originally intended to be used in the navigation bar, not as a favicon.
But I think it would make sense to use it as a favicon as well, so let's keep this open as a feature request

**Comment by tverbeke** [comment]
using a downsized logo as the favicon will probably not look good in all cases (?) - a separate `favicon-url` may be a better option.

**Comment by dylancis** [comment]
@tverbeke  agrred with you Tobias, better to get a separate favicon-url settings here.

**Comment by tverbeke** [comment]
@dylancis @KZARCA @Brianicest a new setting `favicon-path` made it into ShinyProxy 2.0.5 which now allows to set custom favicons for ShinyProxy.
