### ISSUE TITLE
Changes not taking effect on docker image

### ISSUE THREAD

**Issue by Brianicest** [openanalytics/shinyproxy#71]
I have developed a solution and decided to use shinyproxy.

I have the following problem:

A user needs to capture data on the solution, which must be stored and updated on the database for all users accessing the solution, I used SQLite and with R for this.

Now when I log in and capture data, it saves, but when i log in with a different user I dont get to find the captured data.

The problem is that saving data doesnt seem to be saving on the docker image, why is this and how can I go about remedying it?

For problem testing purposes:

Solution link: https://www.oisbotash.com

Data Capturer user:

username: dispatchclerkB@botash.co.za

password: Fyyds7zF.

Admin user:

username: info@qnum.co.za

password: prupre35A2.

Testing:

Inside the solution, if you go to the data management tab, data entry and then right click on an table and insert a new row, click save changes, it must safe new changes to the docker image but its only temporarily doing so, the other user cant see the changes made.

**Comment by fmichielssen** [comment]
Hi @Brianicest,

I have added a comment to your question on the support forum:
https://support.openanalytics.eu/t/issue-with-shinyproxy-user-input-data-storage/616
