### ISSUE TITLE
Private Registry

### ISSUE THREAD

**Issue by statup-github** [openanalytics/shinyproxy#72]
Hi,

I think this is a feature request; but perhaps I've just been unable to find the solution. 

How do I provide a login for a private container registry? I tried adding it to the URL but that doesn't work.

Thanks,
Stefan

**Comment by andodet** [comment]
Tried to Google around without much luck. Was wondering if, beyond deploying on k8s, this has been implemented natively on Shinyproxy.

**Comment by Wesseldr** [comment]
new link to the image-pull-secret is:
https://www.shinyproxy.io/documentation/configuration/#kubernetes

**Comment by LEDfan** [comment]
For Kubernetes you can use the link provided above. For Docker and Docker swarm this was implemented in ShinyProxy 3.0.0, see: https://shinyproxy.io/documentation/configuration/#docker-registry-username
