### ISSUE TITLE
any way to run in windows without docker?

### ISSUE THREAD

**Issue by dockstreet** [openanalytics/shinyproxy#74]
Hi - is it possible for testing local development purposes to run without docker/kubernetes installed? 

Would be nice to see a couple of Dash / Shiny apps locally and test before deploying to a remote server. I believe Docker requires administrative rights to install, for which many users may not have.

**Comment by fmichielssen** [comment]
Hi @dockstreet ,

I'm afraid there is currently no way to run things without a docker or kubernetes installation.
We'll discuss this internally to see how it fits on the roadmap.

**Comment by tverbeke** [comment]
The advantage of using Docker is that ShinyProxy can more or less guarantee that the app will function in exactly the same way locally (in an R session in your IDE). For our own development, we always just test the Shiny apps locally prior to packaging these into a container for deployment.

**Comment by LEDfan** [comment]
As I believe that your question is answered, I'm closing this issue. Feel free to re-open it if you need more help.
