### ISSUE TITLE
ShinyProxy without LDAP

### ISSUE THREAD

**Issue by helgasoft** [openanalytics/shinyproxy#75]
Trying to install ShinyProxy on Ubuntu 16.04 LTS with Java 9. 
The verification command
```
sudo docker run -p 3838:3838 openanalytics/shinyproxy-demo R -e 'shinyproxy::run_01_hello()'
```
works fine and app is showing in the browser.
File _application.yml_ and _shinyproxy-1.1.1.jar_ reside in the same folder.
For testing purposes the _.yml_ config file is set to "**authentication: simple**". 
Unfortunately there is an error with Java:
```
java -jar shinyproxy-1.1.1.jar

# The shinyproxy.log file says:
Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ldapContextSource' defined in class path resource [org/springframework/boot/autoconfigure/ldap/
```
Noticed your source file [pom.xml](https://github.com/openanalytics/shinyproxy/blob/eebddbb143c9546276f24998e98131b75efce088/pom.xml) has at least two dependencies on "ldap"...  Found also [this post](https://support.openanalytics.eu/t/shinyproxy-without-ldap/85). 
We do not want to mess with LDAP _at all_ at this point.  Still, we installed OpenLDAP following [this guide](https://www.linuxbabe.com/ubuntu/install-configure-openldap-server-ubuntu-16-04) without "Basic Post-Installation Configuration" to see if just having LDAP installed would improve the outcome. But the Java compilation error remains the same. 

Please advise - could ShinyProxy be installed without LDAP and (if yes) how ? 

**Edit**:  the _temporary workaround_ from [this post](https://github.com/openanalytics/shinyproxy/issues/4) works
```
java -XaddExports:java.naming/com.sun.jndi.ldap=ALL-UNNAMED -jar shinyproxy-1.1.1.jar
```
not sure how it affects operations and performance...

**Comment by fmichielssen** [comment]
Hi @helgasoft ,

Which java version are you using?

Shinyproxy is based on Spring Boot, which will attempt to autoconfigure a number of components, including ldap. If you set `authentication: simple`, the ldap component will never be used (and its configuration will be empty), but they might still throw an exception like this if a required class was not found.

**Comment by helgasoft** [comment]
Yes - exactly what is happening, Java is adding redundant components. I'm using latest Java 9 (first line on my post).  So, should one just use the workaround?

**Comment by LEDfan** [comment]
This seems like an old bug which should be fixed in the latest ShinyProxy versions. Therefore I'm closing this isssue.
Feel free to re-open it if you need more help.
