### ISSUE TITLE
ShinyProxy listen only on 127.0.0.1

### ISSUE THREAD

**Issue by robinfdx** [openanalytics/shinyproxy#77]
Hello,

It's possible to have a shinyproxy that only listen on the localhost interface ?

Thanks you.

**Comment by fmichielssen** [comment]
Hi @robinfdx ,

Currently shinyproxy listens on all interfaces (0.0.0.0), but it's a good idea to have a setting for this.

The next release will have a `proxy.bind-address` setting:
https://github.com/openanalytics/containerproxy/commit/702bab935b0d0a30297bdbe28fd1b4d5ea934d62
