### ISSUE TITLE
While using keycloak authentication, it redirects to http://mypiaddress:8080/login after sign out

### ISSUE THREAD

**Issue by shizidushu** [openanalytics/shinyproxy#78]
Maybe it is better to redirects to http://mypiaddress:8080 after sign out when using keycloak authentication. http://mypiaddress:8080/login doesn't let keycloak user log in.

**Comment by fmichielssen** [comment]
Hi @shizidushu ,

Agreed, a redirect to `/` makes more sense than `/login`.
A commit has been made, will be in the next release:

https://github.com/openanalytics/containerproxy/commit/a087f2d4baf9c03a50c3a942d468054f099dcac8
