### ISSUE TITLE
contextPath is not enough

### ISSUE THREAD

**Issue by billy34** [openanalytics/shinyproxy#79]
Hello

I'm using version 2.0.1 of shinyproxy

I had troubles launching shinyproxy in a container using a sub path (eg http://hostname/shinyproxy/)

Adding `server.contextPath=/shinyproxy` to environment or these lines to `application.yml`
> server:
> &nbsp;&nbsp;contextPath: /shinyproxy

as suggested here did not solve the problem. Landing page was unreachable returning a 404

After several change and try steps and looking into spring boot I managed to make it working by
providing also the following key/value `server.servlet.context-path=/shinyproxy` or in `application.yml`

>server:
>&nbsp;&nbsp;servlet:
>&nbsp;&nbsp;&nbsp;&nbsp;context-path: /shinyproxy

It seems that server.contextPath is ShinyProxy application specific and that we need to configure also the backing servlet server (undertow)

I hope this will help as ShinyProxy is a very valuable application

**Comment by fmichielssen** [comment]
Hi @billy34 ,

Thanks for catching this. In Shinyproxy 2.0 we switched from Spring Boot 1.x to 2.x, and the setting name has changed there.

This is fixed in commit 58f135828e3b24cf9976069da58dcbf4b3f502fb
and will be in the upcoming release 2.0.2.
