### ISSUE TITLE
Per-application disabling of auth

### ISSUE THREAD

**Issue by richfitz** [openanalytics/shinyproxy#81]
This is a feature request - please feel free to just say no :grin:

In https://www.shinyproxy.io/configuration/ the auth and users are set at the whole proxy level and access is given via lines like:

```
    access-groups: [scientists, mathematicians]
```

Am I right that there is no way of per-application _entirely_ removing the authentication requirement (I think that means that there will be no load balancing either, right?).  Would supporting something like a per-application disabling of authentication be something you'd be willing to support?

**Comment by fmichielssen** [comment]
Removing authentication from the `/app/...` URLs will be straightforward, but supporting anonymous users on the index page requires some additional work I believe.
Also, some authentication backends like OpenID and Keycloak have additional filters installed, those will have to be adjusted as well.

**Comment by LEDfan** [comment]
See issue #330 for an explanation why this is quite difficult to achieve.
