### ISSUE TITLE
[Feature Request] Perform docker pull if image not on host

### ISSUE THREAD

**Issue by SudoBrendan** [openanalytics/shinyproxy#82]
Greetings,

I'm noticing many users (including myself) being confused by a quirk of ShinyProxy: if an image doesn't exist on the docker host, ShinyProxy refuses to boot it. This issue isn't reported here, but rather, on the configuration examples provided by your example repo:

https://github.com/openanalytics/shinyproxy-config-examples/issues/4
https://github.com/openanalytics/shinyproxy-config-examples/issues/2

This missing feature is non-obvious to newcomers, and makes the shinyproxy docker container unable to stand on it's own (it requires that it's host contain more than docker, namely, all the docker images it serves). Is there an obvious reason this requirement exists, or could `docker pull` be invoked if an image isn't found on the host? This missing feature makes deploying shinyproxy on docker orchestrators difficult, where admins shouldn't have to care about host requirements, and where automated janitors might sweep away "unused" images shinyproxy relies on, breaking the site.

**Comment by baswanders** [comment]
+100. It took me a long time to understand this. 
It would be great if it could pull the images.

**Comment by robsonyeg** [comment]
Any roadmap to have this feature?

**Comment by LEDfan** [comment]
This has been implemented as part of ShinyProxy 3.0.0, see: https://shinyproxy.io/documentation/configuration/#docker-image-pull-policy
