### ISSUE TITLE
[KeyCloak] : Get Client roles instead of Realm ones

### ISSUE THREAD

**Issue by billy34** [openanalytics/shinyproxy#83]
Hello
Is it possible to use client roles instead of realm roles with KeyCloak ?
Looking into keycloak adapter documentation it seems thats it's possible providing that the following configuration is set `use-resource-role-mappings=true`
I tried without success the following settings
> proxy.keycloak.use-resource-role-mappings=true
> server.keycloak.use-resource-role-mappings=true
> keycloak.use-resource-role-mappings=true

I defined realm role and client role and assigned both of them to my user. When I look to environment variable of spawned container only realm roles are available (USER being my realm role)
> SHINYPROXY_USERGROUPS=USER,OFFLINE_ACCESS,UMA_AUTHORIZATION

I looked into ShinyProxy and ContainerProxy code but found no clues except that I'm running version 4.3.0.final of Keycloak and you are using version 3.0.0.Final of adapter.

Am I missing something or is it not supported ?

Thanks

**Comment by Okram1** [comment]
I have the same issue using 4.4.0.Final/

Their documentation points to this setting but it does not have an effect inside application.yml

proxy.keycloak.use-resource-role-mappings=true

@billy34  Have you found a solution to this?

**Comment by billy34** [comment]
Not yet. I'm using realm roles for now. Not perfect but works !
Source code is not easy to explore and log trace are not very helpfull and I'm currently troubleshooting other tricky configuration between Keycloak, shinyproxy and traefik proxy. It fills my day :-)

**Comment by fmichielssen** [comment]
Hi,

A commit has been made on develop that enables the `proxy.keycloak.use-resource-role-mappings=true` setting:
https://github.com/openanalytics/containerproxy/commit/bc3ab46dd5f71e64ce2075557a4014a5279a98be

This will be in the upcoming release of shinyproxy.

**Comment by tverbeke** [comment]
@billy34 @Okram1 released as part of ShinyProxy 2.0.5.
