### ISSUE TITLE
Allow passing OIDC access token to R Shiny containers

### ISSUE THREAD

**Issue by brasie** [openanalytics/shinyproxy#86]
It would be great to have a way to pass the OIDC access token that ShinyProxy gets during authentication along to the R Shiny applications launched by that user.

For example, perhaps similar to the `SHINYPROXY_USERNAME` and `SHINYPROXY_USERGROUPS` environment variables, there could be `SHINYPROXY_OIDC_ACCESS_TOKEN`, or some such.

This comes up because we potentially want the R Shiny applications to authenticate against an API using the access token.

**Comment by tverbeke** [comment]
A new environment variable `SHINYPROXY_OIDC_ACCESS_TOKEN` is available since ShinyProxy 2.0.3.
