### ISSUE TITLE
KeyCloak auth sets first name + last name as SHINYPROXY_USERNAME

### ISSUE THREAD

**Issue by gluc** [openanalytics/shinyproxy#88]
When accessing the SHINYPROXY_USERNAME variable, it seems to be 

KeyCloak.FirstName + Space + KeyCloak.LastName

I would expect

KeyCloak.Username 

or

KeyCloak.ID

instead, which defaults to the user's email and seems to be unique.

![image](https://user-images.githubusercontent.com/626832/45049750-dd9a1d00-b07f-11e8-807b-5278df1b9a2a.png)

Or is there another way to unambiguously determine the user from within shiny?

**Comment by fmichielssen** [comment]
Hi @gluc ,

Good point, this name may not work in all scenarios.
A change has been committed in develop:
https://github.com/openanalytics/containerproxy/commit/8c3c91b647262b579612013a96185e6e2b18ff7f

Here, you can specify the attribute to use: `proxy.keycloak.name-attribute`
* name (default, current behaviour)
* preferred_username
* nickname
* email

**Comment by bjornlind** [comment]
Naice!.. Can you have it as a parameter in the application.yml?

**Comment by tverbeke** [comment]
@bjornlind the attribute `proxy.keycloak.name-attribute` refers indeed to a property that can be set in the `application.yml` file e.g.

```
proxy
  keycloak
    name-attribute: email
```

**Comment by bjornlind** [comment]
Thanks!
