### ISSUE TITLE
Setting custom content-path does not work

### ISSUE THREAD

**Issue by yurymuski** [openanalytics/shinyproxy#90]
Hello, I am trying to configure shinyproxy to be hosted on /shiny
Following docs https://www.shinyproxy.io/configuration/  I should set in application.yml:
landing page: /shiny
server:
  servlet:
    context-path: /shiny
But this configs does not work, shiny still listens on root /
Could you please provide right config to use?

**Comment by mnazarov** [comment]
Setting the `context-path` should be enough. You don't need to set-up the `landing-page`, since this is relative to the context-path, and you would get `.../shiny/shiny` address.

**Comment by yurymuski** [comment]
found that issue: https://github.com/openanalytics/shinyproxy/issues/79
and seems fix is on 2.0.2+ shiny only https://github.com/openanalytics/shinyproxy/commit/58f135828e3b24cf9976069da58dcbf4b3f502fb
