### ISSUE TITLE
 No suitable driver found for jdbc:monetdb Bugg

### ISSUE THREAD

**Issue by bjornlind** [openanalytics/shinyproxy#93]
When using the Usage Statistics plugin for monetDb we get error in the lof file: No suitable driver found for jdbc:monetdb://localhost:50000/usage_stats. We can see in the soruce file taht here is no monetdb driver available. why? 

influxdb works fine...

**Comment by tverbeke** [comment]
This has been fixed in ShinyProxy 2.0.4. Can you confirm it works for you now?

**Comment by bjornlind** [comment]
Its tested and is now working. Thanks

**Comment by tverbeke** [comment]
You're welcome!
