### ISSUE TITLE
Bootstrap grid breaks in container

### ISSUE THREAD

**Issue by bjornol** [openanalytics/shinyproxy#96]
We are running big shiny-apps in containers with shinydashboard. The apps have bootstrap grid but this grid break in shinyproxy. We have been running these apps in shiny server for a while with no issues. Seems to be the iframe in shinyproxy that breaks the grid (Divs dont stack on mobile/or at all really). The same is really for shinyproxy also. on the main page where all the apps are listed is very very small on mobile. WHy dosent bootsrap grid work in containers. And also why dosen shinyproxy look better on shinyproxy mobile in general?

**Comment by bjornlind** [comment]
I found a solution: By adding <meta name="viewport" content="width=device-width, initial-scale=1"/> to in the header solved this problem

**Comment by martindut** [comment]
I'm also having issues to get my shinydashboard pages to display in shinyproxy. How do I put that code in the shinyproxy header?

**Comment by bjornol** [comment]
You need to put the <meta name="viewport" content="width=device-width, initial-scale=1"/> inside the app.html header and rebuild the project

**Comment by martindut** [comment]
> You need to put the `<meta name="viewport" content="width=device-width, initial-scale=1"/>` inside the app.html header and rebuild the project

Thanks for the reply. I'm running shiny proxy in a Docker container, so will figure it out.

**Comment by shrektan** [comment]
You can use the `template-path` config and place the app.html there... see https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template for more...
