### ISSUE TITLE
Keycloak + influxdb-logging + empty names => throwing HTTP 500 ERROR

### ISSUE THREAD

**Issue by Diniodoc** [openanalytics/shinyproxy#97]
Hello,

first of all thanks for developing the amazing shinyproxy app!

I run into trouble by using shinyproxy with keycloak-auth and influxdb-userstat logging.

If you try to login into shinyproxy with an user account with empty “First Name” & “Last Name” fields (in keycloak), shinyproxy is throwing an HTTP 500 ERROR.

That problem only occurs when statistic-logging is enabled.
I think the problem is caused by trying to write into the influxdb with an empty “null”-user.
As you can see in the log the user is named by fist and last name, so with empty fields it becomes “null” (Maybe related to issue [#88](https://github.com/openanalytics/shinyproxy/issues/88) ).

Is there a simple way to fix it because I found no way to force people to add their names during the registration process of keycloak?

Thanks,
Dinio

LOG:

`2018-09-24 15:03:43.985 DEBUG 1 --- [ XNIO-2 task-10] o.k.adapters.RequestAuthenticator        : AUTHENTICATED

2018-09-24 15:03:43.985 DEBUG 1 --- [ XNIO-2 task-10] f.KeycloakAuthenticationProcessingFilter : Auth outcome: AUTHENTICATED

2018-09-24 15:03:43.988  INFO 1 --- [ XNIO-2 task-10] e.o.containerproxy.service.UserService   : User logged in [user: null]

2018-09-24 15:03:43.996 ERROR 1 --- [ XNIO-2 task-10] io.undertow.request                      : UT005023: Exception handling request to /sso/login
`

**Comment by tverbeke** [comment]
Hi @Diniodoc,

Do the new facilities released with ShinyProxy 2.0.6 (and discussed in #88), namely the new `proxy.keycloak.name-attribute` attribute allow you to fix your issue?

Best,
Tobias

**Comment by Diniodoc** [comment]
THX for the hint at the new attribute i will try it later and close the issue if it works.
